### ISSUE TITLE
[BUG] Update button in Home Assistant does not work anymore

### ISSUE THREAD

**Issue by smarthomejunkie** [Blueforcer/awtrix-light#101]
# Bug report

## Describe the bug

The update button in Home Assistant does not work anymore.

## Additional information

- Devices involved:
  - Model: Ulanzi Awtrix Smart Pixel Clock 2882 (TC001)
  - AWTRIX-LIGHT version: v0.58

## To Reproduce

Click the update button in Home Assistant

## Expected behavior

The update starts on the display

## Logs

```text
(optional) Add relevant logs which could help tackle the problem.
```

**Comment by smarthomejunkie** [comment]
What I mean is that that button doesn't even work if you use and older firmware and want to update to v1.59. Multiple users mentioned it to me.

**Comment by luchtgitaar** [comment]
@smarthomejunkie : Sorry for bumping this already closed thread, but is the update button suppose to update the firmware via OTA? Because that seems not working for me. I have to manual update.

**Comment by luchtgitaar** [comment]
> Pressing the 'start update' button in Home Assistant indeed doesn't work anymore. I had to update my device using the physical buttons on the clock.
> 
> ![Scherm­afbeelding 2023-05-12 om 12 54 48](https://user-images.githubusercontent.com/2742292/237951348-157dd0f3-1d3e-4a87-a97f-b84cc34d1a84.png)

How do you update using the buttons?

**Comment by smarthomejunkie** [comment]
I tested this today to update to version 0.62 from 0.61. Updating using the button in HA went real slow and in the end, the device was not updated. Updating using the menu on the clock itself works well.

**Comment by smarthomejunkie** [comment]
> > Pressing the 'start update' button in Home Assistant indeed doesn't work anymore. I had to update my device using the physical buttons on the clock.
> > ![Scherm­afbeelding 2023-05-12 om 12 54 48](https://user-images.githubusercontent.com/2742292/237951348-157dd0f3-1d3e-4a87-a97f-b84cc34d1a84.png)
> 
> How do you update using the buttons?

Long press the middle button to enter the menu.
