### ISSUE TITLE
[FEATURE REQUEST] - Longer Apptime Interval

### ISSUE THREAD

**Issue by RDG88** [Blueforcer/awtrix-light#106]
# Feature Request - Longer Apptime Interval

### Is your feature request related to a problem?

We have been testing with sending a longer AppTime interval via the API and/or MQTT request, however, it seems like that any value above 60000ms is ignored. Setting it higher then this value, it seems the rotation from clock -> custom app goes back to 4 seconds.

### Describe the solution / feature you'd like
I would like to be able to set a Longer Apptime Interval then 60 seconds, more like 15 minutes.
I use the clock primarily as a clock, but once every 15 minutes i would like to see a custom app.

### Describe alternatives you've considered
Disable transition and create my own timers in Nodered/HA, however it would be nice to have a solution "build in".

**Comment by mark-skel** [comment]
I just been looking at this to try and keep the clock on for longer before cycle through custom apps. (Wife acceptance factor) would be good to be able to control this. Inbuilt as it's an in built app.

**Comment by Blueforcer** [comment]
> I just been looking at this to try and keep the clock on for longer before cycle through custom apps. (Wife acceptance factor) would be good to be able to control this. Inbuilt as it's an in built app.

Already added. See closing commit
