### ISSUE TITLE
[FEATURE REQUEST]  Sound file check before timer creation

### ISSUE THREAD

**Issue by dalv666** [Blueforcer/awtrix-light#109]
# Feature Request

When using timer https://github.com/Blueforcer/awtrix-light/blob/main/docs/api.md#timer sound file is not checked. 
It would be better to first check if there is such a file and if there is no such file, give an error in the response. And don't create a timer. Otherwise, the timer will run silently.

### Describe the solution / feature you'd like

Check if there is such sound file exist before timer creation.

**Comment by Blueforcer** [comment]
i don't think this is a good idea,
Apart from the fact that there is no response with MQTT, you rely on a timer being started. If the timer does not start at all, is also bad. So it is at least displayed on the matrix.
