### ISSUE TITLE
Use MQTT Retained messages for custom pages

### ISSUE THREAD

**Issue by poblabs** [Blueforcer/awtrix-light#11]
If I create a custom page, and reboot the esp, the page is gone off the clock. Is it possible to use retained messages to auto load those pages again on reboot?

**Comment by Blueforcer** [comment]
retained messages has nothing to do with the client.
With retained message you tell the broker to send the message on every connect. 
So yes, you could so this

**Comment by poblabs** [comment]
Great, thank you for the update
