### ISSUE TITLE
[FEATURE REQUEST]

### ISSUE THREAD

**Issue by MonsterD1** [Blueforcer/awtrix-light#110]
# Feature Request

### Is your feature request related to a problem?

short battery life time even with 4400mAh internal battery - I am suing the clock as a matrix display to show clear massages to a user. unfortunately the battery uptime on "no Matrix mode" is only ~6h. 

### Describe the solution / feature you'd like

battery saving mode with no Matrix (avaiable) and maximal battery saving option on ESPside to in crease the standby battery time

### Describe alternatives you've considered

turn off all additional sensors, slow down esp clock etc

**Comment by Blueforcer** [comment]
There is a small battery in it. A battery saving mode doesn't make sense if you restrict features or disable the matrix
