### ISSUE TITLE
[BUG] Drawing > 4 objects in "notify" fails in v0.61

### ISSUE THREAD

**Issue by dieselrabbit** [Blueforcer/awtrix-light#112]
# Bug report

## Describe the bug

Black screen when attempting to to draw 5 filled rectangles in a notification.

## Additional information

- Devices involved:
  - Model: Ulanzi Awtrix Smart Pixel Clock 2882 (TC001)
  - AWTRIX-LIGHT version: v0.61

## To Reproduce

Publish a notification to `[clock-name]/notify` with a payload of:
```json
{
    "draw": [
        {
            "df": [
                14,
                3,
                3,
                5,
                "#00C0C0"
            ]
        },
        {
            "df": [
                18,
                2,
                3,
                6,
                "#FFFF00"
            ]
        },
        {
            "df": [
                22,
                2,
                3,
                6,
                "#FFFF00"
            ]
        },
        {
            "df": [
                26,
                1,
                3,
                7,
                "#FFFF00"
            ]
        },
        {
            "df": [
                2,
                0,
                3,
                9,
                "#FFFF00"
            ]
        }
    ]
}
```
Notice the screen draws nothing for the notification time, then returns to the normal app cycle.

If I remove ANY 1 drawing object from that payload, drawing of the four remaining objects works as expected.

## Expected behavior

I would expect all five objects to draw.

## Logs

```text
(optional) Add relevant logs which could help tackle the problem.
```

## Additional context

I updated to v0.61 via the clocks update option using physical buttons to navigate the clocks menu.
I was able to draw ~10 objects, mixed between filled rectangles and text with v0.60. 
I'm _trying_ to draw up to 28 objects in a single notification or app.

**Comment by Blueforcer** [comment]
Its because i missed to increase the jsonbuffer:
https://github.com/Blueforcer/awtrix-light/blob/main/src/DisplayManager.cpp#L1752

i will fix it for the next version
