### ISSUE TITLE
[FEATURE REQUEST] Disable transition when one app

### ISSUE THREAD

**Issue by dalv666** [Blueforcer/awtrix-light#114]
# Feature Request

### Is your feature request related to a problem?

When one application remains, the transition remains from this application to it.

### Describe the solution / feature you'd like

Check if the application is left alone, do not make the transition.

**Comment by Blueforcer** [comment]
Normally awtrx checks and set the transision after each loop change.
Tell me how to reproduce it.

**Comment by dalv666** [comment]
`curl --location 'http://192.168.50.215/api/apps' \
--header 'Content-Type: application/json' \
--data '[
    {
        "name": "time",
        "show": true,
        "pos": 0
    },
    {
        "name": "date",
        "show": false,
        "pos": 1
    },
    {
        "name": "temp",
        "show": false
    },
    {
        "name": "hum",
        "show": false
    },
    {
        "name": "bat",
        "show": false
    }
]'`
And then

`curl --location 'http://192.168.50.215/api/apps' \
--header 'Content-Type: application/json' \
--data '[
    {
        "name": "time",
        "show": true,
        "pos": 0
    },
    {
        "name": "date",
        "show": false
    },
    {
        "name": "temp",
        "show": false
    },
    {
        "name": "hum",
        "show": false
    },
    {
        "name": "bat",
        "show": false
    }
]'`

**Comment by dalv666** [comment]
I LOVE YOU!
