### ISSUE TITLE
Add IP and MAC address to stats and built in app [FEATURE REQUEST]

### ISSUE THREAD

**Issue by deepcoder** [Blueforcer/awtrix-light#115]
Would it be possible to add the devices IP and MAC address to the stats JSON return? Useful to have in MQTT, one less place to look for address if devices is in DHCP mode. And MAC address makes creating a unique instance ID easier. Also add a built-in app that displays IP and MAC, have it turned off by default, but able to be displayed. Helpful if you have multiple devices.

Thx for your work on this project!

**Comment by Blueforcer** [comment]
Awtrix Shows it's IP on every boot. 
I don't see any advantage when sending it again every 10 seconds.
It is not worth to implement a native app for this purpose, because this information would not be useful for even 1% of all users.
