### ISSUE TITLE
USB flash with 0.61 caused this message to be continually sent to log[BUG]

### ISSUE THREAD

**Issue by deepcoder** [Blueforcer/awtrix-light#116]
Using the Web USB flasher,

1st, minor issue: web page shows 0.60, not 0.61 on flashing.

2nd, after flashing and going into AP Mode, this error is continually displayed in log:

[ 82826][E][WiFiUdp.cpp:221] parsePacket(): could not receive data: 9
[ 82836][E][WiFiUdp.cpp:221] parsePacket(): could not receive data: 9
[ 82846][E][WiFiUdp.cpp:221] parsePacket(): could not receive data: 9
[ 82856][E][WiFiUdp.cpp:221] parsePacket(): could not receive data: 9
[ 82866][E][WiFiUdp.cpp:221] parsePacket(): could not receive data: 9
[ 82876][E][WiFiUdp.cpp:221] parsePacket(): could not receive data: 9
[ 82886][E][WiFiUdp.cpp:221] parsePacket(): could not receive data: 9

**Comment by Blueforcer** [comment]
That's not a known problem.
I think something went wrong in your update procedure, try to erase it and reflash it
