### ISSUE TITLE
Sync multiple units [FEATURE REQUEST]

### ISSUE THREAD

**Issue by deepcoder** [Blueforcer/awtrix-light#118]
I am trying to find a way to sync either the rotation of apps or display text on two or more units. Is there a way to do this currently via MQTT or API? If not, would there be a way to add some type of synchronization between two or more devices? For example (a simplistic solution) start rotation or apps at a specific time hack, example: start at xx:xx:x5 (start rotation at every 5 second hack).

Thanks for your work on this project!

**Comment by Blueforcer** [comment]
Just try to call an app on both awtrix at the same time, if every clock has the same settings it should be nearly synchronized.
It's not planned to implement any kind of synchronisation.
