### ISSUE TITLE
[BUG] Battery Percentage on switch on and off

### ISSUE THREAD

**Issue by febalci** [Blueforcer/awtrix-light#120]
# Bug report

## Describe the bug

When the battery runs out and ulanzi clock shuts down, it shows the battery percentage as 250% for a single instance. Also, when plug the power in after battery runs out, it shows around 250% battery charge again.

## Additional information

- Devices involved:
  - Model: Ulanzi Awtrix Smart Pixel Clock 2882 (TC001)
  - AWTRIX-LIGHT version: v0.61

## To Reproduce

Wait until battery runs out or plug in after battery runs out.

## Expected behavior

I do not know if this happens only in my case, but is the same since v0.58 (I bought the ulanzi and installed this version first)

## Screenshots
<img src="https://github.com/Blueforcer/awtrix-light/assets/29440671/87edf8db-6cdd-4d1a-82d0-48e453ccc68f" width=50% height=50%>

<img src="https://github.com/Blueforcer/awtrix-light/assets/29440671/751477d0-a141-4b68-9cc6-c5eb2812250f" width=50% height=50%>

**Comment by Blueforcer** [comment]
I will implement a limit.

Beside this, i highly recommend to not use your clock like this. The hardware design is pretty bad and cause a lot of heat. It will live longer if you just leave it plugged in. And only use battery mode if you need it.
