### ISSUE TITLE
up_available no longer working?

### ISSUE THREAD

**Issue by matze20211** [Blueforcer/awtrix-light#121]
# Question

i have two Ulanzi here, with awtrix 0.57, both don't show that a update is available, is i use [PREFIX]/doupdate it updates to 0.60, and again [PREFIX]/doupdate to 0.62, but isn't showing update available. 

## Additional information

- Devices involved:
  - Model: Ulanzi Awtrix Smart Pixel Clock 2882 (TC001)
  - AWTRIX-LIGHT version: 0.57/0.60

**Comment by Blueforcer** [comment]
Automatic update check was removed some versions ago.
I highly recommend to read the changelogs during this early state
