### ISSUE TITLE
Set scroll speed for oversized text including start scroll delay for custom apps

### ISSUE THREAD

**Issue by phoenixswiss** [Blueforcer/awtrix-light#125]
# Question

- Is there a way to set the scroll speed of oversized custom app text? 
- Could we even set a start delay for oversized custom text?

## Additional information

- Devices involved:
  - Model: Ulanzi Awtrix Smart Pixel Clock 2882 (TC001)
  - AWTRIX-LIGHT version: 0.62

## Additional context

The text scrolls too fast and it is sometimes difficult to read the digits of a sensor value.

**Comment by Blueforcer** [comment]
Currently the scroll speed is handled by the given FPS.

You cannot set a delay but you can set a start offset so the text starts scrolling at position 32 or how you like it

**Comment by phoenixswiss** [comment]
Perfect, thank you for the fast reply.

It works as expected.
