### ISSUE TITLE
[FEATURE REQUEST] hide battery app when plugged in and battery 100%

### ISSUE THREAD

**Issue by mark-skel** [Blueforcer/awtrix-light#127]
# Feature Request

### Is your feature request related to a problem? 
No

If so, then add a clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

### Describe the solution / feature you'd like

Option to disable the battery app while the battery level is 100% or plugged in so it's only shown while battery is draining

### Describe alternatives you've considered

Made custom flow in mode red as a custom app.

**Comment by jeeftor** [comment]
I do this in home assistant:

![image](https://github.com/Blueforcer/awtrix-light/assets/6491743/51484b70-307e-4f4f-8520-4fbc3609fff1)

**Comment by bachoo786** [comment]
> I do this in home assistant:
> 
> ![image](https://user-images.githubusercontent.com/6491743/238758662-51484b70-307e-4f4f-8520-4fbc3609fff1.png)

can you please share this as a code rather than a picture? thank.
