### ISSUE TITLE
[BUG] Issue Downloading Icons

### ISSUE THREAD

**Issue by blindguynar** [Blueforcer/awtrix-light#128]
When Running Awtrix-Light on Ulanzi Clock i'm unable to download icons.  The Icons preview fine, but when clicking download i always receive an error no matter the icon choice.  Awtrix Icon's have exact same behavior.  

i can manually upload an icon in the files area under ICONS and is fine.  This icons download just isn't working.

I do not see where logs are stored, but if directed i will provide them.

This is the preview
![Screenshot 2023-05-16 at 10 47 25 AM](https://github.com/Blueforcer/awtrix-light/assets/48634544/93af559b-2d39-43b7-8d83-d12159eab405)

This is the error
![Screenshot 2023-05-16 at 10 47 44 AM](https://github.com/Blueforcer/awtrix-light/assets/48634544/446f89d0-6cec-4c21-b4c3-0753b0d1868a)

**Comment by Blueforcer** [comment]
Logs can be found in the browsers console

**Comment by blindguynar** [comment]
Here is the error in the chrome Console log.  I'm on a macbook pro in case that matters.

![Screenshot 2023-05-16 at 5 09 24 PM](https://github.com/Blueforcer/awtrix-light/assets/48634544/3c12a582-ac17-4710-90f6-ea8ffb89cc08)

**Comment by blindguynar** [comment]
Ok i need to close this issue.  This is something specific to my machine.  I tried it on my other macbook pro and it's fine.  I've got some weird website filtering going on or something with this machine.  Sorry this is NOT a bug with awtrix-light.
