### ISSUE TITLE
[BUG] - Gif rendering oddity 

### ISSUE THREAD

**Issue by jeeftor** [Blueforcer/awtrix-light#133]
# Bug report

## Describe the bug

It appears on some gifs the "coloring" is being "wonky".

## Additional information

- Devices involved:
  - Model: Ulanzi Awtrix Smart Pixel Clock 2882 (TC001)
  - AWTRIX-LIGHT version: [ v0.63]

## To Reproduce

Download icon `2286`

Send packet to notify endpoint:

```json
{
    "text":"2286",
    "icon": "2286"
}
```

## Expected behavior

I expect the icon and what's rendered to look the same

## Screenshots

Take LaMetric icon 2286 for example 

![image](https://developer.lametric.com/content/apps/icon_thumbs/2286_icon_thumb.gif?v=1).

During the rendering of the icon I get a few frames where it doesn't seem to match what I expect to see. You can see there is a "black" area here.
![image](https://github.com/Blueforcer/awtrix-light/assets/6491743/7391ab98-a173-442d-afae-cc0f811f5547)

**Click on this - its an animated GIF and may not auto-load for some reason**
![IMG_9913.gif](https://github.com/Blueforcer/awtrix-light/assets/6491743/c34e7a1d-3efb-4239-9328-a73420d84823)

## Logs

```text
(optional) Add relevant logs which could help tackle the problem.
```

**Comment by Blueforcer** [comment]
Awtrix GIF renderer only supports 8bit gifs at the moment.
Some few lametric icons are 4bit for any reason.
You need to convert it

try this
![sun_cloud](https://github.com/Blueforcer/awtrix-light/assets/31169771/f03ad54b-21c5-4184-81a4-6435bfa3b9e7)
.

**Comment by jeeftor** [comment]
Mind sharing how you converted it? :)

**Comment by Blueforcer** [comment]
See here below
https://blueforcer.github.io/awtrix-light/#/icons

this tool replaces transparent pixels, but also export it in 8 bit
