### ISSUE TITLE
[FEATURE REQUEST]

### ISSUE THREAD

**Issue by jeeftor** [Blueforcer/awtrix-light#134]
# Feature Request

I have been developing various Home Assistant Blueprints and they often need multiple icons. It would be nice if there was a semi-automated way to "bulk-upload" icons. Whether via curl-command or in the UI.

### Is your feature request related to a problem?

I would like to some-how automate the process of downloading icons via blueprints ... 

### Describe the solution / feature you'd like

There a few a few ideas I have:

1) Allow a list of icons to be passed into the downloader

![image](https://github.com/Blueforcer/awtrix-light/assets/6491743/715e8881-349a-4f71-8c75-0b704baccaac)

2) add an API endpoint to download icons

3) publish a `curl` command to allow one to download/upload the icons either to the file browser 

4) This already exists and I shall feel stupid :)

### Describe alternatives you've considered

I've tried to use the web inspector to figure out if I could find a curl command equivalent to the `POST` to the `/edit` endpoint but I came up short

**Comment by Blueforcer** [comment]
Any further questions, or can we close this issue?
