### ISSUE TITLE
[QUESTION] Is it possible to delete file?

### ISSUE THREAD

**Issue by timostr** [Blueforcer/awtrix-light#135]
# Question

I've uploaded file into the wrong directory in the file manager /edit. Is it possible to move or delete that file again?

## Additional information

- Devices involved:
  - Model: Ulanzi Awtrix Smart Pixel Clock 2882 (TC001)

**Comment by Blueforcer** [comment]
Right click on the file like on any other filemanager :)

**Comment by timostr** [comment]
I'm feeling stupid. :-) 👍
