### ISSUE TITLE
[FEATURE REQUEST] Matrix does not power on for MQTT Notification

### ISSUE THREAD

**Issue by jeremywillans** [Blueforcer/awtrix-light#145]
# Feature Request

## Describe the feture

Allow the Matrix to power on when receiving a notification via MQTT.

## Additional information

- Devices involved:
  - Model: Ulanzi Awtrix Smart Pixel Clock 2882 (TC001)
  - AWTRIX-LIGHT version: 0.66

## Ideal Behavior

1. Using MQTT, publish power off command
2. Using MQTT, publish notify command
3. Device will turn on and display notification

**Comment by Blueforcer** [comment]
Isn't it a feature request?

**Comment by jeremywillans** [comment]
Well, the sound plays, but the screen does not turn on.

**Comment by Blueforcer** [comment]
Because you turned the matrix off, not the sound

**Comment by Blueforcer** [comment]
Because you turned the display off, not the sound 😅

**Comment by jeremywillans** [comment]
Fair enough! I have updated this to reflect a feature request - be good to see it wake when receiving a notification. 👍

**Comment by Blueforcer** [comment]
I think it would be better to deactive the sound too. And make the wakeup optional via jsonkey.
