### ISSUE TITLE
[BUG] Wakeup does not update MQTT/HA

### ISSUE THREAD

**Issue by jeremywillans** [Blueforcer/awtrix-light#151]
# Bug report

## Describe the bug

Firstly thanks for the fast turnaround on adding the Wakeup capability!

However MQTT/HA is not updated to reflect this change.

- currentApp topic remains the current App (not Notification)
- Matrix switch in HA does not updated

## Additional information

- Devices involved:
  - Model: Ulanzi Awtrix Smart Pixel Clock 2882 (TC001)
  - AWTRIX-LIGHT version: 0.67

## To Reproduce

1. Power off Matrix
2. Send Notifiction to device

## Expected behavior

1. currentApp topic should update to "Notification"
2. Matrix should switch on

**Comment by Blueforcer** [comment]
Updateing Matrix switch is not possible. because its still off internally

**Comment by jeremywillans** [comment]
Thanks for resolving - now that it powers back off after the notification is dismissed, I agree this isnt relevant 👍

**Comment by jeremywillans** [comment]
@Blueforcer, it looks like the currentApp topic is not restored after the notification is dismissed 😞

**Comment by Blueforcer** [comment]
The App name is only updated when the app is switching.

**Comment by jeremywillans** [comment]
@Blueforcer, thanks for the response, to better clarify, my use case here is being able to understand the current state of the device, especially when the notification has been dismissed.

In a state of matrix off, the currentApp correctly reflects the shown app (prior to turn off) and then when a notification is issued, its updated to Notification (and matrix state is still off as we discussed earlier). However once the notification is dismissed, IMO currentApp should be set back to its previous state, which can also be achieved when either a) turning on the matrix or b) pressing either of the button, even when the matrix is off.

Essentially without this I have no way of knowing if/when the notification has been acknowledged. Happy for other suggestions?

In other news, my Clock has fallen victim to the clock death plague so i am waiting on further correspondence from Ulanzi support.

**Comment by Blueforcer** [comment]
Matrix Off, doesnt mean Awtrix Off.
It just turn the brightness down to zero but awtrix still runs normaly.
You have two ways to to get the acknowledge:
1. Just trigger if current app switches from notification to something else.
2. If current app = notification AND middle button is pressed
