### ISSUE TITLE
[BUG] icon id does not exist

### ISSUE THREAD

**Issue by BenAhrdt** [Blueforcer/awtrix-light#153]
I uploadead one icon yesterday succesfully (lametric id 15124).
If i select now the icon id and klick on preview, the icon will be shown.
if i click download  there will be an error "the id does not exist".
This happens to  EVERY ID

- Devices involved:
  - Model: Ulanzi Awtrix Smart Pixel Clock 2882 (TC001)
  - AWTRIX-LIGHT version: [ eg. v0.66 ]

**Comment by Blueforcer** [comment]
The download is made in your browser. Not by the ESP. please check the Browser console.

**Comment by BenAhrdt** [comment]
@Blueforcer ok. with an other browser it works. the cors blocked. i dont know why.
how many icons canm be safed?

**Comment by Blueforcer** [comment]
Until you're out of space :) you can check it in the filebrowser top right
