### ISSUE TITLE
[QUESTION] Del App

### ISSUE THREAD

**Issue by samke5** [Blueforcer/awtrix-light#155]
Hi, Sorry, but a simple question - how can I delete/disable individual default apps? I want to hide the temperature and battery display. Thanks!

**Comment by Blueforcer** [comment]
In the Menu
https://blueforcer.github.io/awtrix-light/#/onscreen

**Comment by samke5** [comment]
Ohhh sorry - had searched in the mqtt area/suspected it.

Thanks for the quick reply.
Runs great, thanks for the great work!
