### ISSUE TITLE
[QUESTION] How to update the firmware?

### ISSUE THREAD

**Issue by BenAhrdt** [Blueforcer/awtrix-light#159]
I habe the Version 0.66 on my Ulanzy TC001.

Wich File i have to select to update the firmware with the web interface?
![image](https://github.com/Blueforcer/awtrix-light/assets/92173565/912875ec-5b86-47b4-9ad4-4ca9950b4542)

Can i use the Menü?
![image](https://github.com/Blueforcer/awtrix-light/assets/92173565/85a955c1-3bb2-43b1-bb8a-7a30ba8a02eb)

**Comment by SenH** [comment]
You can download `ulanzi_firmware.bin` and upload via web interface: `http://awtrix_XXXXX/update`
