### ISSUE TITLE
[FEATURE REQUEST] Change  DefaultDataPrefix="SHA"  to  DefaultDataPrefix=MQTT_PREFIX 

### ISSUE THREAD

**Issue by robercy** [Blueforcer/awtrix-light#161]
Publish the system data using the MQTT_PREFIX defined on the configuration page, rather than from *DefaultDataPrefix= "SHA". To keep all data together on the same main "Prefix" Topic.

For example, the topics would be:

Prefix/app 
Prefix/bri 
Prefix/btnL
Prefix/temp
....

<img width="289" alt="mqtt" src="https://github.com/Blueforcer/awtrix-light/assets/58106902/6d5118cf-8c81-4bdb-a51c-aaeadc11b561">

**Comment by robercy** [comment]
Guys, You Rocks !!!
Keep the great job.

**Comment by Blueforcer** [comment]
Still a one-man show, but thanks 😁

**Comment by robercy** [comment]
One-man show as good as a Multi-man show.
My reverences to your quality work and dedication.

**Comment by robercy** [comment]
Hi, one problem killed, another born.

The awtrix still publish the status to SHA during boot. 
Maybe the software timing is not correct, like starting MQTT connection before load "Prefix" configuration from config.json file.

Thanks, again.

**Comment by Blueforcer** [comment]
This should be only once during boot, but this is a problem of the library itself it send something during initializing before I can set the prefix.

After that it's sends to the correct prefix

**Comment by robercy** [comment]
It's Ok! 
I allways compile your source code, then I solved this problem, changing "static const char *DefaultDataPrefix" direct on HAMqtt.cpp file.
