### ISSUE TITLE
Bootloop nach eingabe der MQTT Daten

### ISSUE THREAD

**Issue by haahne** [Blueforcer/awtrix-light#163]
Guten Tag,
habe die Uhr erfolgreich geflasht. 

Aber immer wenn ich die daten vom MQTT Broker eingebe und anschließend reboote . Steht auf der Uhr nach der Bootanimation : " CHECK NO UP :( "
Danach erfolgt ein Reboot dies hört erst auf wenn ich die IP Vom Broker lösche.  Broker ist der vom ioBroker. 
Habe auch eine 2. Instanz vom MQTT Adapter installiert und einen anderen Port genommen. Bringt leider auch nichts. 

[logfile.txt](https://github.com/Blueforcer/awtrix-light/files/11645485/logfile.txt)

**Comment by Blueforcer** [comment]
Du musst "eigene states beim verbinden publizieren" im Broker deaktivieren.
Ansonsten sendet iobroker immer an reboot sobald sich awtrix verbindet

**Comment by haahne** [comment]
Habe ich rausgenommen. 
Keine Besserung: 
![image](https://github.com/Blueforcer/awtrix-light/assets/120421080/b14aa0d2-69d8-4eea-9193-7156962e7f50)

**Comment by MFV** [comment]
"States beim Subscribe publizieren" muss ebenfalls deaktiviert werden.

**Comment by haahne** [comment]
Ja das habe ich eben dann noch versucht. :D 
Vielen Dank
