### ISSUE TITLE
[BUG] Month missing following dot

### ISSUE THREAD

**Issue by b-reich** [Blueforcer/awtrix-light#164]
# Bug report

## Describe the bug

Hi just a minor bug.
changing the date to `DD.MM`. It should be have a following dot there.
`04.06` is not a correct date. It should be `04.06.`

## Additional information

- Devices involved:
  - Model: Ulanzi Awtrix Smart Pixel Clock 2882 (TC001)
  - AWTRIX-LIGHT version: v0.67

## To Reproduce

Change Date to `DD.MM`

## Expected behavior

It should be `DD.MM.`

## Screenshots

![C111B62A-E144-4E36-8492-A7D2D83F262E](https://github.com/Blueforcer/awtrix-light/assets/1573025/05b7068f-0d71-4348-9a5f-d30da85f0333)

**Comment by Blueforcer** [comment]
damn youre right. i made a mistake on this commit.
Ive updated the 0.68. please update it manually again.

**Comment by Blueforcer** [comment]
Yes. i didnt updated the version name.

**Comment by Blueforcer** [comment]
Check again in few minutes. Github need some time for publishing

**Comment by b-reich** [comment]
Flashed it over the web interface now. Seems to work :)
Thx
