### ISSUE TITLE
[BUG] unable to send text messages via mqtt

### ISSUE THREAD

**Issue by minoger** [Blueforcer/awtrix-light#168]
# Bug report

## Describe the bug

- unable to send _text_ messages via mqtt, only numbers work
- fail: 
   - mosquitto_pub -h localhost -p 1883 -u FAKEUSER -P FAKEPW -t awtrix_abf540/custom/freitext -m {"text":"hello","icon":"1246"}
- success: 
    - mosquitto_pub -h localhost -p 1883 -u FAKEUSER -P FAKEPW -t awtrix_abf540/custom/freitext -m {"text":"1234","icon":"1246"}

- the same happens by using node-red

## Additional information

- Devices involved:
  - Model: Ulanzi Awtrix Smart Pixel Clock 2882 (TC001)
  - AWTRIX-LIGHT version: [ eg. v0.67 ]

## To Reproduce

- use the commands above

## Expected behavior

- be able to display text

## Logs

- where to find logs?

**Comment by Blueforcer** [comment]
i cannot test it with mosquitto_pub command.
But works like a charm with mqttexplorer, HA and NodeRed.
Please test it again with [MQTT explorer](http://mqtt-explorer.com/)

**Comment by minoger** [comment]
thank you .. you are right .. it is a problem with mosquitto_pub. it doesn't transmit the sign:  --> " <-- unless you add escape sequenzes like -m {\"text\":\"hello\ world\",\"icon\":\"1246\"}. a very strange behavior.

best regards
Michael
