### ISSUE TITLE
[FEATURE REQUEST] - Allow to setup alarms via APIs

### ISSUE THREAD

**Issue by aleesposito85** [Blueforcer/awtrix-light#172]
# Feature Request

Allow to setup alarms via APIs

**Comment by aleesposito85** [comment]
> You can set a timer which plays a custom sound when the configured time has expired.

That is cool, but doesn't have the same functionalities, like: snooze and recurrence. Can also be a bit tedius doing the math :)

**Comment by TheGoblinHero** [comment]
Good idea. I'd like this to be implemented too.

**Comment by burkasaurusrex** [comment]
+1

**Comment by Blueforcer** [comment]
timer and alarms will probably be removed in the next versions. Everyone currently has their own idea and function wishes that can all be created via the smarthome.
On the one hand this follows the basic idea that awtrix is a smarthome companion, on the other hand it is so much more flexible.
Even snooze can be implemented with it.

**Comment by burkasaurusrex** [comment]
Yea, makes sense. The only pushback would be for reliability. For something like an alarm, it would be great to have as few points of failure as possible. So some API functionality to schedule the next alarm so the alarm goes off even without WiFi, smarthome, power, etc would be great in my mind. But I understand it’s generally redundant when connected to a smarthome.

**Comment by Blueforcer** [comment]
But tying the functions to reliability, when awtrix lives only from the smart home and its connection anyway, is not a decisive argument in my opinion. if you have a power failure, or connection loss, then you can no longer set the alarm via API.

**Comment by Blueforcer** [comment]
closing since timer will be removed in the next version
