### ISSUE TITLE
[BUG] Playing sound is not ok

### ISSUE THREAD

**Issue by mcuiobroker** [Blueforcer/awtrix-light#174]
# Bug report

## Describe the bug
I tried to play a RTTTL sound, but it is more one tone as a melodie. It seems to be one tone and in the background with little volume a melodie?
![image](https://github.com/Blueforcer/awtrix-light/assets/84818934/e197d63c-bf53-42c6-a3ab-ec13a1c8d5e2)
Sample is from 
https://www.laub-home.de/wiki/RTTTL_Songs 

Add a description of the bug. Detail the expected behaviour in contrast with the behaviour you're observing.

## Additional information

- Devices involved:
  - Model: Ulanzi Awtrix Smart Pixel Clock 2882 (TC001)
  - AWTRIX-LIGHT version: [0.68 ]

## To Reproduce

MQTT -Entry 
![image](https://github.com/Blueforcer/awtrix-light/assets/84818934/932d0a2b-3822-4e16-84fa-de2313c0f7cb)
![image](https://github.com/Blueforcer/awtrix-light/assets/84818934/d89679c2-6637-4bf9-a839-852e2eb3f14e)

## Expected behavior

If I let it play with https://adamonsoon.github.io/rtttl-play/ on a PC its sounds normal like a melodie.

## Logs

```text
(optional) Add relevant logs which could help tackle the problem.
```

**Comment by Blueforcer** [comment]
It's not a software bug. The build in buzzer is crap. You can replace it with a better one, but nothing to do here from software side

**Comment by mcuiobroker** [comment]
How can I update the buzzer?

**Comment by mcuiobroker** [comment]
Is the anywhere a description how to open it?

**Comment by Blueforcer** [comment]
On my discord server:

https://discord.com/channels/546407049148366859/1101071217986900049

And

https://discord.com/channels/546407049148366859/1100377495146082314

**Comment by mcuiobroker** [comment]
Jetzt habe ich die Anleitung. Danke.
