### ISSUE TITLE
Local NTP

### ISSUE THREAD

**Issue by sulsa** [Blueforcer/awtrix-light#176]
Great project! 

I have a local NTP server using pfSense so I put my Awtrix on a vlan with no internet. However when changing the NTP server on the Awtrix, I am unable to retrieve the time. When I move it to a vlan with internet, it is able to obtain time even though I don't change the NTP server from my local NTP server. Please advise.

**Comment by Blueforcer** [comment]
Did you restart your awtrix after set the new NTP server?
Currently im unable to test your scenario

**Comment by udo1toni** [comment]
did you set ntp  server with ip? works like a charm here (OpnSense)

**Comment by DcFamas** [comment]
With my fritz.box this works like a charme. Also no internet connection, ntp via. DNS-name.
