### ISSUE TITLE
[BUG] Apps state after restart always true

### ISSUE THREAD

**Issue by BenAhrdt** [Blueforcer/awtrix-light#178]
if i deactivetd some native app like "bat" and i restart the tc001 the app will be displayed.
is it possible to store the activation state?

**Comment by Blueforcer** [comment]
It is stored.
How you deactivate it?

**Comment by marlan99** [comment]
i recognized the same issue but when i start the tc001 when the battery was empty and i plugged in the cable again.
maybe a similar behaviour ?

**Comment by marlan99** [comment]
maybe its only the activation state of the app time which will not be stored?

**Comment by Blueforcer** [comment]
If someone would answering my question, there would be no need for guessing 😉

**Comment by BenAhrdt** [comment]
I do it with the ioBroke Adapter.
I think the Adapter did it with
/api/apps/ with the paylod {name: appname, shown: false}
Or something… it works, until you restart the tc001

**Comment by klein0r** [comment]
> If you still want to use the app API you need to send it after each reboot. It's only temporary

Thanks - I will remove that feature (since it's deprecated)

**Comment by Blueforcer** [comment]
> > If you still want to use the app API you need to send it after each reboot. It's only temporary
> 
> Thanks - I will remove that feature (since it's deprecated)

If possible just uncomment it. In the future I try to add it again in a slightly different way. Because the current state cause more questions than it helps
