### ISSUE TITLE
D1 Mini (China) nicht kompatibel?[QUESTION]

### ISSUE THREAD

**Issue by Elektroniker0486** [Blueforcer/awtrix-light#181]
Ist die D1 Mini aus China mit der Awtrix2_uprgrade.bin nicht kompatibel. Im onlineflasher kommt die Meldung, das die Hardware nicht kompatibel sei. Wenn ich mit dem ESP Homeflasher die awtrix2_upgrade.bin flashe dann gibt es kein Lebenszeichen.
Dieser D1 hat mit der alten Awtrix Version einwandfrei funktioniert.

Wird das noch gefixt?

Vielen Dank im voraus!

Add here your question.

## Additional information

- Devices involved:
  - awtrix2_upgrade.bin
  

## Logs

```text
(optional) Add relevant logs which could help tackle the problem.
```

**Comment by Blueforcer** [comment]
ESP8266 ist nicht kompatibel
Wenn du die alte Hardware hast, kannst du den ESP8266 D1 Mini 1:1 gegen den  ESP32 D1 Mini austauschen.

**Comment by Elektroniker0486** [comment]
Ja, ich habe die alte Hardware mit deiner Awtrix Platine. Super, vielen Dank für die Info.
