### ISSUE TITLE
[QUESTION]Komma wird eine Zeile zu hoch gesetzt? Soll das so?

### ISSUE THREAD

**Issue by mcuiobroker** [Blueforcer/awtrix-light#184]
# Question

Soll das Komma so dargestellt werden? Geht es nicht anders?

## Additional information

- Devices involved:
  - Model: Ulanzi Awtrix Smart Pixel Clock 2882 (TC001)
  - AWTRIX-LIGHT version: [0.68 ]

## Logs

```text
(optional) Add relevant logs which could help tackle the problem.
```

## Additional context

![image](https://github.com/Blueforcer/awtrix-light/assets/84818934/67bac9a4-af22-4f3e-961f-fea4d63b0e57)

**Comment by Blueforcer** [comment]
Du warst doch grad noch im discord aktiv 😅

Die Schriftart wurde absichtlich so gemacht.

**Comment by mcuiobroker** [comment]
Sorry, switche hin und herr. War gerade auf github

**Comment by mcuiobroker** [comment]
Kann man da grundsätzlich eine andere Schriftart einstellen?

**Comment by Blueforcer** [comment]
Nein das geht nicht. Die Schriftart wurde speziell für Awtrix entwickelt.

**Comment by mcuiobroker** [comment]
Ok. Danke.
