### ISSUE TITLE
delete or set disable installed apps 

### ISSUE THREAD

**Issue by arteck** [Blueforcer/awtrix-light#186]
please make some apps (eyes, date, clock, batt) switchable off direct after reboot

**Comment by Blueforcer** [comment]
Go into your onscreen menu -> Apps and choose what apps you want, or don't want.

**Comment by RK62** [comment]
How can I permanently disable the installed apps on a flashed Awtrix2? 
Currently I always send a mqtt.0.*.apps a 
`[{name: "time", show: true}, {name: "hum", show: false}, {name: "temp", show: false }] `
but the setting is lost after a reboot.

**Comment by Blueforcer** [comment]
This API is not documented for a good reason 😅

Use this
https://blueforcer.github.io/awtrix-light/#/onscreen

**Comment by RK62** [comment]
How to use onscreen when my awtrix2 has no buttons?

**Comment by Blueforcer** [comment]
If you're limited in hardware, you're currently limited in software Features.
For now use the /app API and send it once as retained message. Zlthen it will be applied on each start automatically

**Comment by pacmac** [comment]
I can't get this to work at all, I have published to the mqtt to `awtrix_1234xxx/apps` but the display just continues to show all of the built in apps, what am I doing wrong ??

```
awtrix_1234xxx/apps

[
{"name":"date","pos":0,"show":false},
{"name":"temp","pos":2,"show":false},
{"name":"hum","show":false,"pos":0},
{"name":"bat","show":false}
]
```
