### ISSUE TITLE
[Feature Request] Add Device configuration URL for HA

### ISSUE THREAD

**Issue by tioan** [Blueforcer/awtrix-light#19]
Please add Support for [Device configuration URL](https://developers.home-assistant.io/blog/2021/10/26/config-entity/#device-configuration-url) 
to Change the MQTT Info button into an Link to Webinterface of the device

current:

![SCR-20230326-tfqt](https://user-images.githubusercontent.com/259990/227802557-e672e98a-a2f9-48a1-84ee-5f597daae0cf.png)

desired:

![SCR-20230326-tfsv](https://user-images.githubusercontent.com/259990/227802486-d0edc881-9c64-461d-bb79-312c21356350.png)

**Comment by Blueforcer** [comment]
This is currently not possible with the used library.
https://dawidchyrzynski.github.io/arduino-home-assistant/documents/library/device-configuration.html#device-configuration

 i will try to exend  this lib by myself in a future update.

**Comment by Blueforcer** [comment]
I will close this issue, until the lib gets an update. Feel free to open it again if its possible
