### ISSUE TITLE
Bootloop after reboot[BUG]

### ISSUE THREAD

**Issue by Dragon0501** [Blueforcer/awtrix-light#190]
First time boot after Flashing works fine. If the ESP is rebootet, doesn't matter if done by button of the firmware or by pressing the two hardware buttons causes an bootloop. It starts up says "check" and after this it reboots and says "check" again

## Additional information

- Devices involved:
  - Model: Ulanzi Awtrix Smart Pixel Clock 2882 (TC001)
  - AWTRIX-LIGHT version: v0.69

**Comment by Blueforcer** [comment]
If youre using iobroker:
duplicate of https://github.com/Blueforcer/awtrix-light/issues/165

**Comment by Dragon0501** [comment]
Thank you very much! Problem solved.
