### ISSUE TITLE
[FEATURE REQUEST] MQTT-Server IP und Port in die /api/stats aufnehmen

### ISSUE THREAD

**Issue by mcuiobroker** [Blueforcer/awtrix-light#198]
Um zu erkennen, dass jemand MQTT-Server definiert hat, bitte die Werte für MQTT-Server und Port in die Stats aufnehmen. Steht der MQTT-Server nicht zur Verfügung dauert es einige Zeit (ca. 1 Minute) bis das Gerät (TC001) etwas anzeigt.

**Comment by Blueforcer** [comment]
Sehe den sinn leider nicht darin, 2 Strings alle 10s zu versenden, mit daten die sich nie ändern und man selbst zuvor eingebeben hat. Der Großteil der User nutzt zudem kein html wenn sie bereits mqtt nutzen.

**Comment by mcuiobroker** [comment]
Nimm es doch bitte in die Settings, dort wird ja nicht alle 10 Sekunden aktualisiert, oder?
