### ISSUE TITLE
[Feature Request] Extend Entity categories with diagnostic

### ISSUE THREAD

**Issue by tioan** [Blueforcer/awtrix-light#20]
Extend existing [Entity categories](https://developers.home-assistant.io/blog/2021/10/26/config-entity?_highlight=diagnostic#entity-categories)with diagnostic and add the following buttons into the category
* Battery (form Sensors)
* Restart
* Update or "Check for Update and apply"

Probebly some internal Information like
- Uptime
- Free Mem
- WiFi Signal

**Comment by Blueforcer** [comment]
diagnostics are not part of the used libary

**Comment by poblabs** [comment]
+1 for Restart button

**Comment by Blueforcer** [comment]
Personally i don't see any sense to restart the clock from HA, there is no need for that.
Every additional HA entity consumes a lot of RAM because awtrix needs to hold several jsons for it. So it must be chosen wisely.

**Comment by Blueforcer** [comment]
I will close this issue, until the lib gets an update. Feel free to open it again if its possible
