### ISSUE TITLE
clock goes into reboot loop when using MQTT (iobroker)

### ISSUE THREAD

**Issue by Totte23** [Blueforcer/awtrix-light#200]
For some reason my Ulanzi clock goes into reboot loop as soon as I connect with MQTT adapter at iobroker.
Firmware 0.7
I already tried to modify the reboot setting by publishing false state but no effect.
When I use this adapter instead (so no MQTT adapter of iobroker) then there is no issue:
https://github.com/klein0r/ioBroker.awtrix-light

Any idea how I could solve this?

**Comment by Blueforcer** [comment]
dublicate of https://github.com/Blueforcer/awtrix-light/issues/165
