### ISSUE TITLE
[BUG] Set brightness via menu, save, brightness menu shows wrong % 

### ISSUE THREAD

**Issue by nxxxse** [Blueforcer/awtrix-light#206]
# Bug report

## Describe the bug

The brightness is stored internally as 1/255 to model what that hardware is capable of (PWM). However, the menu shows brightness in %. The [map](https://reference.arduino.cc/reference/en/language/functions/math/map/) function is used to convert from % to 1/255 and when opening the menu from 1/255 to %. `map` does not round. There seems to be an issue with converting from 1/255 back to %.

## Additional information

- Devices involved:
  - Model: Ulanzi Awtrix Smart Pixel Clock 2882 (TC001)
  - AWTRIX-LIGHT version: 0.70

## To Reproduce

* Set brightness via [Onscreen menu](https://blueforcer.github.io/awtrix-light/#/onscreen?id=onscreen-menu) to 95 %. Close.
* Open brightness setting via Onscreen menu again.

## Expected behavior

Shows 95 % as it was saved.

## Actual behavior

Shows 94 %.

## Additional context

I tried to fix it but I have no good idea how to do that.

**Comment by Blueforcer** [comment]
since map is used in both direction its not that accurate and loses precision. Percentage is not used internally
