### ISSUE TITLE
[BUG] clock back to 01.01.1070

### ISSUE THREAD

**Issue by BenAhrdt** [Blueforcer/awtrix-light#209]
Meine Uhr war heute morgen aus (hängt am USB) und nach dem Einschalten wieder auf dem Datum 01.0.1970
The IP is displayed, but no web server can be reached.
Also no access point is visible in the WLAN

V0.70

**Comment by Blueforcer** [comment]
Dann konnte sich die Uhr nicht mit dem NTP server verbinden um die Uhrzeit zu holen.
Entweder falsche Server eingetragen, kein Internet oder der NTP Server zur Zeit nicht erreichbar

**Comment by BenAhrdt** [comment]
ABer die Uhr funktionierte schon 4 Wochen

**Comment by Blueforcer** [comment]
Dann ist es auch unwahrscheinlich daß sich die Software in der Zeit ändert.

Wie gesagt, die in meinem letzten Kommentar angesprochenen Punkte liegen am nächsten.

**Comment by BenAhrdt** [comment]
Wie kann ich jetzt wieder an die Uhr kommen? Sie zeigt die IP An, aber ich komme nicht drauf.

**Comment by Blueforcer** [comment]
Welche IP zeigt sie denn an?

**Comment by BenAhrdt** [comment]
192.168.2.41    --- DIe habe ich auch kofiguriert und war auch aktuell.
Bei update erscheint ein error und in der Fritzbox wird das Gerät nicht angezeigt.
Also es scheint sich nicht mit dem WLAN zu verbinden, obwohl eine IP angezeigt wird.
Bis gestern abend war die Uhr normal im WLAN.
Nun kann ich sie nicht mehr erreichen

**Comment by Blueforcer** [comment]
wenn du die IP manuell als statisch Konfiguriert hast, dann wird die natürlich angezeigt. Wenn du da einen Fehler gemacht hast, wirst du nicht mehr drauf kommen. Hilft nur noch neu flashen.

**Comment by BenAhrdt** [comment]
die IP stimmt ja. wie gesagt lief es ja 4 wochen bis heute morgen.

**Comment by Blueforcer** [comment]
Hast du ne statische IP im Webinterface angegeben?
Wenn ja dann bitte zurücksetzen und mit ner dynamischen probieren.

**Comment by BenAhrdt** [comment]
Funktioniert wieder.
Neu gelasht, aber scheinbar war das WLAN abgeschmiert. Da das Gerät als einziges im WLAN hing, viel es nicht auf.
Könnte man noch ein not Connected als Hinweis geben?
