### ISSUE TITLE
[BUG] draw with "db" and 8x32 picture creates "ErrorParsingJson"

### ISSUE THREAD

**Issue by RK62** [Blueforcer/awtrix-light#214]
# Bug report

## Describe the bug
I can transfer an 8x8 graphic without problems, with 8x32 I get an error message "ErrorParsingJson".
Is it possible to transfer only smaller BMP's with "db"?

## Additional information

- Devices involved:
  - Model: Ulanzi Awtrix Smart Pixel Clock 2882 (TC001)
  - AWTRIX-LIGHT version: [ eg. v0.70 ]

### This works fine
```
{  
    text: "Klein", 
    draw: [  
        {"db": [ 0,0,8,8,
            [   63504,63504,63504,63504,63504,63504,63504,63504,
                63504,0,0,0,0,0,0,63504,
                63504,0,0,0,0,0,0,63504,
                63504,0,0,0,0,0,0,63504,
                63504,0,0,0,0,0,0,63504,
                63504,0,0,0,0,0,0,63504,
                63504,0,0,0,0,0,0,63504,
                63504,63504,63504,63504,63504,63504,63504,63504                     
                ] ] }
    ]
}

```
###This creates an error "ErrorParsingJson"
7 lines will be ok, when using the 8th line the error raises:

```
{  
    text: "Gross", 
    draw: [  
        {"db": [ 0,0,32,8,
            [ 64512,64512,64512,64512,64512,64512,64512,64512,64512,64512,64512,64512,64512,64512,64512,64512,64512,64512,64512,64512,64512,64512,64512,64512,64512,64512,64512,64512,64512,64512,64512,64512,
                64512,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,64512,
                64512,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,64512,
                64512,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,64512,
                64512,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,64512,
                64512,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,64512,
                64512,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,64512,
64512,64512,64512,64512,64512,64512,64512,64512,64512,64512,64512,64512,64512,64512,64512,64512,64512,64512,64512,64512,64512,64512,64512,64512,64512,64512,64512,64512,64512,64512,64512,64512
                ] ] }
    ]
}
```

## Expected behavior

It should displayalso 8x32 graphics

**Comment by Blueforcer** [comment]
the json is too big. i will try to increase the memeorypool

**Comment by Blueforcer** [comment]
@RK62 Please check it with v0.71

**Comment by RK62** [comment]
No changes, same error with v0.72 😥

**Comment by Blueforcer** [comment]
i need to remove this again, this causes huge RAM consumption to allocate the json pool.
unfortunally this affects also other users, so they unable to use higher ammount of  customapps anymore.
I recoomend to create a 32x8 gif and use that instead.
im Sorry but the ESP is limited in resources and I therefore have to weigh things up a lot.

**Comment by RK62** [comment]
The GIF workaround does not help me with my application because I generate finished images from ioBroker.

Is it possible to implement one of the following alternatives?
- Sending the graphic in several parts?
- Additive use of db-commands in seperate JSON's, i.e. without deleting the already created display?
- Cool feature: API call for creating GIF images from the transmission of the 8x32 graphic?

**Comment by Blueforcer** [comment]
All 3 points are unfortunately not possible
Maybe you can draw it with other commands.. the bitmap above can be also created with one drawrect command.

**Comment by RK62** [comment]
OK, so I have to search for a other solution.
Do you know a way to convert my Matrix-Arrays with content like mqtt.0.AL-0.screen to gif-format?
