### ISSUE TITLE
[FEATURE REQUEST] Allow configuring a custom Home Assistant MQTT Discovery prefix

### ISSUE THREAD

**Issue by CWSpear** [Blueforcer/awtrix-light#215]
# Feature Request

### Is your feature request related to a problem?

The Home Assistant MQTT Discovery is configurable in Home Assistant. awtrix hardcodes it to `homeassistant`

### Describe the solution / feature you'd like

Please allow the Home Assistant MQTT Discovery to be configurable if HA MQTT Discovery is enabled.

### Describe alternatives you've considered

I've considered changing my discovery prefix, but that would require changing a lot of other things, I don't even know all what I've got set up using it, but more than a few. I also can't be the only one use has this issue.

**Comment by Blueforcer** [comment]
You're indeed the first one with this request, because it's the standard prefix

**Comment by CWSpear** [comment]
Thanks!
