### ISSUE TITLE
[BUG] Apps not autowitch to next App

### ISSUE THREAD

**Issue by bicmac** [Blueforcer/awtrix-light#216]
I have 2 custom Apps setups over IOBroker AWTRIX-Light Adapter in my TC001.
I have hidden all internal apps accept data and time.
auto Switch for apps is enabled and works if i dont have setupd Cusom apps. As soon as i add a custum app he will ignore the autoswitch and walk through the cycle exactly once. That he will stopp and not start from beginning.
As the IOBroker Adapter use the official API i think it is maybe a bug in AWTRIX-Light FW. But i have no clue how to debug that.
Actual FW is installed on the Device. Is there any way to downgrade to a older Version as i think it was working allready once.

**Comment by bicmac** [comment]
Hier ein paar mehr Infos aus dem IPBroker AWTRIX Light Ticket:
https://github.com/klein0r/ioBroker.awtrix-light/issues/39

Es scheint so das es einen Fehle rgibt sobald man Textscrolling disabled in Custoum Apps und der Text länger ist.
Zitat: "Es muss an dem Text Scrolling liegen. Ich habe das gleiche Problem.
Solange der Text nicht zu lang ist, funktioniert die automatische App Rotation. Sobald der Text aber zu lang ist, der Haken "noScroll" gesetzt ist, verharrt das Display bei der App. Erst wenn der Text wieder aufs Display passt geht's weiter."

@Blueforcer kannst Du das bei Dir nachstellen oder hast Du ne Idee warum die Apps nicht mehr weiterlaufen sondern einfach stehen bleiben.

**Comment by bicmac** [comment]
Hier vorsichtshalber nochmal der komplette Logoutput für den Request aus dem IOBroker:

`2023-07-19 21:51:23.691  - debug: awtrix-light.0 (12107) sending "POST" request to "/api/custom?name=aussen" with data: {"background":"#000000","text":"21,8 °C","textCase":2,"repeat":1,"color":"#FFFFFF","noScroll":true,"icon":"40921"}
2023-07-19 21:51:23.808  - debug: awtrix-light.0 (12107) received 200 response from "/api/custom?name=aussen" with content: "OK"`

**Comment by Blueforcer** [comment]
wie ich mir dachte:

Sobald du "repeat" nutzt, wird die App nicht mehr nach einer Zeit beendet sondern dann wenn der Text X mal durchgescrollt ist.
Mit noScroll verhindert du es aber und es wird nie eintreten.

Ich könnte das evtl noch abfangen das bei noScroll wieder auf Zeit geschaut wird und nicht auf repeat.

Bis dahin kannst du repeat entfernen oder auf 0 setzen

**Comment by bicmac** [comment]
danke. Muss dazu warten bis Matthias seinen IOBroker Adapter anpasst. Denn momentan kann ich 0 nicht setzen für das Repeat über den Adapter. Ich hab ihm aber schon geschrieben ob er es anpassen kann.
Ggf findest Du ja auch Zeit es relativ zeitnah bei Dir irgendwie abzufangen.

**Comment by Blueforcer** [comment]
Dann ist das aber generell falsch.
Repeat ist optional in awteix und sollte nicht Standardmäßig auf 1 sei.

In awteix ist es Standard 0 wenn's nicht angegeben wird

**Comment by Blueforcer** [comment]
Sorry fehler von mir. Grad nochmal geschaut, -1 ist standard. Denn bei 0 ist er fertig mit scrollen

**Comment by klein0r** [comment]
Also liegt es an `repeat: 1` dass nicht zur nächsten App gewechselt wird? Oder verstehe ich `noScroll` falsch?

**Comment by Blueforcer** [comment]
Ja. `noScroll` verhindert das `repeat` runterzählt. Wenn repeat angegeben ist, wird diese variable um bei jedem kompletten durchscrollen um eins verringert. Wenn 0 dann ist die App fertig.
ist `repeat `= -1 (wenns z.b nicht in der json angegeben wird) dann wird `repeat ` nicht beachtet sondern die `duration `bzw globale apptime.
In der obrigen Konstellation war es nun aber so das Awtrix gewartet hat bis `repeat `<1 ist, was aber nie passiert ist weil das scrollen mit `noScroll` verhindert wurde

**Comment by klein0r** [comment]
Perfekt, danke für die Erklärung
