### ISSUE TITLE
[FEATURE REQUEST] Countdown Timer as App

### ISSUE THREAD

**Issue by bicmac** [Blueforcer/awtrix-light#217]
Would be nice to have a way to setup a Countdown (maybe more then one) over the API.
The Display should then just count down like a egg timer with Hours:Minutes:Seconds
After reaching the end he should maybe play a Song (can setuped using API) and a TEXT (also setuped using API)

**Comment by Blueforcer** [comment]
would be easier to do it by your own from your smartphone system. Here you have all the flexibility.

**Comment by samturner3** [comment]
So need to push to mqtt every second for a seconds display?

**Comment by Blueforcer** [comment]
if you want it that way, yes. 1s is absolutly no problem for awtrix, im running apps wich gets updates every 100ms
