### ISSUE TITLE
[BUG] [NEW BEHAVIOUR] Notifications are handled sequential

### ISSUE THREAD

**Issue by Dinges28** [Blueforcer/awtrix-light#225]
# Bug report

## Describe the bug

In firmware 0.6 I used the notify function for several things. One of them was showing the DIM percentage of a light.
It would show the light brightness percentage "realtime" while dimming. and after releasing any button it will hold the percentage for 5 seconds
When dimming It would overwrite the previous notification despite of the "duration" timer still active or not.

In firmware 0.7 notifications are handled sequential, it will process the new notification AFTER the duration timer is finished. I would like the notification again to process the new input, despite the fact that the timer is still active.

## Additional information

- Devices involved:
  - Model: Ulanzi Awtrix Smart Pixel Clock 2882 (TC001)
  - AWTRIX-LIGHT version: 0.7

## To Reproduce
```
topic: ulanzi_computerkamer/notify
              payload: "{\"duration\": 5,\"text\": \"Computer\",\"progress\": \"{{(state_attr('light.computerkamer_groep','brightness') / 2.55 )| round(0) }}\"}"   
```

**Comment by Blueforcer** [comment]
Its really important to read the changelogs and the documentation _before_ creating a "bug" report.
Use the stack key to control this behavior
