### ISSUE TITLE
When using TextOffset icon is pushed by the offset [BUG]

### ISSUE THREAD

**Issue by hkdrj** [Blueforcer/awtrix-light#231]
# Bug report

## Describe the bug

When using TextOffset and PushIcon=1, the icon it´s pushed by the offset. 

## Additional information

- Devices involved:
  - Model: Ulanzi Awtrix Smart Pixel Clock 2882 (TC001)
  - AWTRIX-LIGHT version: 0.70/0.71 Beta

## To Reproduce

msg.payload={
      "text": "0123456789 0123456789",
      "textOffset": 33,
      "icon": 52648,
      "pushIcon": 1
    }    

## Expected behavior

That the icon it´s pushed just when the text it´s at one pixel distance from the icon. That´s how it worked until version 0.67

**Comment by Blueforcer** [comment]
note for me:
It only fials in customapp, not in notifications
