### ISSUE TITLE
Add version number to release files

### ISSUE THREAD

**Issue by wilfredktlr** [Blueforcer/awtrix-light#235]
# Feature Request

The firmware file on the [releases page](https://github.com/Blueforcer/awtrix-light/releases) does not have the version number in the filename. This makes it dificult to see if you've downloaded the correct file to upload to the device.

### Describe the solution / feature you'd like

Add the version variable to the filename.

https://github.com/Blueforcer/awtrix-light/blob/ff510653e9bd740cc0cbea08715e69cebbe3fdb5/.github/workflows/main.yml#L107
```
asset_name: ulanzi_firmware_${{ steps.version_number.outputs.firmware_version }}.bin
```

https://github.com/Blueforcer/awtrix-light/blob/ff510653e9bd740cc0cbea08715e69cebbe3fdb5/.github/workflows/main.yml#L118
```
asset_name: awtrix2_upgrade_firmware_${{ steps.version_number.outputs.firmware_version }}.bin
```

### Describe alternatives you've considered

N/A

### Additional context

N/A

**Comment by Blueforcer** [comment]
isnt the latest youve downloaded, the latest release ? ;-)
I can do this in the future, but also remember you can use the webflasher or start the auto update right from your awtrix onscreen menu or API without downloading the bin file manually
