### ISSUE TITLE
Interface not working using reverse proxy (HTTPS and/or subdirectory)

### ISSUE THREAD

**Issue by wilfredktlr** [Blueforcer/awtrix-light#236]
# Bug report

## Describe the bug

I use a reverse proxy (HAProxy) to access the webinterface. When Awtrix want's to load a resource (eg. `http://${window.location.hostname}/[filename]`) it fails because the browser cannot access it when the webinterface is accessed using HTTPS or a subdirectory. This causes the webinterface to not work correctly (eg. the menu).

## Additional information

- Devices involved:
  - Model: Ulanzi Awtrix Smart Pixel Clock 2882 (TC001)
  - AWTRIX-LIGHT version: v0.71

## To Reproduce

- Setup a reverse proxy to access the site using HTTPS and/or a subdirectory.

## Expected behavior

No JavaScript errors and a working menu.

## Screenshots

An example of a fixed protocol and path.

![image](https://github.com/Blueforcer/awtrix-light/assets/1142879/b5d5c9e8-5e1d-40cd-95ae-8bb667c3feee)

The JavaScript error and non-working menu.

![image](https://github.com/Blueforcer/awtrix-light/assets/1142879/d63c58a4-291f-48a1-b1d0-4ae35b451480)

## Logs

N/A

## Additional context

A possible solution would be to make the URL relative (eg. `var e=new URL('./config.json');`).

**Comment by Blueforcer** [comment]
This "bug" should belong to the webinterface library. 
https://github.com/cotestatnt/esp-fs-webserver

My knowlege for that is limited. Feel free to open a PR

**Comment by wilfredktlr** [comment]
Thanks. I didn't realize that this was an external library. I've opened an issue over there.

https://github.com/cotestatnt/esp-fs-webserver/issues/29

**Comment by wilfredktlr** [comment]
The author of the esp-fs-webserver just fixed the issue should be fixed in version [1.2.3](https://github.com/cotestatnt/esp-fs-webserver/releases/tag/1.2.3).

https://github.com/cotestatnt/esp-fs-webserver/issues/29#issuecomment-1674354045
