### ISSUE TITLE
Cannot flash Ulanzi TC001

### ISSUE THREAD

**Issue by stalakerob** [Blueforcer/awtrix-light#238]
# Bug report

## Describe the bug

I tried flashing a Ulanzi TC001 that I just received today from China. The clock's integrated firmware works. Trying to flash awtrix light always produces a initialization error. I've tried multiple USB ports and cables on a notebook and a Windows PC. The flasher can connect but always throws this error. It suggest to to press the BOOT button while hitting initialize but WTH is the boot button?
 
## Additional information

- Devices involved:
  - Model: Ulanzi Awtrix Smart Pixel Clock 2882 (TC001)
  - AWTRIX-LIGHT version: 0.71
## Screenshots

![image](https://github.com/Blueforcer/awtrix-light/assets/44496615/f41b2d5e-b899-492e-882b-383235337ef5)

## Logs

```text
(optional) Add relevant logs which could help tackle the problem.
```

**Comment by stalakerob** [comment]
I did replug and turning on/off many times. No luck so far. One thing I realized is that sometimes there is a short beep and the clock continues to run and sometimes there is a very long beep and the clock stops to run and a reset is required to make it run again. In both cases the initialization error shows up.

**Comment by stalakerob** [comment]
This behavior seems to depend on port/cable being used but I'm not shure.

**Comment by Blueforcer** [comment]
While flashing a continuous beep is normal. Maybe you turn the clock off too early?

**Comment by stalakerob** [comment]
No, I always wait until the error shows. Is there a dependency on the stock firmware version installed and/or the battery load level?  My battery seems to be at 75%. Firmware version I don't know.

**Comment by stalakerob** [comment]
Could it be an issue with the USB port? Charging works but maybe some other pins have issues? Did you see something like this happen before?

**Comment by Blueforcer** [comment]
1-2 Users reported the same. 
Either they used another PC this mostly works. Or they flashed it manually.

**Comment by stalakerob** [comment]
I tried yet another PC. Same issue. They are all Windows 11 PCs though. How do I flash this device manually?

**Comment by stalakerob** [comment]
Can I download the .bin file somewhere and try flashing it with a different tool?

**Comment by Blueforcer** [comment]
Sure, you will find it in the release tab of this repo. 
Or here:
https://github.com/Blueforcer/awtrix-light/tree/main/docs%2Fulanzi_flasher%2Ffirmware

Make sure you're flashing every partition. Not only the firmware.bin
You can see the partition offset in the manifest.json


You can also try to flash the firmware.bin over the ulanzi Webinterface and then try to use the online flasher again to get the partitions right. 

If you don't flash the partitions you will have limited space of flash memory for icons etc

**Comment by rockthenet** [comment]
I had the exact Issue. The manual flashing workaround fortunately worked for **one** of the two Pixel Clock's. 

Today i tried the **second** again with another Windows PC and at first it seems to work just fine. But then it "crashed" during the chrome firmware update with the message "**lost connection**". Despite I was patient and didn't touch anything during update process. Unfortunately, a retry didn't work. The Clock makes a **continuous beep** from now on when Ii switch it on. 
The display is off. And there is not any Wifi connection or AP available. 

My computer is recognizing a device when I plug it at the computer but i don't know hot to recover. 
Is there any more reliable windows Tool to flash this or even the original firmware?

**Comment by rockthenet** [comment]
Update: 
I managed to flash the original firmware again with this tool:
![image](https://github.com/Blueforcer/awtrix-light/assets/43685417/1a0e7ad9-d5e8-4293-ad2d-b4c557e6f742)
https://github.com/esphome/esphome-flasher/releases
... @Blueforcer Do you think that it also works with your firmware?

**Comment by stalakerob** [comment]
@Blueforcer So I installed firmware.bin using the ulanzi web interface. It works. But I still cannot flash awtrix using the online flasher. I can connect to my mqtt broker as well. You said I have limited space for icons etc. How much do I lose if I cannot flash the remaining files? Thx. Robert

**Comment by Blueforcer** [comment]
Around 2/3 I think. You can check this in the file manager too right. Normally you have 256kb free.

**Comment by stalakerob** [comment]
I have 152 kb free of 192kb total. I can live with this I think. Many thanks for your quick support.  Appreciated.
Cheers from Bavaria.

**Comment by Blueforcer** [comment]
Grüße aus Hessen;)

**Comment by thewan056** [comment]
> Update: I managed to flash the original firmware successfully with this tool: ![image](https://user-images.githubusercontent.com/43685417/256634111-1a0e7ad9-d5e8-4293-ad2d-b4c557e6f742.png) https://github.com/esphome/esphome-flasher/releases ... @Blueforcer Do you think that it also works with your firmware?

Hi, can you tell me where did you get the original firmware from? I would like to change back to the original firmware if possible.
