### ISSUE TITLE
Shuffle function for effects

### ISSUE THREAD

**Issue by schraubstock85** [Blueforcer/awtrix-light#244]
My kids like the new effects of Version 7.1 it would be great to shuffle them randomly. Than it is always be a surprise what is next in a custom app called effects.

**Comment by robercy** [comment]
If you use homeassistant, you can try: [https://flows.blueforcer.de/flow/9dZKg529OyE2](https://flows.blueforcer.de/flow/9dZKg529OyE2)

**Comment by Blueforcer** [comment]
This is not possible with the current scaffold.
Its better to do it by your own with an automation.
If you need ideas how to do this, the discord community can help you for sure
