### ISSUE TITLE
[FEATURE REQUEST] Making DFplayer clone proof

### ISSUE THREAD

**Issue by robercy** [Blueforcer/awtrix-light#245]
Using DFplayers like this one [Chinese clone](https://pt.aliexpress.com/item/32657798948.html?spm=a2g0o.order_detail.order_detail_item.3.d3894c7fboY1Lf&gatewayAdapt=glo2bra), do not work.

After unstable behavior, and a lot of research, I discover (as discussed on [ghmartin77/DFPlayerAnalyzer#10](https://github.com/ghmartin77/DFPlayerAnalyzer/issues/10) the final solution is changing the value of c_msSendSpace to 150 (line 365 on DFMiniMp2.h file), solving the problem, and I believe, will avoid future problems.

My suggestion, if possible and no cause other problem, will be change this value on next PR on github. Thanks.

**Comment by robercy** [comment]
Thanks !!

**Comment by robercy** [comment]
One more thing! 
The value of c_msSendSpace  (line 365 on DFMiniMp2.h file) is still the same, do not changed to 150 !

**Comment by Blueforcer** [comment]
damn this commit wanst pushed xD
its updated now, and will be used in future updates, sorry

**Comment by robercy** [comment]
Don't worry, my friend. Thats why you have ours eyes and attention. Great job.
