### ISSUE TITLE
Visit Button in HA and IP in Sensors

### ISSUE THREAD

**Issue by MrRodz** [Blueforcer/awtrix-light#249]
Hi, firstly thank you for the great work you have done. 
Would it be possible to add the Ip address into the sensors on Home Assistant as well as having a Visit Button in the Mqtt Config like in the below image.  
<img width="410" alt="Screenshot 2023-08-03 at 17 11 29" src="https://github.com/Blueforcer/awtrix-light/assets/38086707/5dddfbd0-9325-4fb3-b044-a30245bbd9c6">

Thanks

**Comment by Blueforcer** [comment]
Unfortunately the HA library im using, doesn't support this feature.
