### ISSUE TITLE
Entity_id's in Home Assistant don't refer to device (not unique per device)

### ISSUE THREAD

**Issue by TheGroundZero** [Blueforcer/awtrix-light#25]
I'm uncertain whether this is something that needs to be solved from within HA or this firmware.

An entity like the one showing the firmware version, has an entity_id of `sensor.version`.
![image](https://user-images.githubusercontent.com/2406013/228462493-dddcb42b-b4e7-4c97-954c-c964dbc5e1b8.png)
Same for e.g. `sensor.battery` or `light.matrix`.
![image](https://user-images.githubusercontent.com/2406013/228463510-36f457f9-75b5-4a75-9543-4b845e5e40fa.png)

If a 2nd device flashed with the same firmware would be added to Home Assistant, this will likely result in entity_id's like `sensor.version_2` or `light.matrix_2`.

These entity_id's are very generic and don't refer to the device they belong too.
It's not unthinkable a generic sensor like `sensor.version` could already be provided by HA itself.

In my opinion, it'd be better to have entity_id's like `sensor.[devicename]_[sensor]`.
For example: `sensor.awtrix_aabbcc_version` or `light.awtrix_aabbcc_matrix`.

A HA user would still be able to manually change these entity_id's if they'd want to.

Compare this to the battery sensor entity for an Aqara door sensor integrated via Z2M:
![image](https://user-images.githubusercontent.com/2406013/228464379-9ec480dc-70b7-4497-ab05-43fbb9b2d21c.png)

**Comment by TheGroundZero** [comment]
This looks relevant: https://www.home-assistant.io/integrations/mqtt/#use-object_id-to-influence-the-entity-id

![image](https://user-images.githubusercontent.com/2406013/228467160-f2eb7d50-c12e-49e7-a6b9-a718429a016b.png)

**Comment by Blueforcer** [comment]
Every sensor has its own unique ID based on the devices ID.
```
name: Version
unique_id: 09464c_ver
device:
  identifiers: ec626009464c
  name: awtrix_09464c
  sw_version: '0.42'
  manufacturer: Blueforcer
  model: AWTRIX Light
state_topic: SHA/ec626009464c/09464c_ver/stat_t
platform: mqtt
```

Since I am dependent on the HA libary I use, im very limited in configuration.
Likewise, a complete overhaul or even a own HA discovery integration due to small blemishesis **currently** not my main goal in the development of awtrix. If you know how to change this to your liking, you are of course free to submit a PR. I currently lack the know-how.

**Comment by TheGroundZero** [comment]
Did the fix for #24 include this unique_id or was this behaviour already present prior?
Because, it could be possible that since I already had the device installed before 0.42 was released, some configuration get _cached_ in HA.
So it could be possible that if I flash my 2nd clock with this firmware it would show up correctly.

**Comment by Blueforcer** [comment]
Unique IDs was made in latest firmware 0.42.wasnt present proir

**Comment by Blueforcer** [comment]
I will close this issue, until the lib gets an update. Feel free to open it again if its possible
