### ISSUE TITLE
old_awtrix2_conversion_0.72.bin

### ISSUE THREAD

**Issue by bimbolongo** [Blueforcer/awtrix-light#251]
Awtrix 2 Hardware

Wenn ich ein Update auf die Version 0.72 durchführe, habe ich nach einigen Minuten
Laufzeit keine Verbindung mehr zum Webinterface der Awtrix.

Nach einem Downgrade auf 0.71 läuft wieder alles normal und man kann das Webinterface erreichen.

Zum Test habe ich mal einen ESP32 mit der Custom Build 0.72 geflasht, da tritt das Problem nicht auf.

**Comment by Blueforcer** [comment]
**?**
