### ISSUE TITLE
add simple count down timer & stop watch

### ISSUE THREAD

**Issue by jonm01** [Blueforcer/awtrix-light#257]
# Feature Request

Missing basic feature:

- stop watch
- count down timer

**Comment by Blueforcer** [comment]
You can implement such Features easily via API. 
Awtrix meant to be controlled by your smarthome

**Comment by danielskowronski** [comment]
So do you mean we’re supposed to spam device with network packets every second to get reasonable timer experience?

**Comment by Blueforcer** [comment]
> So do you mean we’re supposed to spam device with network packets every second to get reasonable timer experience?

If you want to, yes.
