### ISSUE TITLE
WLAN / Battery Status 

### ISSUE THREAD

**Issue by TJHooker** [Blueforcer/awtrix-light#260]
create an Option to show WLAN Connected

 with  red or green Dot  for connected or no connect
same  for  the ACCU  why not  show  traffic Light  red <20%/50% orange/>80 % green 
 in left / right upper or below Corner

**Comment by Blueforcer** [comment]
https://github.com/Blueforcer/awtrix-light/releases/tag/0.81

battery doesnt make sense to me, since you already have an indicator and stats API.. the app.
And there are also users wich build their own clock without a battery

**Comment by TJHooker** [comment]
Greate Wlan and MQTT  you are right with the battery THX

**Comment by Ysbrand** [comment]
Can this (red/yellow pixel) be added to the documentation? (at least I couldn't find any reference to it)
