### ISSUE TITLE
[BUG] Cannot download any LaMetric icons -  Error "This ID doesn't exist"

### ISSUE THREAD

**Issue by mnul** [Blueforcer/awtrix-light#262]
# Bug report

## Describe the bug

Cannot download any LaMetric icons through the web interface. Error "This ID doesn't exist". Preview works fine.

## Additional information

- Devices involved:
  - Model: Ulanzi Awtrix Smart Pixel Clock 2882 (TC001)
  - AWTRIX-LIGHT version: v0.74

## To Reproduce

Go to the webinterface of your device, switch to [icons]. enter any valid LaMetric Icon ID (e.g. 10400) and click preview, icon will show. 
If you cllick on download, error window pops up and says "This ID doesn't exist".

**Comment by Blueforcer** [comment]
try another browser, make sure javascript is enabled, and clear the brosercache

**Comment by mnul** [comment]
latest update seems to have fixed it ...

**Comment by Blueforcer** [comment]
mhh there was no change to this:)
but glad it work now

**Comment by tebald1** [comment]
I'm facing the same issue. Preview works fine, download shows "this ID doesnt exist".

I'm running AWTRIX 3 0.96. Tried Firefox and Edge on Windows and Chrome on Android. Same error on all plattforms.

Any workaround for this issue?

**Comment by imac941** [comment]
I have the same issue with version 0.96.

Does anyone have any ideas?
