### ISSUE TITLE
Question: self build awtrix, LED order

### ISSUE THREAD

**Issue by mark77-DE** [Blueforcer/awtrix-light#264]
I bought an 8x32 Display from ali.

Idea was to build an light (no buttons, no sensors) and weatherproof version of the display, but unfortunately, the order of the LEDs seems different.

Before I start digging deeper, does anyone know the order of the LEDs?

Would it be "easy" to change the order by source code?

Thanks, Mark

**Comment by Blueforcer** [comment]
No need to modify the code
https://blueforcer.github.io/awtrix-light/#/dev

Just try wich matrix type fit yours

**Comment by mark77-DE** [comment]
Wow, this is great!

Is it also possible to disable display of battery state without hardware buttons? Or have I overread this as well?

**Comment by Blueforcer** [comment]
Disable sensor_reading and have a look at the settings API to disable battery app

**Comment by mark77-DE** [comment]
Danke dir
