### ISSUE TITLE
[BUG] Update error

### ISSUE THREAD

**Issue by Calimerorulez** [Blueforcer/awtrix-light#265]
Running 0.74, I'm trying to update my Ulanzi clock. When clicking  'Start update' in Home Assistant, the display shows 'Err cnct'. I saw this behavior the first time in 0.73. Version 0.72 updated correctly to 0.73 when using this procedure.

**Comment by GitHoubi** [comment]
> Running 0.74, I'm trying to update my Ulanzi clock. When clicking  'Start update' in Home Assistant, the display shows 'Err cnct'. I saw this behavior the first time in 0.73. Version 0.72 updated correctly to 0.73 when using this procedure.

Reboot the device and then try again to update fw immediately after the boot process finished. It might need a try or two but will eventually succeed to update the fw.

**Comment by Blueforcer** [comment]
This is a bug in the http updater wich i cant change.
Sometimes it work sometimes not. no matter wich firmware.
its always better to upload the firmware to webinterface and will work everytime
