### ISSUE TITLE
[FEATURE REQUEST] Daisy Chaining with second (third, fourth,... TC001) to get a resolution of 64x8, 96x8, 128x8,...) 

### ISSUE THREAD

**Issue by gentschi** [Blueforcer/awtrix-light#269]
# Feature Request
de:
Ist es ohne größeren Aufwand möglich, eine Art "Slave-Mode" für einen zweiten, dritten oder vierten TC001 zu implementieren, den der erste TLC001 im "Master-Mode" mit Daten versorgt, um eine höhere Auflösung von 64x8, 96x8, 128x8 usw. zu bekommen?
### Is your feature request related to a problem?

en:
Is it possible without much effort to implement a kind of "slave mode" for a second, third or fourth TC001, which is supplied with data by the first TC001 in "master mode" to get a higher resolution of 64x8, 96x8, 128x8 etc.?

If so, then add a clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

**Comment by Blueforcer** [comment]
Das wird eher nicht möglich sein, jede noch so kleinste Latenz würde das visuelle verhalten stören, vorallem beim scrollen.
Habe mich damit schonmal beschäftigt aber die Idee wieder verworfen. sorry
