### ISSUE TITLE
[BUG] Update API doesnt work

### ISSUE THREAD

**Issue by Blueforcer** [Blueforcer/awtrix-light#270]
Note for me: /doupdate doesnt work :-)

**Comment by hardoverflow** [comment]
Can confirm this behavior. Sometimes it works.

**Comment by Blueforcer** [comment]
Currently it doesn't work at all.
The last versions this was because of not enough ram for https reuqests.

**Comment by SentiQ** [comment]
Still getting "ERR CNCT" at firmware v0.73

**Comment by Blueforcer** [comment]
> Still getting "ERR CNCT" at firmware v0.73

We're at v0.81...

**Comment by SentiQ** [comment]
So I have to update manually?

**Comment by Blueforcer** [comment]
You can still trigger via http, onscreen or Homeassistant
