### ISSUE TITLE
Infinit loop after setting MQTT credentials [BUG]

### ISSUE THREAD

**Issue by tommimaus** [Blueforcer/awtrix-light#272]
# Bug report

## Describe the bug

Add a description of the bug. Detail the expected behaviour in contrast with the behaviour you're observing.

## Additional information

- Devices involved:
  - Model: Ulanzi Awtrix Smart Pixel Clock 2882 (TC001)
  - AWTRIX-LIGHT version: [ eg. v0.45 ]

## Logs

```text
(optional) Add relevant logs which could help tackle the problem.
```

**Comment by Blueforcer** [comment]
See pinned issue. https://github.com/Blueforcer/awtrix-light/issues/165
**Next time please fill out the issue template otherwise it will be closed immediately**

**Comment by tommimaus** [comment]
> Add a description of the bug. Detail the expected behaviour in contrast with the behaviour you're observing.
After setting the (correct) MQTT credentials and restarting the ULANZI it goes in an infinite loop .
The Order of DISPLAY Messages after Restart:
Rev. 0.81
AWTRIX
IP Address
MQTT ... 
short Display of Date Time
CHeck Upd
No Up :(

Restart the loop as written above.

The MQTT Data Transfer for has happened correctly.
