### ISSUE TITLE
[FEATURE REQUEST] Disable next and previous app buttons

### ISSUE THREAD

**Issue by aleesposito85** [Blueforcer/awtrix-light#273]
# Feature Request

### Is your feature request related to a problem?

No

### Describe the solution / feature you'd like

It would be nice if we could disable the next and previous buttons to not transition the apps. 
In this way we could build custom app that can be interactive. E.g. the Ulanzi Score board app

**Comment by Blueforcer** [comment]
Already possible via settings API (BLOCKN)
