### ISSUE TITLE
[BUG] Humidity calibration offset

### ISSUE THREAD

**Issue by alfureu** [Blueforcer/awtrix-light#275]
# Bug report

## Describe the bug

So I have couple of humidity sensors in my home, and the Ulanzi's is quite off (10+ %). I know I can disable it and show a different sensor's output on the screen, but I was wondering whether it would be possible to set manually an offset (positive and/or negative) to the humidity sensor, so it is closer to reality.

## Additional information

- Devices involved:
  - Model: Ulanzi Awtrix Smart Pixel Clock 2882 (TC001)
  - AWTRIX-LIGHT version: v0.83

**Comment by Blueforcer** [comment]
https://blueforcer.github.io/awtrix-light/#/dev
