### ISSUE TITLE
[FEATURE REQUEST] Set brightness through API

### ISSUE THREAD

**Issue by claell** [Blueforcer/awtrix-light#277]
# Feature Request

### Is your feature request related to a problem?

Currently, there seems to be no way to set the brightness through the API? Or am I just reading the docs wrong: https://blueforcer.github.io/awtrix-light/#/api?id=change-settings? It says `BRI` "Determines". Does it mean it sets the brightness or returns the current brightness value?

Possibly, I just misunderstand, and it's already supported?

**Comment by Blueforcer** [comment]
It sets the brightness (if it's not in Auto brightness)

**Comment by claell** [comment]
Alright, thanks for clarifying. Then it's fine!
