### ISSUE TITLE
[FEATURE REQUEST] Lower minimum brightness on auto brightness

### ISSUE THREAD

**Issue by claell** [Blueforcer/awtrix-light#278]
# Feature Request

### Is your feature request related to a problem?

With auto brightness on, the brightness in a dark room is still too high for me. Not sure, what the actual brightness percentage was, though. So possibly, it already was at 1 % and that is just still too bright.

### Describe the solution / feature you'd like

Lower minimum brightness

### Describe alternatives you've considered

Reading brightness in and based on that, turn off the display or enable some night mode via the API.

### Additional context

None

**Comment by Blueforcer** [comment]
https://blueforcer.github.io/awtrix-light/#/dev

**Comment by claell** [comment]
Thanks!

> Create a dev.json in your filemanager.

That refers to the AWTRIX light file manager?

**Comment by claell** [comment]
And in case, that's still too bright: Is that a hardware limitation? Or would it be possible to dim the matrix even further, and is just not supported in AWTRIX Light?

**Comment by Blueforcer** [comment]
Its not possible.
