### ISSUE TITLE
[BUG] MQTT options not showing anymore

### ISSUE THREAD

**Issue by LucaZiegler** [Blueforcer/awtrix-light#288]
# Bug report

## Describe the bug

Add a description of the bug. Detail the expected behaviour in contrast with the behaviour you're observing.

## Additional information

- Devices involved:
  - Model: Ulanzi TC001
  - AWTRIX-LIGHT version: 0.83

## To Reproduce

- The mqtt configuration tab is not showing anymore after an update and homeassistant is not finding the ulanzi anymore

## Expected behavior

- Able the change the mqtt configuration

## Screenshots
![image](https://github.com/Blueforcer/awtrix-light/assets/36471502/21b043af-d8fe-494a-b96d-d1b342df01a4)

## Logs

```text
(optional) Add relevant logs which could help tackle the problem.
```

**Comment by Blueforcer** [comment]
Check the config.json. maybe it's broken. You can delete this file and reboot, awtrix will generate a new one.

**Comment by LucaZiegler** [comment]
> All that stuff for the Webinterface and the entered settings.

Where can I get a Template?
Its not mentioned in the Documentation..

**Comment by Blueforcer** [comment]
As I told you, just delete this file and reboot. Awtrix will generate a new one.

**Comment by LucaZiegler** [comment]
> As I told you, just delete this file and reboot. Awtrix will generate a new one.

Ah sorry, yeah that worked, thx!
