### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Basduu** [Blueforcer/awtrix-light#289]
# Bug report

## Describe the bug

The WLAN connection is not established. As soon as I flashed the Ulanzi and scan for the available WiFi, nothing happens. Nothing is found and when I enter the WiFi access data and click on connect, nothing happens either. The Ulanzi stays in AP mode. This is now the case with version 0.83. Before 0.79 the connection was established correctly. I have attached the log file from the web flasher.

## Additional information

- Devices involved:
  - Model: Ulanzi Awtrix Smart Pixel Clock 2882 (TC001)
  - AWTRIX-LIGHT version: [ v.083 ]

## Additional context

[esp-web-tools-logs (3).txt](https://github.com/Blueforcer/awtrix-light/files/12487081/esp-web-tools-logs.3.txt)

**Comment by Basduu** [comment]
hi, Problem is the Mesh-Repeater. In near off the router wifi connected without problems. But when the meshrepeater is near then no connection is established.

**Comment by Blueforcer** [comment]
ok, so doesnt seem like a firmware issue.

**Comment by groserge** [comment]
Hello i have the ulanzi with Autrix I had to change my WiFi router and the ulanzi is stuck in AP MODE what could I do to réinitialize? I try to connect to my Mac in usb but still can’t connect to the interface .. thank you for your help

**Comment by groserge** [comment]
![Uploading image.jpg…]()

**Comment by groserge** [comment]
> Connect with your phone and setup the new wifi like on the first setup .
Simple effective but it didn't come to my mind thank you very much for your help you helped me well it's good it works!!
