### ISSUE TITLE
[Feature Request] Add option to disable the start sound

### ISSUE THREAD

**Issue by N1c093** [Blueforcer/awtrix-light#29]
Currently the awtrix-light plays a sound, when the device starts.
It would be great when this start sound could be disabled.

**Comment by Blueforcer** [comment]
It's already implemented in my current developer state 👍

**Comment by Blueforcer** [comment]
https://github.com/Blueforcer/awtrix-light/commit/2124f832d016b288d8881df2636732bc828e983d
