### ISSUE TITLE
No IconTab in Webinterface[BUG]

### ISSUE THREAD

**Issue by DonatPlayZ** [Blueforcer/awtrix-light#291]
# Bug report

## Describe the bug

Hello, since Today i got nomore "Icon" tab in the Webinterface. I already tried to "reupdate" to v. 0.83 still no tab for the icons, yesterday everything worked and i uploaded some icons

## Additional information

- Devices involved:
  - Model: Ulanzi Awtrix Smart Pixel Clock 2882 (TC001)
  - AWTRIX-LIGHT version: 0.83

## Logs

```text
(optional) Add relevant logs which could help tackle the problem.
```

## Additional context

![Awtrix](https://github.com/Blueforcer/awtrix-light/assets/30085560/75b965ac-3fea-4d39-b75d-8b4af4d7f717)

**Comment by Blueforcer** [comment]
Did you modified the config.json?

Delete ist and reboot awtrix to create a new one

**Comment by robson80** [comment]
Hi,
I just had the same issue with version 0.90. I changed nothing, but uploaded 5 icon files in total. 

Also, some other tabs were not visible anymore: "Time", "Auth".
Furthermore, in "MQTT" tab only the "Broker" field was visible. All other fields (e.g. "Port", "Username") were gone.

As @Christian-4711 already stated, deleting file "DoNotTouch.json" and restaring the ESP helped.
What an irony when looking at the file name ;)

**Comment by manalishi70** [comment]
Same behavior here: AWTRIX Light 0.94
