### ISSUE TITLE
[FEATURE REQUEST] better ( darker ) night Mode

### ISSUE THREAD

**Issue by martz170** [Blueforcer/awtrix-light#293]
# Feature Request

Hello,

here´s a Feature request for this Clock.
Even when using the brightness setting to auto mode, the darkest setting in auto mode is still to bright for the night.
It would be great to have the same night mode like the Lametric Clock.
Only Clock with 1%  and without Icon on left - only clock.

Thank you.

**Comment by Blueforcer** [comment]
There will be no native night mode. You have all posibilities to make your ows with your personal prefenrences.
Or use one of these
https://flows.blueforcer.de/search?query=night
