### ISSUE TITLE
[FEATURE REQUEST] Add display state in api

### ISSUE THREAD

**Issue by DrRSatzteil** [Blueforcer/awtrix-light#296]
# Feature Request

### Is your feature request related to a problem?

I'd like to keep the state of the display (On/Off) in sync with my smart home solution. However the display state cannot be retrieved via mqtt/http.

### Describe the solution / feature you'd like

Add the current display state to the stat topic/endpoint.

### Describe alternatives you've considered

Just live with it 😀 

### Additional context

If this already exists please let me know ☺️

**Comment by Blueforcer** [comment]
You can get it with the MATP key in the settings api

**Comment by DrRSatzteil** [comment]
Wow I completely missed this endpoint 🙈

Sorry for opening this issue but thanks for your fast feedback! Issue closed.

**Comment by DrRSatzteil** [comment]
Sorry to reopen this but is there a way to acutally receive settings via mqtt? It seems that this is only possible through the http api, right?

**Comment by Blueforcer** [comment]
Its not possible, mqtt is not made for requests.

**Comment by DrRSatzteil** [comment]
Would it be an option for you to have a sendsettings topic like for the screen/sendscreen pair? I think this would be a great compromise between sending in intervals and not being able to access the information at all via mqtt.

**Comment by DanielHabenicht** [comment]
One more question regarding the `MATP` key: Should it be added to the `api.md` table? 
Because one only gets to know that it exists after trying out or finding this issue. 
It probably might also be a good idea to add the `GET` Option to the settings table.

**Comment by Blueforcer** [comment]
No, that was just a key I needed for the app.

It will be available in the stats API next release

**Comment by DanielHabenicht** [comment]
Sorry to bother you again! 
It was already available in the stats API (for version 0.88), it just was not documented in the markdown docs (and still isn't). Should I add a PR to document it?

By the way, are you interested in hosting an [openapi](https://swagger.io/specification/) specification for the API? 
This should make it easier to integrate with any 3rd party systems. I almost have it done for an Integration with HA I am building, so I am happy to contribute back.
