### ISSUE TITLE
[FEATURE REQUEST] Add unique device ID in api

### ISSUE THREAD

**Issue by DrRSatzteil** [Blueforcer/awtrix-light#297]
# Feature Request

### Is your feature request related to a problem?

When linking the device to a smart home solution it is desirable to be able to identify a device by a unique hardware ID. Right now I use the topic as ID but if you change the topic the system will recognise this as a new device. It would be good to be able to change properties like the topic without loosing the link to the actual device.

### Describe the solution / feature you'd like

Add some kind of hardware ID (e.g. MAC Address) to the stats topic/endpoint.

### Describe alternatives you've considered

I will just live with it 😊

### Additional context

Nothing

**Comment by Blueforcer** [comment]
an unique ID already exists, but not exposed. i can add it to the stats i think
