### ISSUE TITLE
[FEATURE REQUEST] add an option to mirror display

### ISSUE THREAD

**Issue by volkerrichert** [Blueforcer/awtrix-light#298]
# Feature Request

I have my awtrix sitting on a shelf above my bed. During night the time can't be read easily. It would be fine to have an option to make it more "readable". This will also help to mount it upside down. 

### Describe the solution / feature you'd like

Add an option to mirror the display at the x- and/or y- axis. This can be two options, one for each axis or just one with 4 possible settings (none / mirror X / mirror Y / mirror both)

**Comment by Blueforcer** [comment]
There is already a mirror and flip function
https://blueforcer.github.io/awtrix-light/#/dev

**Comment by volkerrichert** [comment]
Ahh, i missed that. THX

**Comment by volkerrichert** [comment]
ah, ok. Just at boot time. Is there a change to change ist via API at runtime?

**Comment by Blueforcer** [comment]
Unfortunately not

**Comment by volkerrichert** [comment]
sound promising..
