### ISSUE TITLE
[Feature Request] Possibility to check update by mqtt

### ISSUE THREAD

**Issue by uiltonlopes** [Blueforcer/awtrix-light#30]
With this feature we can set a schedule to check and update the device automatically

**Comment by TheZoker** [comment]
Would also be nice, to expose the update as a HA update sensor with a button to update the firmware just like the shelly (or esphome) integration:
![image](https://user-images.githubusercontent.com/1368405/229295090-c7bd67a6-e394-42d3-b897-65f577b39d8e.png)

But maybe this is limited by the external library

**Comment by Blueforcer** [comment]
> Would also be nice, to expose the update as a HA update sensor with a button to update the firmware just like the shelly (or esphome) integration: ![image](https://user-images.githubusercontent.com/1368405/229295090-c7bd67a6-e394-42d3-b897-65f577b39d8e.png)
> 
> But maybe this is limited by the external library

Unfortunally not possible

**Comment by Blueforcer** [comment]
https://github.com/Blueforcer/awtrix-light/commit/bc72069ae3c9032cb4b1c99ff83cfb761b3ccb58
