### ISSUE TITLE
[BUG] Restore fails with directories in ICONS folder

### ISSUE THREAD

**Issue by SenH** [Blueforcer/awtrix-light#306]
# Bug report

## Describe the bug

I have a few dirs in my ICONS dir. The backup is working correctly but upon restore these folders and their contents are not put back on the FS. The Web UI displays "restore failed". When I create the folders manually in the FileManager and retry restore it works correctly.
<img width="537" alt="Screenshot 2023-09-09 at 10 07 25" src="https://github.com/Blueforcer/awtrix-light/assets/168986/f8084c00-370b-43fc-ba13-5f0e7e39b043">

## Additional information

- Devices involved:
  - Model: Ulanzi Awtrix Smart Pixel Clock 2882 (TC001)
  - AWTRIX-LIGHT version: v0.86

**Comment by Blueforcer** [comment]
The Icons folder was never intended to contain subfolders.
