### ISSUE TITLE
No changes for temp and hum

### ISSUE THREAD

**Issue by galluslongus** [Blueforcer/awtrix-light#307]
# Bug report

## Describe the bug

after changing the values for hum and/or temp compensation and saving / rebooting, nothing changed.
it doesnt matter if i edit the json file or use the browser in Time Tab.

## Additional information

- Devices involved:
  - Model: Ulanzi Awtrix Smart Pixel Clock 2882 (TC001)
  - AWTRIX-LIGHT version: [ eg. v0.86 ]

**Comment by Blueforcer** [comment]
Still works as expected.
Please show me your dev.json

**Comment by galluslongus** [comment]
{
  "temp_offset": -18,
  "hum_offset": 25,
}

**Comment by Blueforcer** [comment]
The JSON is invalid because of the last comma. The editor should tell you the error by a red cross

**Comment by galluslongus** [comment]
damned, thats it...thank you
