### ISSUE TITLE
Red flashing Dot/LED in the upper left corner

### ISSUE THREAD

**Issue by wolfgang1962** [Blueforcer/awtrix-light#308]
I got three TC001 and they run in different rooms. On two of it i recognized a flasching red LED in the upper left corner. I know, the Indicators are on the right side - I didn't find any information about an indicator on the left side.
I tried to figure out, what is the reason, or what situation will start the flashing LED.
It seems it ist depending on the WIFI signal. I checked the value in iobroker and it was poor -85dB. Additionally the shown Values from the iobroker adapter were old values and not actual.
Sometimes it helped only to restart the TC001, sometimes I needed to setup the WIFI again.
After that the WIFI was better -70dB  but getting lower in a few days without moving the TC001 or anything og the WIFI devices.

Am I right with my speculation?

**Comment by Blueforcer** [comment]
It fades when awtrix doesn't have a wifi connection
