### ISSUE TITLE
[BUG] WiFi reconnect partly successful

### ISSUE THREAD

**Issue by DrRSatzteil** [Blueforcer/awtrix-light#310]
# Bug report
Unexpected WiFi behaviour after lost connection (version 0.86 Bugfix)

## Describe the bug

WiFi is switched off in parts of our house during night time so the Ulanzi clock is without connection for a couple of hours. In the morning it shows "AP MODE" on the screen. So far this is the expected behaviour I guess.

The thing is: the device is actually not in AP mode. I see that it has an active dhcp lease and I can even access the web frontend where it also shows me that it is connected to my wifi network. All other features of the device are non-functional (API, screen mirror, etc.) until after a manual reboot.

## Additional information

- Devices involved:
  - Model: Ulanzi Awtrix Smart Pixel Clock 2882 (TC001)

## To Reproduce

Turn off WiFi until Clock enters AP mode. Then reactivate WiFi. Clock is reconnecting successfully but thinks it's still in AP mode.

## Expected behavior

Preferably leave AP mode and commence normal operation.

## Screenshots

N/A

## Logs

```
I don't have any logs so far. If required I'm happy to create a log file. 
```

## Additional context

N/A

**Comment by ofenboecka** [comment]
Thanks DrRSatzteil, I have a similar setup with WiFi turned off at night.
It's true that after re-enabling WiFi, awtrix reconnects and I'm able to access the web interface - and initiate a reboot there.
But it's not responsive to http API calls, a reboot fails with "FileNotFound":

$ curl -X POST -H 'Content-Type:application/json' http://[awtrixIP]/api/reboot --data '{ }'
FileNotFound

Therefore, the reboot cannot be automated.
Is there a way to completely turn off this automatic AP mode?

Thanks, br

**Comment by Xeno22** [comment]
Same here - since two days my Awtrix greets me in the morning with "AP MODE" enabled.
No idea if this happens because of the new Awtrix light 0.86 or the new UniFi firmware ...
It seems to disconnect and reconnect, but Awtrix stays in AP MODE:
![image](https://github.com/Blueforcer/awtrix-light/assets/1567623/a94b5e2b-41ce-4943-850c-5a367aafbc6c)

**Comment by Blueforcer** [comment]
Awtrix only enters AP mode, if it can't connect to the wifi **at boot **. There is no further check during runtime.
So either your awtrix runs out of power or there is a different problem.

**Comment by kevstone122** [comment]
Okay this i also recognize if sometimes the clock doesn't get that fast an IP from DHCP, then it changes to the AP Mode. 
But today my mesh network got hang and so there was no internet anymore available. All clocks have "AP Mode" on the Display. 
I reboot the mesh system and then i have to reboot each clock. It looks like, that the clock is changing during runtime into the AP Mode. They are always on the USB C Port.

![Image](https://github.com/user-attachments/assets/eb001ccf-878a-4671-90d3-50a7ade68e0e)
