### ISSUE TITLE
Node red MQTT

### ISSUE THREAD

**Issue by madmax5900** [Blueforcer/awtrix-light#315]
Hello!

I would like to control the Ulanzi with Node Red via MQTT.

Unfortunately I haven't done that yet.

Can anyone help me how to do this?

Thanks in advance.

**Comment by Blueforcer** [comment]
I don't think the Project GitHub is the right place for basic questions wich mainly hasn't anything to do with awtrix.

I recommend to join the awtrix discord or use nodered forums
