### ISSUE TITLE
[BUG] Icon is not displayed again with pushIcon=2 

### ISSUE THREAD

**Issue by pherga** [Blueforcer/awtrix-light#316]
Related, maybe, to the previous bug I reported last week with textOffset, if pushIcon = 2 on an MQTT payload the icon does not return on subsequent passes. Instead, The icon is displayed when the text in offset reaches the location of the icon.

- Devices involved:
  - Model: Ulanzi Awtrix Smart Pixel Clock 2882 (TC001)
  - AWTRIX-LIGHT version: v0.87

Steps to Reproduce:
1. Publish the following payload:
{  "text": "Good Night",  "repeat" : 3,  "pushIcon" : 2, "textOffset" : 33, "icon" : "w-clear-night" }

Expected Behavior
After the first pass, the icon should return while the text starts scrolling again.

Actual Behavior
On the second or any subsequent passes the icon does not return. Instead it is displayed only when the text reaches the location of the icon.

Screenshots
![awtrix](https://github.com/Blueforcer/awtrix-light/assets/130929897/aca07db3-5d62-461d-a90f-98eaeccec109)

**Comment by Blueforcer** [comment]
Crazy that's what I've fixed.. let me check this

**Comment by Blueforcer** [comment]
Notify or CustomApp?!

**Comment by pherga** [comment]
Yup. textOffset=22 does work as expected.

**Comment by pherga** [comment]
Thank you so much, Stephan. Keep it up! 💪🏻
