### ISSUE TITLE
[BUG] Deadlock with 0.87

### ISSUE THREAD

**Issue by Xeno22** [Blueforcer/awtrix-light#318]
# Bug report

## Describe the bug

Updated my TC001 today because of the „stuck in AP mode“ issue, but my clock just stopped scrolling/working 10minutes ago.
I kicked it from the wifi and it did not reconnect. So probably deadlocked..
Power off and on worked as expected.

## Additional information

- Devices involved:
  - Model: Ulanzi Awtrix Smart Pixel Clock 2882 (TC001)
  - AWTRIX-LIGHT version: v0.87

**Comment by Blueforcer** [comment]
How can i reproduce this issue?

**Comment by Xeno22** [comment]
> How can i reproduce this issue?

That is a really good question :)
It took 2-3 hours to freeze.
![image](https://github.com/Blueforcer/awtrix-light/assets/1567623/4c232d64-d080-4d8f-bef4-96365e9d4c1f)

I could try to hook it up to my MBP and check the serial output. Maybe my board broke? At least I heard of sporadic freezes.
For the start I would flash 0.85 and see if it still freezes as this was the last known good version.
I could also fetch 0.86 and patch out the "no wifi -> restart" code.

Clock Apps: internal DateTime, HA AWTrix Weather + Forecast, HA Awtrix light Weather App.

**Comment by Blueforcer** [comment]
I dont think downgrading will help that much.

The only thing i could imagine is a endless loop in some very special cases here
https://github.com/Blueforcer/awtrix-light/blob/bda4082c52d8173bccc5bde83d08e880ce867e04/src/GifPlayer.h#L572

You could add a Serial.println(currentFrame); inside the loop, and check the serial outout when the deadlock happens.

**Comment by Xeno22** [comment]
Possible - Maybe the Fog GIF makes it worse :)
Will let 0.84 run for a few hours, then upload my modified 0.87 firmware (also added a WD, just in case) and see what it says on the serial line.

OT: Regarding the GIF player: is the reason known why some grey colors change to pink (especially on the clouds)?

**Comment by Blueforcer** [comment]
It's because of the compression, I don't have much skill in GIF decoding, so currently I'm unable to catch every method. You can uncompress the gif with a online tool and it should be fine.
You can also upload it here so maybe I find something to fix

**Comment by Xeno22** [comment]
0.84 did not freeze till now - so probably a change in 0.87 lets it run in circles ;) Or it depends on the rendered icons.

**Comment by Blueforcer** [comment]
It's not possible for the LEDs to hold the colors at that low brightness. Youll get best colors in 20-40%

**Comment by pherga** [comment]
It seems, indeed, to be related to some animated icons. In my case it got stuck exactly at the same spot with the "cloudy" weather icon.

**Comment by pherga** [comment]
I'm getting stuck with this icon.
![w-cloudy](https://github.com/Blueforcer/awtrix-light/assets/130929897/e6ac96f9-06d9-4af0-b0b5-1fe5424c1306)

**Comment by individualist99** [comment]
Same Here. Awtrix gets stuck multiple times a day since 0.87 and has to be restarted then. Seems like  it happens every now then when custom App from Home Assistent Integration "AWTRIX Weather ⛈️ + Forecast + 🌕️" is displayed

**Comment by Blueforcer** [comment]
> I dont think downgrading will help that much.
> 
> The only thing i could imagine is a endless loop in some very special cases here
> https://github.com/Blueforcer/awtrix-light/blob/bda4082c52d8173bccc5bde83d08e880ce867e04/src/GifPlayer.h#L572
> 
> You could add a Serial.println(currentFrame); inside the loop, and check the serial outout when the deadlock happens.
> 
> 

Would be nice if anyone can try this. I'm unable to reproduce it

**Comment by Xeno22** [comment]
> > I dont think downgrading will help that much.
> > The only thing i could imagine is a endless loop in some very special cases here
> > https://github.com/Blueforcer/awtrix-light/blob/bda4082c52d8173bccc5bde83d08e880ce867e04/src/GifPlayer.h#L572
> > 
> > You could add a Serial.println(currentFrame); inside the loop, and check the serial outout when the deadlock happens.
> 
> Would be nice if anyone can try this. I'm unable to reproduce it

Will add the debug and give it a try.

**Comment by Xeno22** [comment]
Bit boring atm:
`0<3 0<3 1<3 2<3 0<3 1<3 2<3 0<2 0<2 1<2 0<3 0<3 1<3 2<3`

**Comment by Xeno22** [comment]
Ok, had a deadlock. It indeed stays the the playGif loop.
Seems like it crashed after it switched the icon and the frame counter got off. Probably a missing reset of something?

Format: playGif function prints the params and then the loop with currentframe + "<" + frame.
```
playGif:0x0 3 w-cloudy.gif0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 1<3 2<3 playGif:0x0 3 w-cloudy.gif0<3 0<3 1<3 2<3 playGif:0x0 15 w-clear-night.gif0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 

.... many repeated lines ...

3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 0<15 1<15 2<15 3<15 4<15 E (3354570) task_wdt: Task watchdog got triggered. The following tasks did not reset the watchdog in time:
E (3354570) task_wdt:  - loopTask (CPU 1)
E (3354570) task_wdt: Tasks currently running:
E (3354570) task_wdt: CPU 0: IDLE
E (3354570) task_wdt: CPU 1: loopTask
Framebuffer_GFX::begin Width: 32 Height: 8 Num Pixels: 256
Connecting to Thermomix
...............playGif:0x0 3 w-clear-night.gif0<3 1<3 2<3 playGif:0x0 3 w-clear-night.gif0<3 1<3 2<3 playGif:0x0 3 w-clear-night.gif0<3 1<3 2<3 playGif:0x0 3 w-clear-night.gif0<3 1<3 2<3 playGif:0x0 3 w-clear-night.gif0<3 1<3 2<3 playGif:0x0 3 w-clear-night.gif0<3 1<3 2<3 playGif:0x0 3 w-clear-night.gif0<3 1<3 2<3 playGif:0x0 3 w-clear-night.gif0<3 1<3 2<3 playGif:0x0 3 w-clear-night.gif0<3 1<3 2<3 playGif:0x0 3 w-clear-night.gif0<3 1<3 2<3 playGif:0x0 3 w-clear-night.gif0<3 1<3 2<3 playGif:0x0 3 w-clear-night.gif0<3 1<3 2<3 playGif:0x0 3 w-clear-night.gif0<3 1<3 2<3 playGif:0x0 3 w-clear-night.gif0<3 1<3 2<3 playGif:0x0 3 w-clear-night.gif0<3 1<3 2<3 playGif:0x0 3 w-clear-night.gif0<3 1<3 2<3 playGif:0x0 3 w-clear-night.gif0<3 1<3 2<3 playGif:0x0 3 w-clear-night.gif0<3 1<3 2<3 playGif:0x0 3 w-clear-night.gif0<3 1<3 2<3 playGif:0x0 3 w-clear-night.gif0<3 1<3 2<3 playGif:0x0 3 w-clear-night.gif0<3 1<3 2<3 playGif:0x0 3 w-clear-night.gif0<3 1<3 2<3
```

At least my watchdog code helped a lot :D

**Comment by Blueforcer** [comment]
Ok then I know why it doesn't happen to me. I don't change the icons in a CustomApp like in the weather app. Awtrix fast-forward the gif to the last shown frame to get a smooth transition. In your case it tries to forward to frame 15 wich doesn't exists. So I need to catch that. Thanks for your help.

**Comment by Xeno22** [comment]
Glad that I could help. If I should try anything else, just let me know. Maybe I'll try to understand your code better if I find time.
And many thanks for your effort!
Fyi: 0.84 worked for >24h.

**Comment by Blueforcer** [comment]
I need to understand it too 🤪🤣

**Comment by jackawacka** [comment]
I updated to 0.87 and the freeze happens to me as well (2 times - never did before) I'm using the stock Time and a the custom weather flow in node-red (but changed the output via mqtt) Both times it freezes in the weather app.

**Comment by Blueforcer** [comment]
Issue is already located. Need to fix it now

**Comment by Blueforcer** [comment]
@Xeno22 can you test the latest commit to main please

**Comment by Xeno22** [comment]
> @Xeno22 can you test the latest commit to main please

The currentFrame resets look promising. Will give it a try.

**Comment by Xeno22** [comment]
> @Xeno22 can you test the latest commit to main please

After 4:30h of uptime I did not see a single crash. But the custom app still shows the cloudy gif.

**Comment by Blueforcer** [comment]
Maybe you can force some various animated icons to the same app

**Comment by Xeno22** [comment]
> Maybe you can force some various animated icons to the same app. I can test it tomorrow afternoon

Switched the icons while the custom app was shown and it worked like a charm.
I would give it a go.

**Comment by Xeno22** [comment]
Still works as expected.

**Comment by Blueforcer** [comment]
https://github.com/Blueforcer/awtrix-light/releases/tag/0.88

**Comment by wolfgang1962** [comment]
It is still happening with 0.88 after a while...
I restarted - it runs for nearly two hour and freeze again...
I turned back to 0.86
