### ISSUE TITLE
[BUG] "uppercase" setting in dev.json does not work.

### ISSUE THREAD

**Issue by marek2k** [Blueforcer/awtrix-light#320]
# Bug report

The "uppercase" key in dev.json is not active.

## Additional information

Setting the "uppercase" key to "false" no longer works. This option worked well for me in the version 0.76. After upgrade to 0.87 all displayed texts are in uppercase.

Here is my **dev.json** file
```
{
  "matrix": 2,
  "uppercase": false,
  "temp_dec_places": 1,
  "temp_offset": -5,
  "hum_offset": 10,
  "min_brightness": 8,
  "max_brightness": 90
}
```

**Comment by Blueforcer** [comment]
https://github.com/Blueforcer/awtrix-light/releases/tag/0.88
