### ISSUE TITLE
[FEATURE REQUEST] Reconnecting the Wi-Fi connection after interruption.

### ISSUE THREAD

**Issue by ME8800** [Blueforcer/awtrix-light#323]
After a basic feature has been removed, I kindly request an optional monitoring of the Wi-Fi connection. Instead of a full restart, this could involve simply reconnecting the WiFi to the stored network on the ESP or just reinitializing the Wi-Fi module.
Thank you for your excellent work.

**Comment by Blueforcer** [comment]
Please read the changelog carefully.
The reboot was removed, not the reconnect...
