### ISSUE TITLE
[FEATURE REQUEST]

### ISSUE THREAD

**Issue by k-a-r-g** [Blueforcer/awtrix-light#328]
# Feature Request

### Is your feature request related to a problem?

The feature is not related to a problem.

### Describe the solution / feature you'd like

It would be great if transition effects are also used to switch to, and away from, notifications.

### Describe alternatives you've considered

The current alternative is to display notifications without transitions. Which, of course, works well, but is less eye candy.

**Comment by Blueforcer** [comment]
Notification are overlays wich sits above the apps. There is nothing to transition with.sorry
