### ISSUE TITLE
[BUG] Current licensing prevents commercial use altogether

### ISSUE THREAD

**Issue by flobeier** [Blueforcer/awtrix-light#329]
# Bug report

## Describe the bug
The README states to contact you if one wants to use the project commercially. However, since it contains code from contributors and you're not using a [Contributor License Agreement (CLA)](https://github.com/cla-assistant/cla-assistant), it wouldn't be possible to do so without asking every contributor for permission.

**Comment by Blueforcer** [comment]
So what license I need then?

**Comment by flobeier** [comment]
The issue is that the contributors retain full rights to their code as no CLA is in place. This means you can't change the license or distribute the code under a different license without asking them for permission or removing their code. Since the license for their contributions is the same as the license for the project, no commercial use would be possible until done so.

**Comment by Blueforcer** [comment]
I can ask them, no problem.
Then I will add the CLA

**Comment by Blueforcer** [comment]
commercial note removed
