### ISSUE TITLE
Pause auto transition when the screen is off

### ISSUE THREAD

**Issue by wilfredktlr** [Blueforcer/awtrix-light#330]
# Feature Request

### Is your feature request related to a problem?

When transitioning is enabled and the screen is turned off it still cycles through the apps. This causes unnecessary MQTT messages (and uses CPU cycles, power usage).

### Describe the solution / feature you'd like

Always pause transitioning when the screen is off regardless of the auto transition setting.

### Describe alternatives you've considered

Creating an automation to turn off transitioning when the screen is off. But this is more complex because you have to store the previous state before the screen was turned off to restore it to the previous setting when it's turned back on.

### Additional context

N/A

**Comment by Blueforcer** [comment]
You're switching the matrix off, nothing else.
It makes no difference in power usage or CPU cycles because the rendering is still running even without transition.
Many users plays with the app and Liveview even the matrix is turned off.
