### ISSUE TITLE
[BUG] Rendering issues with some icons with "moving" elements

### ISSUE THREAD

**Issue by ejalal** [Blueforcer/awtrix-light#331]
# Bug report

## Describe the bug

Some animated icons from lametric official site have rendering issues

Icon codes
2286 
2283
2282

## Additional information

- Devices involved:
  - Model: Ulanzi Awtrix Smart Pixel Clock 2882 (TC001)
  - AWTRIX-LIGHT version: [ eg. v0.88 ]

## To Reproduce

Create any app with one of these icons, my weather app has a dynamic icon (icon code is a HA sensor based on current condition)

## Screenshots

![Media_230921_210414](https://github.com/Blueforcer/awtrix-light/assets/19426471/36411b11-df2b-4d50-a1ea-6c2ccb4764dc)

## Logs

```text
```

**Comment by Blueforcer** [comment]
Awtrix cant handle every type of compressed gifs.
Use a online converter to uncompress it:
https://ezgif.com/maker
