### ISSUE TITLE
[BUG] Lametric icon download broken for jpg

### ISSUE THREAD

**Issue by TheGroundZero** [Blueforcer/awtrix-light#332]
# Bug report

## Describe the bug

JPG (static) icons downloaded via the download functionality on the device appears to be broken.
Downloading GIFs works fine.

I did notice that the preview of the icon (which does function) displays a PNG, so perhaps there's a conversion error occurring?
**EDIT** Renaming the icon file from `name.jpg` to `name.png` makes it "function" again in the File Editor. This appears to confirm my suspicion. However, it won't work on the device as it requires a JPG file.

## To Reproduce

- Preview a static icon from Lametric, e.g. `32047`, notice that it appears correctly
- Download this icon
- Check the icon in the File Manager, notice how the icon is broken
- Use the icon in a custom app, e.g. `{ "text": "test", "icon": "32047"}`, notice how it appears the same (broken) on the device

## Expected behavior

- Download a static icon and have it appears correctly

## Screenshots

![image](https://github.com/Blueforcer/awtrix-light/assets/2406013/2d7bbdd4-6083-4870-815d-28d7d3e5b49f)
![image](https://github.com/Blueforcer/awtrix-light/assets/2406013/eb6ad34f-ea22-4903-ba29-8ec73e1fc739)

**Comment by Blueforcer** [comment]
It's just a regular download of the file. No converting happening

**Comment by TheGroundZero** [comment]
> It's just a regular download of the file. No converting happening

Could it be that it's downloading a PNG but storing as a JPG?
The preview on the web interface is a PNG file. Also, renaming one of the broken jpg's to png does "fix" it in the file browser.

**Comment by TheGroundZero** [comment]
I've used the preview feature to download the PNG of each icon, then used PaintDotNet to convert them into JPG.
Also renamed them for my own clarity.

For some reason, I'm not getting an icon on my device when I'm calling for a JPG icon. GIF icons work fine.
Text and progress bar display fine. Text is moved to the right to make room for an icon. But icon is black.

![image](https://github.com/Blueforcer/awtrix-light/assets/2406013/b2cf278b-200a-4f5e-9616-d9c386b97efe)
![image](https://github.com/Blueforcer/awtrix-light/assets/2406013/77813725-ebed-4d83-8f1f-f540a30001f8)

Calling for a GIF icon works fine
![image](https://github.com/Blueforcer/awtrix-light/assets/2406013/8911994d-32c1-42bc-ab8b-e53aaf4bd2d7)

**Comment by Blueforcer** [comment]
Does it have s resolution of 8x8?

**Comment by TheGroundZero** [comment]
> Does it have s resolution of 8x8?

Yes. It's the PNG I downloaded from the preview and converted into JPG
![image](https://github.com/Blueforcer/awtrix-light/assets/2406013/827b13e9-16ad-496d-aa86-0e9a71549a49)

bat_dch_100.jpg
![bat_dch_100](https://github.com/Blueforcer/awtrix-light/assets/2406013/246483e9-a3a5-4743-8d8d-6187dc7235da)

bat_stb_full.gif
![bat_stb_full](https://github.com/Blueforcer/awtrix-light/assets/2406013/36b18631-ba8f-44c9-8ccb-a79c78869e21)

**Comment by Blueforcer** [comment]
just tested it with 32047 and it works. preview in filemanager ist correct, also on matrix
