### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by 10der** [Blueforcer/awtrix-light#337]
# Bug report

## Describe the bug
switch not is case-sensitive

## Additional information

- Devices involved:
  - Model: Ulanzi Awtrix Smart Pixel Clock 2882 (TC001)
  - AWTRIX-LIGHT version: 0.88 

## To Reproduce

Steps to reproduce the behaviour:

rtfm `{"name":"time"}`
![image](https://github.com/Blueforcer/awtrix-light/assets/7056498/0fc7a972-3137-40ae-ab33-2f76e715da8a)

- send to mqtt
- nothing
change 
`{"name":"Time"}`
now all ok

## Expected behaviour
idk how right :-) 
please fix or code or rtfm =) 

## Logs

```text
(optional) Add relevant logs which could help tackle the problem.
```

**Comment by Blueforcer** [comment]
I'm not sure what's the big here?

**Comment by zzarne** [comment]
I've stumbled there as well when I was reading the API documentation. The example for /switch has "time" as an example while further on the built-in names are "Time", "Date" and so on. "time" != "Time". I agree that this is mislabeled as a bug, but the documentation could me more precise and state which topics and payloads are case sensitive and which aren't.

**Comment by Blueforcer** [comment]
Thats just an example. Customapps can be whatever you like
The names of the build-.in apps are listed below (see your own screenshot)
