### ISSUE TITLE
[BUG] Dots seperator of time stoped blinking

### ISSUE THREAD

**Issue by MHPtweidinger** [Blueforcer/awtrix-light#339]
# Bug report

Dots of the clock app don't flash after changing the config with MQTT.

## Describe the bug

The dots separator between hours and minutes of the default clock app used to blink. Today i submitted a MQTT config to adjust the color and brights and played around with the formatting of the clock app and as i published my first config the dots stopped flashing. I looked in the docu but could not find a property to turn the flashing back on. 

## Additional information

- Devices involved:
  - Model: Ulanzi Awtrix Smart Pixel Clock 2882 (TC001)
  - AWTRIX-LIGHT version: [ eg. v0.45 ]

**Comment by Blueforcer** [comment]
What is your current timefomat

**Comment by MHPtweidinger** [comment]
i set it to: 
`"TFORMAT":"%H:%M",
`

**Comment by Blueforcer** [comment]
Replace : with a space

**Comment by Blueforcer** [comment]
See documentation:
![Screenshot_20230929_150915_Edge.png](https://github.com/Blueforcer/awtrix-light/assets/31169771/799c39bf-959f-4e00-a74c-53926c790101)
