### ISSUE TITLE
[BUG] Error when trying to flash my Ulanzi clock: "Failed to initialize."

### ISSUE THREAD

**Issue by Jonas-Sander** [Blueforcer/awtrix-light#341]
# Bug report
I'm trying to flash my lanzi TC001 Smart Pixel Uhr 2882 via https://blueforcer.github.io/awtrix-light/#/flasher.  
This error occures: 

![grafik](https://github.com/Blueforcer/awtrix-light/assets/29028262/74c43e31-786b-4754-962c-8acd07fbc13e)

I'm using a windows pc and tried it with:
* Edge: Version 117.0.2045.47 (Offizielles Build) (64-Bit)
* Chrome: Version 117.0.5938.92 (Offizieller Build) (64-Bit)

I already tried to reset my ULANZI clock via "Logs & console" > "Reset device" and by pressing the reset button at the back of the device. Nothing helped.

When I press "Install" the device beeps and turns off for a brief moment but after that it turns back on and nothing changed.

## Additional information

- Devices involved:
  - Model: Ulanzi Awtrix Smart Pixel Clock 2882 (TC001)

## To Reproduce

1. Connect the ULANZI pixel clock via USB to my PC
2. Try using the flashing tool at https://blueforcer.github.io/awtrix-light/#/flasher (+ check erase device button)

## Expected behavior

The device should be flashed.

## Screenshots

https://github.com/Blueforcer/awtrix-light/assets/29028262/45ff7e26-b2fd-4c5d-95dc-50ef2e4a85b5

## Logs

```text
----------------BOOTING INFO----------------
------ESP SDK Version : v3.3.5-1-g85c43024c
------Dot2d Version : dot2d-0.1.0
------Firmware Version : 1.7.3.385ae1
------SPIFFS File System init succeed.
------Global Device Data init succeed.
------Global Config Data init succeed.
------Global User Data init succeed.
------Global App Switch Data init succeed.
------Global System Data init succeed.
------Dot2d Director init succeed.
------Screen And Canvas init succeed.
------App Manager init succeed.
------Device init succeed.
```

```
connect-221663ff.js:485 Initializing Improv Serial
connect-221663ff.js:810  Improv initialization failed. Error: Improv Wi-Fi Serial not detected
    at connect-221663ff.js:485:1200
_initialize @ connect-221663ff.js:810
await in _initialize (asynchron)
firstUpdated @ connect-221663ff.js:810
_$AE @ connect-221663ff.js:1
performUpdate @ connect-221663ff.js:1
scheduleUpdate @ connect-221663ff.js:1
_$E_ @ connect-221663ff.js:1
await in _$E_ (asynchron)
requestUpdate @ connect-221663ff.js:1
o @ connect-221663ff.js:1
de @ connect-221663ff.js:1
ce @ connect-221663ff.js:1
ba @ connect-221663ff.js:512
_a @ connect-221663ff.js:867
await in _a (asynchron)
(anonymous) @ install-button.js:1
connect-221663ff.js:485 Try hard reset.
connect-221663ff.js:485  Error: Couldn't sync to ESP. Try resetting.
    at pa.sync (connect-221663ff.js:485:58250)
    at async pa.initialize (connect-221663ff.js:485:53144)
    at async connect-221663ff.js:485:65392
```

**Comment by Jonas-Sander** [comment]
Okay, I solved by connecting to the Ulanzi clock via the IP address shown on the device, then tapping "About" (the button at the very bottom of the page), selecting update firmware, and choosing "ulanzi_TC001_0.88.bin" that is at the "releases" tab here on GitHub. Since I already added the wifi before updating the clock it connected directly to my wifi after flashing it with the AWTRIX firmware.

**Comment by Jonas-Sander** [comment]
This process is not documented though and the original way (the quickstart at https://blueforcer.github.io/awtrix-light/#/quickstart) didn't work for me.

**Comment by Blueforcer** [comment]
You need to use a high quality cable and probably another USB port. The ulanzi hardware is bad.
But glad it works now.

**Comment by Jonas-Sander** [comment]
> You need to use a high quality cable and probably another USB port. The ulanzi hardware is bad.
But glad it works now.

I tried it with 2 other USB cables and 2 more USB ports, still didn't work :/

**Comment by Blueforcer** [comment]
Sorry there is nothing I can do.
Some users reported that it works on another PC for any reason.

**Comment by Jonas-Sander** [comment]
No worries, thanks for your help :)   

There is one thing that was annoying though because of this issue: When I had issues with the IP settings (I changed something and couldn't connect to the web interface afterwards) I had troubles resetting the device. The reset button at the back of the device didn't function properly. If you press it nothing happens. I tried pressing, holding, turning the device on and off several times etc. and it didn't work. After a while I got lucky and it somehow went back to the access point mode. I think it was when pressing the reset button while the device is booting up? I tried to reset it again afterwards once and it didn't work. Is there a special way or time when the reset button has to be pressed?

**Comment by pzzz** [comment]
> Okay, I solved by connecting to the Ulanzi clock via the IP address shown on the device, then tapping "About" (the button at the very bottom of the page), selecting update firmware, and choosing "ulanzi_TC001_0.88.bin" that is at the "releases" tab here on GitHub. Since I already added the wifi before updating the clock it connected directly to my wifi after flashing it with the AWTRIX firmware.

Can confirm, this also was the way to go for me (y)

**Comment by GitGudin** [comment]
> Okay, I solved by connecting to the Ulanzi clock via the IP address shown on the device, then tapping "About" (the button at the very bottom of the page), selecting update firmware, and choosing "ulanzi_TC001_0.88.bin" that is at the "releases" tab here on GitHub. Since I already added the wifi before updating the clock it connected directly to my wifi after flashing it with the AWTRIX firmware.

Worked for me, too. Thanks for sharing!

**Comment by runrennerrun** [comment]
> > Okay, I solved by connecting to the Ulanzi clock via the IP address shown on the device, then tapping "About" (the button at the very bottom of the page), selecting update firmware, and choosing "ulanzi_TC001_0.88.bin" that is at the "releases" tab here on GitHub. Since I already added the wifi before updating the clock it connected directly to my wifi after flashing it with the AWTRIX firmware.
> 
> Worked for me, too. Thanks for sharing!

Hi, I can't find the  releases tab where the "ulanzi_TC001_0.88.bin" should be. where do i find that?

**Comment by coalfield** [comment]
Thank you, really helped me after trying numerous cables!

**Comment by wAuner** [comment]
I can confirm that using a better cable helped. When I switched to a very short (about 50cm) Thunderbolt 4 cable I was able to successfully flash the firmware with my Macbook.

**Comment by mbnn6** [comment]
I would like to confirm that changing the cable helped! It's because of the way the clock will connect to your mac, choosing serial connection as the connection method (important to make it work, don't choose bluetooth) was only possible then.

**Comment by SimonKai22** [comment]
> ulanzi_TC001_0.88.bin

I have the same problem. Can you tell me where I can find the file "ulanzi_TC001_0.88.bin"?

many thanks for the help

**Comment by Blueforcer** [comment]
> Many thanks for the link. If I have managed to install this version on the Ulanzi, what do I have to do afterwards?

What do you mean? I think there must be a reason why you're flashing awtrix.
You should read the documentation for further steps

**Comment by SimonKai22** [comment]
oh ok, I think I misunderstood that. Is "ulanzi_TC001_0.88.bin" the same version as the one via the web flasher?

**Comment by SimonKai22** [comment]
That worked! Thank you
How do I switch off the temperature and humidity display? Unfortunately I don't understand the instructions

**Comment by noizee2k** [comment]
Yep. It worked that way, had the same problems on my mac. Already bought your app, worth the money!

**Comment by MeisterPiffer** [comment]
I just want to add that I had the same issue.
I even flashed the firmware via commandline esptool, but even though reporting success, it didn't came up again.
However I was able to reflash the original firmware and use the about->update method to flash the very same file I tried before and this worked.
I feel like there should be a hint to this procedure as alternative to the Online Flasher, as I tested several combinations including 3x USB A to C cables, 3x USB C to C cables, 2x Linux computers, one Windows Laptop and 2 TC001 without success.

**Comment by Jonas-Sander** [comment]
I also think this should be highlighted / documented on the [flasher](https://blueforcer.github.io/awtrix3/#/flasher) site.

**Comment by PtiDam27** [comment]
> Okay, I solved by connecting to the Ulanzi clock via the IP address shown on the device, then tapping "About" (the button at the very bottom of the page), selecting update firmware, and choosing "ulanzi_TC001_0.88.bin" that is at the "releases" tab here on GitHub. Since I already added the wifi before updating the clock it connected directly to my wifi after flashing it with the AWTRIX firmware.

this work for me too big thank i try a lot solution i found on internet this solution only work and is so easy

**Comment by Blueforcer** [comment]
Flashing without changing the partitions, will results in less free Flash space. Sou you have less space available for Icons etc.

**Comment by derdritte** [comment]
I also cannot use the online flasher (ubuntu 22.04, chrome 124.0.6367.91). For safety I wanted to read/dump the base-firmware first using esptools, which initially also failed. Only after I removed all baud-settings, and dumped using `esptool.py -c esp32 -p /dev/ttyUSB0 read_flash 0x0 0x400000 ulanzi_tc001_factory.bin` would it work.

I only tried on the one PC so far, but I tried 3 cables, including a usb-c/usb-c one none of which worked for the online flasher, but did work with esptools.

My ulanzi just reset at the very beginning of the flashing-process (showing the logo in red again) and then just acted like it was reset. I would love a second route using locally installed esptools (in addition to the built-in online flashing, which other users already mentioned).

**Comment by Raudi1** [comment]
I had the same issue. Tried all kinds of different cables (C to C, A to C, USB 2/3, short, long...) on different ports connected to different controllers on my computer (has no USB2 though).
What worked for me immediately was to connect through the USB3 hub built into my monitor.

**Comment by Blueforcer** [comment]
> What worked in my case was to flash the firmware through the built-in webinterface of the clock. The online-flasher just didn't come through on my computer.

You will loose lots of flashmemory with this method, becaue ulanzi use a different partition table.

**Comment by dhuddle** [comment]
> I also think this should be highlighted / documented on the [flasher](https://blueforcer.github.io/awtrix3/#/flasher) site.

This bug report and resolution helped me with my issue. 4 different USB cables, 5 different computer ports, 2 different browsers (chrome and edge)  and no luck. Once I went to the ulanzi stock firmware update and hit enter, it was cake.

It should at least be documented on the official flasher site as an alternative method.

**Comment by overtesters** [comment]
> I had the same issue, different USB cables und ports didn't work.
> 
> What worked in my case was to flash the firmware through the built-in webinterface of the clock. The online-flasher just didn't come through on my computer.

A little update to my original post: After Blueforcer's Post I continued to try getting Awtrix 3 on my Ulanzi with the online Flasher. Installing through my Ubuntu PC didn't work either. In the End it worked with a Barebone PC where a minimal Installation of Windows 10 was running. Took about 2 minutes, only strange thing was that the Ulanzi was beeping through the whole update process. Aside from that, it worked liked described in the online manual.

**Comment by Blueforcer** [comment]
Beeping while flashing is normal because it's a active low buzzer.

**Comment by iamjackg** [comment]
Just wanted to add that I was running into the same issue, but flashing locally with esptool following the instructions at https://github.com/Blueforcer/awtrix3/blob/main/docs/ulanzi_flasher/firmware/README worked fine.

**Comment by shinz41** [comment]
On linux,  you might need permissions to access a device/port :
sudo setfacl -m u:USERNAME:rw /dev/ttyUSB0
Where your session account name should replace USERNAME (of course...)

**Comment by Olli2k** [comment]
0Same Issue here. Depends on the USB3 technology of "modern" PC. Using a USB Hub with 2.0 Standard solved this for me. Should work for everyone else. Tested it on all PCs and with all cables I used before. All were working with the USB Hub.

**Comment by dmxtoxlr** [comment]
> 0Same Issue here. Depends on the USB3 technology of "modern" PC. Using a USB Hub with 2.0 Standard solved this for me. Should work for everyone else. Tested it on all PCs and with all cables I used before. All were working with the USB Hub.
> 
> €dit: All tests were done with a already flashed awtrix3 (0.96) via webinterface.

Thanks so much for this hint! Since aparently we don't have any PCs with USB2.0 ports anymore, I ended up trying with an old raspberry pi3. Worked perfectly fine with (with the chromium browser) on the first try :)
Maybe you could add this information to the quick start guide?

**Comment by gfx54** [comment]
The solution provided up (upgrading using the "About" button + firmware ulanzi_TC001_0.98.bin  worked well on my Ulanzi (bought in July 25).

**Comment by Blueforcer** [comment]
> The solution provided up (upgrading using the "About" button + firmware ulanzi_TC001_0.98.bin  worked well on my Ulanzi (bought in July 25).

Please note, with this solution you just have 250kb of free flash instead of 1,35MB

**Comment by cooper2k4** [comment]
Using an USB 2.0 Port instead of 3.0 solved that issue for me.

**Comment by jerconnect** [comment]
Same for me too, impossible to flash with the cable. Forced to download the Firmware and go through About and update with the ".bin" file

**Comment by dimangi** [comment]
Tried 6 different cables, different ports, Windows and Mac devices, no luck. Also tried to flash tasmota via About as it would provide a path to repartition. Also no luck.

**Comment by wassim-bejaoui** [comment]
Hello! 

I had the same issue with my new clock—the flashing process wasn’t working. 

After troubleshooting in my homelab, I found that my **firewall was blocking outbound traffic on ports 5228 and 8443**. Once I temporarily allowed those ports, the Blueforcer Flasher worked perfectly.

Don’t forget to remove the firewall rule after flashing for better security.

Hope this helps others running into the same problem!

**Comment by Nemeczek** [comment]
I read somewhere that if you have it error then try USB 2.0 port. And it worked!

**Comment by rok8ray** [comment]
Hey, i'm having this same error. Could someone please give me the link to the releases tab you speak of? Thanks
