### ISSUE TITLE
[BUG] temp_dec_places in mqtt message _tmp

### ISSUE THREAD

**Issue by martin131** [Blueforcer/awtrix-light#345]
# Bug report

## Describe the bug

temp_dec_places is not reflected in _tmp message in mqtt

## Additional information

- Devices involved:
  - Model: ULANZI with DIY ESP32
  - AWTRIX-LIGHT version: 0.88

## Expected behavior

_tmp value should be same as temp value in stats

## Screenshots

![image](https://github.com/Blueforcer/awtrix-light/assets/4062374/252795fe-26c4-4822-be69-7fa648b929c8)

**Comment by Gerrit-KMeier** [comment]
The temperaturesensor in the device is quite inaccurate. So do you utilize it somewhere ?

**Comment by martin131** [comment]
@Gerrit-KMeier I am using DIY ESP32 setup with external connected SHT31 sensor. Now it is very accurate.

**Comment by martin131** [comment]
thank you :-)
