### ISSUE TITLE
[FEATURE REQUEST] Reduce energy consume, in the night , via brightness sensor

### ISSUE THREAD

**Issue by mklossde** [Blueforcer/awtrix-light#346]
# Feature Request

Add option to automatic turn off matrix display when brightness is below minimum, to reduce energy consume. 

### Is your feature request related to a problem?

It depends if energy consume is defined as a problem ;-)

### Describe the solution / feature you'd like

I think most of the energy consume of the device  is used for the matrix display and the wifi connection. 
Maybe this is a way, for some usecases, to reduce this energy consume when is is not need. 

To automatic reduce energy consume, without manuel processs, the idee is to automaticly detect the timeslot when the 
device is not use by a person, with its own sensors. 
For Example, in some case the device is placed in a room, where nobody is inside at night and the night is maybe detected by the brightness sensor. 

There is alrady a automatic brightness feature  with a minimum level switch, the matrix is not dim below this minum value. 

The feature request is to add a new option "automatic power on/off" when the brightness sensor goews below the selected minimum and switch automaticly the matrix on, when the brightness sensor detect a value obove the minimum. 

### Describe alternatives you've considered

It possible to switch the matrix display on and off via mqtt (e.g. a rule in Home-Assistant), wich also depends on the brightness level.

**Comment by Blueforcer** [comment]
This is a very special request. The problem here is that everyone has a different idea of it. Therefore, you get all the tools at hand via API to implement it exactly according to your wishes. You can read the brightness and you can switch the matrix on and off. AWTRIX should have as little intelligence of its own as possible
