### ISSUE TITLE
When sending Post for custom app, an effect is set

### ISSUE THREAD

**Issue by SKB-CGN** [Blueforcer/awtrix-light#349]
Hi,
I am sending apps to the clock via Post. This was working well. Today I updated the clock and now there is some effect behind my text, which I do not want.

The effect value is set to empty or 'None' but displays a color waving background.

How can I have the behaviour like before?
How do I unset the background effect?

'none', 'None', false are not working.

Thank you!

**Comment by Blueforcer** [comment]
If you don't need aneffect, don't send the key "effect". A effect "none" doesn't exist and awtrix uses the first one

**Comment by SKB-CGN** [comment]
Before I sent empty key effect, which was working fine. Means, if no key effect ist sent, the effect will not displayed?

**Comment by Blueforcer** [comment]
But this has changed. Why you send a empty value if you don't use it?

**Comment by SKB-CGN** [comment]
I create the apps dynamically - therefore the key exists and got a value or was set to empty. I will need to change that.

Thanks.

**Comment by Blueforcer** [comment]
I will see if I can do another solution..

**Comment by SKB-CGN** [comment]
Thanks a lot!

**Comment by SKB-CGN** [comment]
Did you change it back again that if effect is empty, that the effect is not applied?

Just to be sure, because I installed the new version and the effect is gone 👍
