### ISSUE TITLE
[BUG] Fixed IP config not working?

### ISSUE THREAD

**Issue by DJF3** [Blueforcer/awtrix-light#352]
# Bug report

## Describe the bug

v0.88 - after configuring Static IP under "Network", the clock doesn't use a static IP. It only listens to my DHCP server.
Configured: local IP, gateway, subnet (255,255,255,0) and primary DNS (also a local device).

## Additional information

- Devices involved:
  - Model: Ulanzi Awtrix Smart Pixel Clock 2882 (TC001)
  - AWTRIX-LIGHT version: [0.88]

## To Reproduce

- in a terminal window (or equivalent) ping the current clock IP "ping 192.168.4.118 -a" (-a = beep on success)
- Enable Static IP (toggle goes green)
- Configure a NEW static IP address
- click "Save configuration"
- click "Restart ESP"

## Expected behavior
The ping should stop beeping because the clock has a new (fixed) IP address. Instead it doesn't.

Manually powering off/on the clock doesn't make a change either.

**Comment by Blueforcer** [comment]
im using it since beginning, and it works as it should.
![image](https://github.com/Blueforcer/awtrix-light/assets/31169771/c355bbdd-8fea-4eee-a14e-d1c12ca4aca0)

**Comment by tebra-jl** [comment]
I have the same bug on same hardware with firmware 0.90

**Comment by tebra-jl** [comment]
It works now after define also a secondary DNS and a reboot.
Thanks for this great software.
