### ISSUE TITLE
[BUG] My clock native app not conect to ntp servers

### ISSUE THREAD

**Issue by Laserm4n** [Blueforcer/awtrix-light#355]
Hello everyone! Since today I have a problem with my awtrix light, after updating to 0.90 my native clock application does not work well and the time and date reset, I tried to change the ntp server and use another one but it still does not work. Does anyone know something about this?

- Devices involved:
  - Model: Ulanzi Awtrix Smart Pixel Clock 2882 (TC001)
  - AWTRIX-LIGHT version: [ eg. v0.90 ]

**Comment by Blueforcer** [comment]
So far, there is no similar report. here, everything runs as before.
maybe awtrix have no internet connection?
