### ISSUE TITLE
[BUG] Another transition glitch

### ISSUE THREAD

**Issue by TheGoblinHero** [Blueforcer/awtrix-light#356]
# Bug report

## Describe the bug

I'm developing my own weather app and found another transition glitch. Here's a video to illustrate the problem.
[https://drive.google.com/file/d/1IFTi1EPxoXv7dNxDYxlaZizz4O-yR1Ql/view](https://drive.google.com/file/d/1IFTi1EPxoXv7dNxDYxlaZizz4O-yR1Ql/view)
Dark blue line at the bottom does not transition as expected. And I think I know there the problem is. Dark blue line (glitched) is drawed using the "db" command. The line above it (normal transition) is drawed using the bunch of "dp" commands.
Here's a JSON of my app if needed:
`{"draw":[{"dp":[8,6,"#31C5BB"]},{"dp":[9,6,"#31C4BE"]},{"dp":[10,6,"#31C0C7"]},{"dp":[11,6,"#31BDCF"]},{"dp":[12,6,"#31B5D9"]},{"dp":[13,6,"#32B0D7"]},{"dp":[14,6,"#31B9D6"]},{"dp":[15,6,"#31B3D8"]},{"dp":[16,6,"#31B3D8"]},{"dp":[17,6,"#31B5D9"]},{"dp":[18,6,"#3E8893"]},{"dp":[19,6,"#32B0D7"]},{"dp":[20,6,"#34A7D2"]},{"dp":[21,6,"#35A2D0"]},{"dp":[22,6,"#369BCD"]},{"dp":[23,6,"#3799CC"]},{"dp":[24,6,"#398BC5"]},{"dp":[25,6,"#3894C9"]},{"dp":[26,6,"#3E8893"]},{"dp":[27,6,"#31BECC"]},{"dp":[28,6,"#31C1C5"]},{"dp":[29,6,"#31C5BD"]},{"dp":[30,6,"#31CAB0"]},{"dp":[31,6,"#31CAB1"]},{"db":[8,7,24,1,["65824","65824","65824","65824","65824","65824","65824","65824","65824","65824","65824","65824","65824","65824","65824","65824","65824","65824","65824","65824","65824","65824","65824","65799"]]},{"dt":[14.0,0,"6.5°","#31C5BD"]}],"icon":"w_partlycloudy","duration":4,"pushIcon":2,"lifetime":120}`

## Additional information

- Devices involved:
  - Model: Ulanzi Awtrix Smart Pixel Clock 2882 (TC001)
  - AWTRIX-LIGHT version:  v0.90 ]

**Comment by Blueforcer** [comment]
fixed
[commercially](https://github.com/Blueforcer/awtrix-light/releases/tag/0.92)
