### ISSUE TITLE
[FEATURE REQUEST] App: Playground option für Progres

### ISSUE THREAD

**Issue by Dtrieb** [Blueforcer/awtrix-light#358]
Hätte einen kleinen Wunsch für die App: könntest du da noch die Option für Progres an/aus im Playground machen? (Ich weiß das ich den Code per Hand löschen kann)

**Comment by Blueforcer** [comment]
Das ist doch bereits seit drin?

**Comment by Dtrieb** [comment]
Ja jetzt ja 👍
