### ISSUE TITLE
[BUG] Distorted Icons sometimes

### ISSUE THREAD

**Issue by ict** [Blueforcer/awtrix-light#359]
# Bug report

## Describe the bug

Certain animated icons seem to be rendered wrongly on certain frames of the animation.
A good example is icon 53384 from LaMetric (a moving cloud), which partly looks normal as in the preview, but party has an inverted outline.

## Additional information

- Devices involved:
  - Model: Ulanzi Awtrix Smart Pixel Clock 2882 (TC001)
  - AWTRIX-LIGHT version: [ eg. v0.90 ]

## To Reproduce

Create and publish any custom app with icon 
`{ "icon": "53384" }`

## Expected behavior

The cloud is animated normally as in the preview

## Screenshots
Normal render: 
![grafik](https://github.com/Blueforcer/awtrix-light/assets/488575/a2f2ceb8-a9a1-4005-8384-f0a9cbe59c67)
Distorted frame:
![grafik](https://github.com/Blueforcer/awtrix-light/assets/488575/3156839f-bd63-483b-8f1b-10ed8ffb0130)

**Comment by Blueforcer** [comment]
https://github.com/Blueforcer/awtrix-light/issues/331
