### ISSUE TITLE
Remove buttons from live view?

### ISSUE THREAD

**Issue by mcrummett** [Blueforcer/awtrix-light#363]
Is there a way for me to remove the buttons from below the live view of the clock?  I'm trying to integrate the clock into my Home Assistant dashboard via iframe but without the buttons.

**Comment by Blueforcer** [comment]
No. Maybe you can inject you own CSS to hide this buttons or you
Check documentation. There is also a Fullscreen endpoint .

On my discord server you also find a integration for this.

**Comment by mcrummett** [comment]
Cheers! An integration for Home Assistant or similar?

I've joined the discord but I must admit even working in IT for the last 17 years I am a newbie to discord!
