### ISSUE TITLE
[QUESTION] sync multiple (TC001) devices

### ISSUE THREAD

**Issue by rwesterflan** [Blueforcer/awtrix-light#364]
Hi!

I've been using your wonderful tool for a while now, and decided to buy two more TC001's for different parts of the house.
Is there a way I could push a notification to all of them from Home Assistant, without writing the same mqtt.publish multiple times?
Maybe subscribe them to the same topic somehow?

Thank you!

**Comment by Blueforcer** [comment]
You can use the clients key for notifications.

**Comment by rwesterflan** [comment]
That was fast :D You're right, sorry I missed that one in the docs. Got it to work that way. Thank you so much!
