### ISSUE TITLE
[FEATURE REQUEST] Home Assistant Voice Satellite

### ISSUE THREAD

**Issue by ThePituLegend** [Blueforcer/awtrix-light#367]
# Feature Request

### Is your feature request related to a problem?

Nope

### Describe the solution / feature you'd like

Since the project is geared towards smarthome setups, and being ESP32-based, I think that adding the possibility of becoming a HA Voice Satellite (adding the extra microphone component, of course) flows naturally. 

To be honest, I don't know if it is possible, or if it is something that diverges from the project's roadmap or intentions. 

However, if possible, I think it would be an invaluable addition to the project. 
It allows whoever wants to have both an awtrix-light and a HA-VoiceSat to spare the extra device. And it gives awtrix-light the "Amazon Echo Show" vibe 

### Additional context

https://www.home-assistant.io/blog/2023/10/12/year-of-the-voice-chapter-4-wakewords/#turn-any-esp32-into-a-voice-satellite-using-esphome

**Comment by Blueforcer** [comment]
There is not enough free RAM for such features. Sorry.
