### ISSUE TITLE
[BUG]MQTT setting cannot display normally

### ISSUE THREAD

**Issue by ken8303** [Blueforcer/awtrix-light#368]
Sorry seem that when I click MQTT page, I only able to change the Broker IP , other settings is missed. Thanks
![Screenshot 2023-10-27 at 10 02 01](https://github.com/Blueforcer/awtrix-light/assets/79350555/6a82b643-56f9-4e60-b11a-3af1d4c5c9d7)

**Comment by Blueforcer** [comment]
Delete the DoNotTouch.json from Filemanager and reboot awtrix.

**Comment by ken8303** [comment]
Thanks so muchˆˆ
