### ISSUE TITLE
[FEATURE REQUEST] Set offset for temperature sensor

### ISSUE THREAD

**Issue by PV-Joe** [Blueforcer/awtrix-light#370]
The integrated temperature sensor of the Ulanzi TC001 reports much to high values.

I wonder if it is possible to set an offset value to make it useful.

in my case the sensor measures 6-7 centigrade on top of the actual temperature.

**Comment by Blueforcer** [comment]
Yes.
https://blueforcer.github.io/awtrix-light/#/dev

But keep in mind the sensor reading will be always off, because the matrix heat up the case depending on what is currently displayed and brightness.
