### ISSUE TITLE
[FEATURE REQUEST] Disable Calendar in time app

### ISSUE THREAD

**Issue by nightshifty** [Blueforcer/awtrix-light#372]
# Feature Request

### Is your feature request related to a problem?
No

### Describe the solution / feature you'd like

I want to have a setting to disable the calendar in the time app. I did not find one in the documentation.
The only way to achieve this right now is to set the color to black. But I would like to have the time placed in center when the calendar is disabled.

**Comment by Blueforcer** [comment]
Change Timemode
