### ISSUE TITLE
[FEATURE REQUEST] - Transistion Effect as APP/NOTIFICATION property

### ISSUE THREAD

**Issue by Bitfummler** [Blueforcer/awtrix-light#379]
Would be nice to be able to setup a transition effect/time per APP/NOTIFICATION. I would assume everything is already there since is should work like TEFF=0 on global scope. Only the APP/NOTIFICATION specific settings are missing. In the end, the global settings shall be overruled by when APP/NOTIFICATION specific settings have been set.

**Comment by Blueforcer** [comment]
Notifications cant have a transision because its an overlay wich sits on top of the actual apps:
For CustomApps its a bit tricky beacuse awtrix needs to know the next transisiton before the app appears and this is currently not possible due the scaffold
