### ISSUE TITLE
[QUESTION] Memory Leakage issue?

### ISSUE THREAD

**Issue by smarthomejunkie** [Blueforcer/awtrix-light#38]
# Question
If I look at the free ram history of the Ulanzi clock in Home Assistant, I see that the free RAM is slowly diminishing over time.

![Screenshot_1](https://user-images.githubusercontent.com/67226335/229519463-5c31ee6f-0f70-43cc-b2b8-edbe5fe7de0a.png)

I'm not sure if this is related to the way I publish MQTT messages or if something is wrong in the firmware. I created several apps through MQTT in Home Assistant that I show on the Ulanzi Pixel Clock. Every time when a value changes within the app, I publish a new MQTT message (MQTT.publish) to the clock with the same app name. Is this the correct approach?

## Additional information

- Devices involved:
  - Model: Ulanzi Awtrix Smart Pixel Clock 2882 (TC001)
  - AWTRIX-LIGHT version: v0.47

**Comment by smarthomejunkie** [comment]
I monitored this for a while now and it seems that every time when I send an MQTT publish message, the memory gets a bit lower. I'd expect that the memory stays at the same level when you send an MQTT publish message (to the same app).

**Comment by Blueforcer** [comment]
Did you noticed something similar before 0.47?

**Comment by smarthomejunkie** [comment]
I didn't really look into it before, but according to the stats it seems to be a new issue since 0.47

![54702E9C-ED1D-4966-A921-1C2ED6E41D15](https://user-images.githubusercontent.com/67226335/229582320-ac18557e-daaf-461c-9e6d-6e58ca60a454.png)

**Comment by Blueforcer** [comment]
I will have a look at it before next update

**Comment by Blueforcer** [comment]
What happened at the last peak in your history? Restart?

**Comment by smarthomejunkie** [comment]
Yes, it spontanously restarted when I was sending multiple mqtt publish commands.

**Comment by Blueforcer** [comment]
i think i found something. I made a benchmark the last hour at it seems pretty stable at >3000 messages
![image](https://user-images.githubusercontent.com/31169771/229596817-f7a3ab16-e888-43aa-835c-e4efdf7eea68.png)

**Comment by smarthomejunkie** [comment]
That looks promising!

**Comment by Diginix** [comment]
My TC001 freezed today after 2 days running with 0.47. It shows the time with not changing seconds when it happend. It was not reachable over network and no hardware button worked anymore. Only left+right button hold for turning off and on helped.
Where I can monitor the RAM? Didn't found it in stats or webUI.

**Comment by Blueforcer** [comment]
You can find it in Homeassistant sensor. 
But it's already 100% fixed for the next version 

Am Fr, 7. Apr 2023, um 21:14, schrieb Diginix:

**Comment by Diginix** [comment]
I use TC001 with iobroker as mqtt broker. I guess I can't retrieve RAM usage there, but didn't need it.

**Comment by Blueforcer** [comment]
That's true, next version will also send it to /stats. But then ram issue is solved 😄

**Comment by Diginix** [comment]
Today I got again a freezed TC001. I switch every 30 sec from time app to a custom app for 10 sec with outside temperature and dynamic icon related to the current weather. With this frequency it happens at least once per day for me. Would be great to have the bug fix soon. I can also test beta versions if you tell me how to install.

**Comment by Blueforcer** [comment]
You can get the Testversions on my discord server.

**Comment by Diginix** [comment]
In awtrix-light section I see only the forum
![image](https://user-images.githubusercontent.com/39678667/230738237-ef0ca767-a8af-47f3-a338-ebcf2b949081.png)
Could you guide me please where I can download it?

**Comment by Blueforcer** [comment]
Have a look at the dev talk channel. I posted a new version today. You can update it via Webinterface

**Comment by Diginix** [comment]
0.48 found
![image](https://user-images.githubusercontent.com/39678667/230739020-3a497855-54c3-46e7-8830-636bfad40322.png)
