### ISSUE TITLE
[FEATURE REQUEST] - Would be nice to switch to a specific app via API 

### ISSUE THREAD

**Issue by Bitfummler** [Blueforcer/awtrix-light#381]
Maybe I've overlooked something, but I guees, there is no API command available which allows me to switch to specific app when automatic transitions are disabled.

**Comment by Blueforcer** [comment]
https://blueforcer.github.io/awtrix-light/#/api?id=switch-to-specific-app

**Comment by Bitfummler** [comment]
Ups, my fault, sorry for the trouble.
