### ISSUE TITLE
[BUG] Battery charge at 100%

### ISSUE THREAD

**Issue by FeromonDE** [Blueforcer/awtrix-light#387]
# Bug report

## Describe the bug

If the battery charge reaches 100%, the charge changes almost every second in HA. 

## Additional information

- Devices involved:
  - Model: Ulanzi Awtrix Smart Pixel Clock 2882 (TC001)
  - AWTRIX-LIGHT version: [ eg. v0.90 ]

## To Reproduce

Charge to 100%

## Expected behavior

See the battery gradually discharge

## Screenshots

![Screenshot_2023-11-04-13-36-46-569_io homeassistant companion android-edit](https://github.com/Blueforcer/awtrix-light/assets/18047972/b2819292-6622-48c2-80d2-2876c67a1fce)

**Comment by Blueforcer** [comment]
Im not the developer of the hardware 😜
It's not a firmware bug

**Comment by FeromonDE** [comment]
It turns out that the battery charge remains unknown and the device can turn off at any moment?

**Comment by Blueforcer** [comment]
> It turns out that the battery charge remains unknown and the device can turn off at any moment?

Im not sure what you mean.

Kannst auch gern auf deutsch schreiben.

**Comment by FeromonDE** [comment]
I just wanted to monitor the battery charge and at a certain value turn on charging through the smart socket and turn it off at 100%

**Comment by Blueforcer** [comment]
I don't see any problem to archive this.
If percentage > 95% longer than 1min, turn off.

But the cheap battery will die pretty fast if you always push full charging cycles.

**Comment by FeromonDE** [comment]
> I don't see any problem to archive this. If percentage > 95% longer than 1min, turn off.
> 
> But the cheap battery will die pretty fast if you always push full charging cycles.

![Screenshot_2023-11-04-14-32-00-659_io homeassistant companion android-edit](https://github.com/Blueforcer/awtrix-light/assets/18047972/3ae990b4-10d5-4175-9dae-bcebbac369b6)
Ladestand innerhalb von 1.5 Minuten, und so springt die Ladung hier und her fast jede 5 Sekunden.

**Comment by Blueforcer** [comment]
Dann baue eine Mittelung ein wenn dir das zu viel ist und gehe auf 2min Verzögerung.
Die Werte kommen so von der Hardware und werden bereits von der Software geglättet.
Die Batterie und Hardware an sich ist halt Schmutz.
