### ISSUE TITLE
[BUG] after MQTT settings, device Restarts always (0.90)

### ISSUE THREAD

**Issue by Ichda** [Blueforcer/awtrix-light#388]
# Bug report

## Describe the bug
Hello
I installed the Firmware 0.90 and did the MQTT settings. After save and reboot, the Devices restarts in a loop. After deleting the MQTT IP Adress of the broker, the device works fine.
I get the MQTT data in MQTT Broker (ioBroker). So the communication is working, but then the Device reboots.

## Additional information

- Devices involved:
  - Model: Ulanzi Awtrix Smart Pixel Clock 2882 (TC001)
  - AWTRIX-LIGHT version: 0.90
  - MQTT broker: ioBroker.MQTT v5.1.0

## Logs

```text
(optional) Add relevant logs which could help tackle the problem.
```

**Comment by Blueforcer** [comment]
duplicate of https://github.com/Blueforcer/awtrix-light/issues/165
