### ISSUE TITLE
[BUG] Selecting DoNotTouch.json and clicking MkFile erases the file

### ISSUE THREAD

**Issue by jankazemier** [Blueforcer/awtrix-light#389]
1. I clicked on the DoNotTouch.json file (not even wanting to edit it)
2. clicking the file entered the filename into the box 
3. clicking MkFile immediately overwrites the file with an empty file
4. DoNotTouch.json is overwritten without any warning or way to discard changes or to get it back

![image](https://github.com/Blueforcer/awtrix-light/assets/355155/05888d79-e09e-4643-b2ce-79f997408de8)

It would be nice to either get a warning, be able to discard the changes or to restore the file.

(also, can I download a new DoNotTouch.json somewhere? )

**Comment by jankazemier** [comment]
Ok, I managed to restore it by saving the config again using the webinterface. Still, this should not happen :)

**Comment by Blueforcer** [comment]
It's the behavior of the ACE file editor.
It's not made by me, you should open an issue there.

If you delete the JSON, awtrix will generate a new one after reboot.
