### ISSUE TITLE
[QUESTION] Show icon in the time app

### ISSUE THREAD

**Issue by AlexanderGlogger** [Blueforcer/awtrix-light#39]
# Question

Is it possible to show a icon on the left when displaying time like in the temperature app? And is it possible to customise the icons of the default apps?

## Additional information

- Devices involved:
  - Model: Ulanzi Awtrix Smart Pixel Clock 2882 (TC001)
  - AWTRIX-LIGHT version: [ v0.47 ]

**Comment by Blueforcer** [comment]
No
