### ISSUE TITLE
[BUG] Timezone to another location

### ISSUE THREAD

**Issue by shawndamon** [Blueforcer/awtrix-light#392]
# Bug report

## Describe the bug

I cant seem to update the timezone the following is what i have tried:
Asia/Shanghai,CST-8
Asia/Singapore,<+08>-8

- Devices involved:
  - Model: Ulanzi Awtrix Smart Pixel Clock 2882 (TC001)
  - AWTRIX-LIGHT version: [ eg. v0.45 ]

## To Reproduce

[Steps to reproduce the behavior:]

(http://awtrix_efbac8.local/) under time trying to change it

![image](https://github.com/Blueforcer/awtrix-light/assets/31374940/49516acb-6c00-4aad-afea-77145ce5af79)

**Comment by Blueforcer** [comment]
There is a link right here where you can find the setting you need:
![image](https://github.com/Blueforcer/awtrix-light/assets/31169771/f9ca914c-4c5d-43e7-975d-701239e211a9)

So for Shanghai it is **CST-8** and it works

![image](https://github.com/Blueforcer/awtrix-light/assets/31169771/aa7c2de4-0fe3-4b7f-b6e9-8848359b27d1)

**Comment by shawndamon** [comment]
sorry i didnt see you message on Discord sooner...thank you for closing this
