### ISSUE TITLE
extend app display time beyond 30 sec

### ISSUE THREAD

**Issue by LPhilipp2408** [Blueforcer/awtrix-light#393]
The **apptime** (displaytime of the inbuilt apps) can currently be maxed to **30 secs**.
Can this be **extended** either via dev.json or config over the buttons?

**Comment by Blueforcer** [comment]
you can set it via the settings API

**Comment by LPhilipp2408** [comment]
Thanks, didn’t find that in the documentation (which does not mean that it’s not there) Awesome software & thanks for the quick reply Am 12.11.2023 um 13:32 schrieb Stephan ***@***.***>:﻿
you can set it via the settings API
