### ISSUE TITLE
Make draw apps scrolling

### ISSUE THREAD

**Issue by salabim** [Blueforcer/awtrix-light#395]
It would be nice if we could have draw apps, which are wider than 32 pixels could scroll, like other apps.
This is particularly useful for pictures specified as bitmaps.

**Comment by Blueforcer** [comment]
What is a draw app?

**Comment by salabim** [comment]
I mean a custom app which has a key 'draw'.
And for me, the drawing instruction 'db' therein is most interesting.

**Comment by Blueforcer** [comment]
Drawing commands are always static. If you want to move something you need to change the coordinates. 
There will be no way to do this automatically

**Comment by salabim** [comment]
That's a pity.
My use case is a 'long' text, made from another font, that I would like to scroll like a text app. But, ow I can't, as far as I know.
Could you add to the feature request list?

**Comment by Blueforcer** [comment]
It's not that trivial as it sounds.
Awtrix can't count the pixels of each characters if it's just a picture. This is necessary to scroll the text

**Comment by salabim** [comment]
My characters are just an example. 'All' I ask is to scroll the picture one pixel at a time, really like the text app.
But maybe I don't understand the system enough. Anyway, I love awtrix!

**Comment by Blueforcer** [comment]
Just update the position of the picture. Awtrix has no problems in receiving fast app parameter changes.

There will be no Automation in the drawing functions, sorry.

**Comment by salabim** [comment]
Ok.
Thanks.
