### ISSUE TITLE
[FEATURE REQUEST] Instructions to restore original firmware

### ISSUE THREAD

**Issue by Sumidu** [Blueforcer/awtrix-light#400]
# Feature Request

### Is your feature request related to a problem?

No
### Describe the solution / feature you'd like

I would like to have a webflasher for the original firmware! 

### Describe alternatives you've considered

I have tried looking for clear instructions on the web, but they are all fuzzy.

### Additional context

After installing AWTrix Light, I found no way of how to go back to stock.

**Comment by Blueforcer** [comment]
You can find the firmware on their website under "Tips"
https://www.ulanzi.com/products/ulanzi-pixel-smart-clock-2882

**Comment by 2sucres** [comment]
Not enough space when flashing with the web interface from the device

**Comment by Sumidu** [comment]
I found the firmware but no instructions. 🫢

**Comment by Dunkelschunkel** [comment]
I had the same problems. I think I was using a web flasher and only managed to get it up and running after flashing the original firmware twice. Even then it was not reboot safe.

**Comment by Blueforcer** [comment]
![image](https://github.com/Blueforcer/awtrix-light/assets/31169771/9ce8f85f-e8c3-436d-9659-b00c638dc528)
[ulanzi_original_firmware.zip](https://github.com/Blueforcer/awtrix-light/files/13491066/ulanzi_original_firmware.zip)

**Comment by Blueforcer** [comment]
> Sorry to bother again. Is there an equivalent MacOS tool somewhere? 

I don't know, sorry. But I'm pretty sure there are flash tools for Mac available.
