### ISSUE TITLE
ability to rotate the whole display

### ISSUE THREAD

**Issue by timgentschhh** [Blueforcer/awtrix-light#401]
# Feature Request

It would be nice if I could rotate the display for 180 degree , so that I could stick it on the underside of my kitchen cupboard.

**Comment by Blueforcer** [comment]
Already possible:
https://blueforcer.github.io/awtrix-light/#/dev

**Comment by timgentschhh** [comment]
very nice! thank you very much for your quick reply
-----------------------

**Comment by bachoo786** [comment]
@Blueforcer sorry I have just got my ulanzi display and I really need to rotate my screen. I know you have shared the link above but how do I implement it using JSON ? thanks.

**Comment by Blueforcer** [comment]
> @Blueforcer sorry I have just got my ulanzi display and I really need to rotate my screen. I know you have shared the link above but how do I implement it using JSON ? thanks.

Create a dev.json in the Filemanager
And add
{"rotate_screen":true}

**Comment by bachoo786** [comment]
> > @Blueforcer sorry I have just got my ulanzi display and I really need to rotate my screen. I know you have shared the link above but how do I implement it using JSON ? thanks.
> 
> Create a dev.json in the Filemanager And add {"rotate_screen":true}

hey thanks for the reply so I did what you told me to do and restarted the ULANZI display however it has not rotated the screen. Please see below:

![image](https://github.com/Blueforcer/awtrix-light/assets/6251030/6a7d8753-e859-4398-a2be-9a0ad2010f2a)

**Comment by Blueforcer** [comment]
The Filemanager tell you the error in your JSON. There is a leading space marked as a red dot. Remove it.

**Comment by bachoo786** [comment]
> The Filemanager tell you the error in your JSON. There is a leading space marked as a red dot. Remove it.

thanks works perctly
