### ISSUE TITLE
[FEATURE REQUEST] Bluetooth BLE Beacon

### ISSUE THREAD

**Issue by MehrCurry** [Blueforcer/awtrix-light#403]
# Feature Request

It would be nice to enable a BLE beacon on the clock to make it trackable with ESPresense. My usecase is to enable/disable the clock when someone enters the same room the clock is in.

### Describe alternatives you've considered

It would be trivial if the clock is always in the same room and already works for me. But since the clock is portable it would be nice to be able to track it via ESPresense.

**Comment by Blueforcer** [comment]
I tried it some month ago, unfortunately the BLE library consuming too much RAM
