### ISSUE TITLE
How to use the '

### ISSUE THREAD

**Issue by salabim** [Blueforcer/awtrix-light#406]
In the documentation I read
```
This section contains small setting options that the majority of users do not change or change very rarely and therefore saved the effort of creating an elaborate settings interface.

All features are only applied at boot. So you have to restart awtrix after modifying.

Create a dev.json in your filemanager.
```
Is there any possibility of controlling these features from the API (or otherwise from Python)?

**Comment by Blueforcer** [comment]
A bit more words than 4 would be good....

**Comment by salabim** [comment]
In the documentation I read

This section contains small setting options that the majority of users do not change or change very rarely and therefore saved the effort of creating an elaborate settings interface.

All features are only applied at boot. So you have to restart awtrix after modifying.

Create a dev.json in your filemanager.
Is there any possibility of controlling these features from the API (or otherwise from Python)?

**Comment by Blueforcer** [comment]
No it's not controllable from API

**Comment by salabim** [comment]
Thanks for the quick response!
