### ISSUE TITLE
Excuse me for the support request in a bug tracker (no Discord account) - display Bitcoin price

### ISSUE THREAD

**Issue by GETandSELECT** [Blueforcer/awtrix-light#408]
Hi

Sorry for the support request in a bug tracker. Unfortunately I don't have a Discord account for privacy reasons.

I have Awtrix-light installed on my "Ulanzi TC001 Smart Pixel Clock 2882". I even bought the app but it doesn't help me at all, you see the same as on the Web UI).

I don't have a home assistant or any other server. **How can I display the current Bitcoin price? What is the simplest way?**

Somehow I can't get any further, I think it's very simple but I just can't find the right way.

**Comment by Blueforcer** [comment]
You need an external system for that. Awtrix light is not meant to be standalone.

Use a raspberry or anything wich can run 24/7, install nodered and import this flow
https://flows.blueforcer.de/flow/MzB23Oe0orLJ
