### ISSUE TITLE
[FEATURE REQUEST] - Notifications in Cyrillic

### ISSUE THREAD

**Issue by cimburlen** [Blueforcer/awtrix-light#410]
Hello. Is it possible to add the ability to display notifications in Cyrillic in the next firmware. This makes it very difficult to use with Home Assistant. As far as I understand, most of the fonts here support the Cyrillic alphabet.

**Comment by Blueforcer** [comment]
The Awtrix Font doesn't support Cyrillic character.
This would requires to create a new font.
I don't even know if Cyrillic characters would fit in 5 pixel height.

From my side I have no plans to add it. But maybe another user wich has knowledge about that can do this.
Sorry

**Comment by 10der** [comment]
> The Awtrix Font doesn't support Cyrillic character. This would requires to create a new font. I don't even know if Cyrillic characters would fit in 5 pixel height.
> 
> From my side I have no plans to add it. Sorry. But maybe another user wich has knowledge about that can do this.

![telegram-cloud-photo-size-2-5433729041212493884-y](https://github.com/Blueforcer/awtrix-light/assets/7056498/1f4e025c-83d5-4f20-8792-b297889a84cb)

NB:
red right upper it's not artefact, it's mark for red-alert :(
