### ISSUE TITLE
Set WIFI Credentials via USB [FEATURE REQUEST]

### ISSUE THREAD

**Issue by ahk97** [Blueforcer/awtrix-light#414]
I would like to use an TC001/Awtrix in a new location.
It would be nice if its possible to change the WIFI Credentials via the USB Port (serial terminal).
Currently I have to do a full reset of the unit to get it into ap mode again.

Thanks!

**Comment by Blueforcer** [comment]
Why full reset?
You can set the new credentials in the Webinterface at any time.
You can also turn off the current wifi, and awtrix will open the AP mode after reboot.

**Comment by ahk97** [comment]
Ok. I did not know that.
Then it would probably be sufficient to add a note about the WIFI setup features to the docs.
Or: 6 short button presses start the Wifi Manager / AP Mode (like the tasmota devices)
