### ISSUE TITLE
[BUG] Lower left pixel flashes yellow constantly

### ISSUE THREAD

**Issue by bruschhaupt** [Blueforcer/awtrix-light#415]
# Bug report

## Describe the bug

The left lower pixel flashes yellow continuously. I can't overwrite the pixel either. Does anyone know why this is and how I can switch it off? 

WATCH
![Lower left pixel flashes yellow constantly](https://github.com/Blueforcer/awtrix-light/assets/20648677/6c28ef9e-940f-4972-a538-d37e3fd9f762)

## Additional information

- Devices involved:
  - Model: Ulanzi Awtrix Smart Pixel Clock 2882 (TC001)
  - AWTRIX-LIGHT version: 0.90

**Comment by Blueforcer** [comment]
That means you configured a mqtt broker but awtrix can't connect.
Remove the broker host in order to disable it.

**Comment by bruschhaupt** [comment]
Thank you for the quick solution
