### ISSUE TITLE
[FEATURE REQUEST] Allow to adjust volume for DFPlayer

### ISSUE THREAD

**Issue by Lutty76** [Blueforcer/awtrix-light#419]
# Feature Request

### Is your feature request related to a problem?

My problem is that I cannot adjust volume

### Describe the solution / feature you'd like

In global.cpp
you have this 
```
#ifndef ULANZI
    Settings.putUInt("VOL", VOLUME_PERCENT);
```
and this

```
#ifndef ULANZI
    VOLUME_PERCENT = Settings.getUInt("VOL", 50);
    VOLUME = map(VOLUME_PERCENT, 0, 100, 0, 30);
```

but we can't set this setting for api as this variable doesn't exist in DisplayManager.cpp
so you just put default value (50) in setting and reload it

### Describe alternatives you've considered

Just add : 

`  VOLUME_PERCENT = doc.containsKey("VOL") ? doc["VOL"].as<int>() : VOLUME_PERCENT ;`
in  DisplayManager_::setNewSettings
for allow use to change volume

**Comment by Blueforcer** [comment]
Currently you can set the volume via onscreen menu

**Comment by Lutty76** [comment]
I don't have plugged the screen for the moment 😅 so i didn't see this thanks for information. But can be done by API should be a good thing, no ?

**Comment by Blueforcer** [comment]
https://github.com/Blueforcer/awtrix-light/releases/tag/0.92
