### ISSUE TITLE
[BUG]: Icon stays visible when empty MQTT payload is sent to an active custom app and transition = off

### ISSUE THREAD

**Issue by smarthomejunkie** [Blueforcer/awtrix-light#42]
# Bug report

## Describe the bug
Icon stays visible when empty MQTT payload is sent to an active custom app and transition = off

## Additional information

- Devices involved:
  - Model: Ulanzi Awtrix Smart Pixel Clock 2882 (TC001)
  - AWTRIX-LIGHT version: 0.48

## To Reproduce
1. switch transition off 
2. activate a custom app with mqtt.publish using an icon
3. the custom app is shown with the icon
4. de-activate the custom app by sending mqtt.publish with an empty payload
5. The value of the de-activated custom app is removed, but the icon of the de-activated custom app stays visible

## Expected behavior
The icon of the active app that gets deactivated is removed as well just like the value is.

## Logs

```text
(optional) Add relevant logs which could help tackle the problem.
```

**Comment by Blueforcer** [comment]
that was a bug in an early dev snapshot. doesnt belong to a release.
