### ISSUE TITLE
[FEATURE REQUEST] Allow URL for icon

### ISSUE THREAD

**Issue by blaxer** [Blueforcer/awtrix-light#421]
# Feature Request

### Is your feature request related to a problem?

No

### Describe the solution / feature you'd like

It would be helpful if you could specify a URL for the icon. This would eliminate the storage constraints on the device and also allow for a much easier time when using multiple clocks.

### Additional context

An example of the JSON, I would host the icon files locally but you get the idea:

{
  "text": "Hello, AWTRIX Light!",
  "rainbow": true,
  "duration": 10,
  "icon": "https://developer.lametric.com/content/apps/icon_thumbs/102.gif"
}

Thank you in advance for your consideration.

**Comment by Blueforcer** [comment]
AWTRIX would need to download the icon every time over SSL wich would cause in massive stuttering and RAM consumption.
