### ISSUE TITLE
[BUG] auto brightness in 0.91 is dimmer

### ISSUE THREAD

**Issue by golles** [Blueforcer/awtrix-light#424]
First and most importantly, thank you for making and sharing this project, I appreciate your work and dedication!

# Bug report

## Describe the bug

Recently the `0.91` release came out and I installed this on my 2 clocks.
I immediately noticed the screen was dimmer than before.
I've changed one clock back to version `0.90` to see at the same location what the effect is.
I took a picture (see below) of both clocks in the same place with some daylight coming in (the roller curtain only open a little bit), as with less light it is more visible (like with the current winter weather conditions).

## Additional information

- Devices involved:
  - Model: Ulanzi Awtrix Smart Pixel Clock 2882 (TC001)
  - AWTRIX-LIGHT version: 0.91

## To Reproduce

Install version `0.91` after running version `0.91`.

## Expected behavior

I would prefer to have the auto brightness to be how it was in the previous version, as when it's darker (outside) its more difficult to read the screen of the clock.

## Screenshots

<img width="1247" alt="Scherm­afbeelding 2023-12-04 om 14 40 16" src="https://github.com/Blueforcer/awtrix-light/assets/2211503/fe6fce53-44e1-4cf4-8aae-682a85f9b49b">

Left is the clock running version `0.90` and right is the clock running version `0.91`

## Logs

N/A

## Additional context

N/A

**Comment by Blueforcer** [comment]
set the min_brightness via dev.json higher to fit your needs.

**Comment by golles** [comment]
@Blueforcer what would be an appropriate value to make it comparable to version 0.90?

**Comment by Blueforcer** [comment]
Default is 2. 
Try 3 or 4

**Comment by golles** [comment]
Setting `min_brightness` is a nice solution during the night, but wouldn't increase the brightness during the day

**Comment by Blueforcer** [comment]
Too dark, too bright 😅
Play also with the max value

**Comment by golles** [comment]
That's not what I was trying to say. In general, the clock is too dim since the latest update.
Setting `min_brightness` is only effective when it's dark, as it would now allow the backlight to go less than the set value. During the day, when it's less dark in the room, the `min_brightness` has no effect, as the auto brightness stays higher. In my previous photo, you can see the difference during winter daytime. The right clock is a lot dimmer than the right, but still not near the `min_brightness`

**Comment by Blueforcer** [comment]
In the previous version it was a bug, and the LDR reading was not correct so  the matrix wasn't able to detect bright environment and it was too dim.

Now it's correct. There is no other option, sorry.

**Comment by golles** [comment]
Ok, thanks for the support
