### ISSUE TITLE
[FEATURE REQUEST] Night mode that tints the display with a warm orange hue

### ISSUE THREAD

**Issue by petrnohejl** [Blueforcer/awtrix-light#425]
# Feature Request

### Is your feature request related to a problem?

It's a known fact that blue light has a negative impact on sleep quality because it affects circadian rhythm. Therefore it's recommended to reduce the blue light before sleeping. I am frustrated that I cannot tint the display with orange/red color at night. Something like f.lux does on my computer.

### Describe the solution / feature you'd like

It would be great to add a new feature that would switch the display to a night mode after a specified time. The whole display would be tinted with a warm orange or red hue. Users could specify a color temperature in Kelvins.

### Describe alternatives you've considered

A simple solution could be using red color all the time, but I prefer to use white color during the day and orange/red color at night. Also tinting the icons is not possible.

Thank you for your consideration.

**Comment by Blueforcer** [comment]
There will be no internal automations.
You can make your own like this one

https://flows.blueforcer.de/flow/VqREgAJBApGm
