### ISSUE TITLE
[BUG]: Ulanzi stalls/hangs during FW update to AWTRIX

### ISSUE THREAD

**Issue by cnaehle** [Blueforcer/awtrix-light#426]
# Bug report

## Describe the bug

Both devices I received to day got stuck with the "UPDATE" message in capitals although the webinterface stated success. I waited 5 minutes with the first device, turned off, now stay dark (beeps when left and right button are pressed).

## Additional information

- Devices involved:
  - Model: Ulanzi Awtrix Smart Pixel Clock 2882 (TC001)
  - AWTRIX-LIGHT version: [ eg. v0.45 ]0.91

## To Reproduce

Steps to reproduce the behavior: FW flash with r0.91

## Expected behavior

clean FW update to 0.91 as previously successfully performed.

## Screenshots

n.a.

## Logs

n.a.

## Additional context

n.a.

**Comment by cnaehle** [comment]
Hmm… sounds like a possible chain of actions… anything I can do to fix it?Mobil gesendetAm 08.12.2023 um 20:01 schrieb Stephan ***@***.***>:﻿
Sounds like you flashed the wrong firmware. If you have a ulanzi TC001 flash the ulanzi firmware NOT the old_awtrix2_upgrade

**Comment by Blueforcer** [comment]
Flash the awtrix light ulanzi firmware 😅 use the webflasher

**Comment by Blueforcer** [comment]
You can use whatever flasher you like.
You can download the bin files from the GitHub release page.
For webflasher it's important to NOT use the cable wich came with the clock. It's bad

**Comment by cnaehle** [comment]
Ok, thanks….

Any suggestions on the flasher? I a running Mac OS (latest), and BrewfFlasher  (the only one I found so far) wouldn´t run...

-------
Prof. Dr. Claas Philip Nähle
***@***.***
+49-178-4001619

**Comment by Blueforcer** [comment]
Sorry i dont use MacOS.
But the webflasher should also work on mac if youre using chrome.

Wir können auch Deutsch reden :)

**Comment by cnaehle** [comment]
Gerne…. ;)

Ich habe sowohl Edge als auch Chrome ausprobiert - es erschient die gleiche Fehlermeldung. Auch initial schon, daher hatte ich die FW dann über das Ulanzi-Webinterface geladen, wenngleich leider wohl die flasche bin-Datei.

Meine Frau hat Windows - hast Du da Deine Empfehlung?

Viele Grüße

-------
Prof. Dr. Claas Philip Nähle
***@***.***
+49-178-4001619

**Comment by cnaehle** [comment]
Ha - völlig verrückt… in der Fritzbox wurden beide noch angezeigt, und das Webinterface war noch erreichbar! Diesmal richtig geflachst, alles gut!

Glück gehabt! Danke…!

-------
Prof. Dr. Claas Philip Nähle
***@***.***
+49-178-4001619

**Comment by Blueforcer** [comment]
Sehr gut. Die ESPs laufen auch nur die PINs für die Peripherie wie Matrix sind bei der version anders. Deswegen wird nichts angezeigt, aber das Programm rennt weiter
