### ISSUE TITLE
[BUG] Kalendersymbol wird nicht ausgeblendet

### ISSUE THREAD

**Issue by AngieSoft** [Blueforcer/awtrix-light#429]
Seit update von 0.7 auf 0.91 wird auf dem onscreen-Display das Kalendersymbol in der Zeitansicht nicht mehr ausgeblendet.

![awtrix](https://github.com/Blueforcer/awtrix-light/assets/25101817/bba8d6e4-0608-4069-83b6-540e7949f987)

**Comment by Blueforcer** [comment]
War die neue Zeitansicht in der 0.7 überhaupt schon drin ?^^
Du musst den Time-Mode (TMODE) per settings API ändern.

**Comment by AngieSoft** [comment]
Ja, da konnte man den Kalender per Tasten am Gerät ausblenden, so dass nur noich die Zeit, inkl. Sekunden angezeigt wurde.

**Comment by Blueforcer** [comment]
> Ja, da konnte man den Kalender per Tasten am Gerät ausblenden, so dass nur noich die Zeit, inkl. Sekunden angezeigt wurde.

Nein, du konntest lediglich die Kalender App deaktivieren. Das geht weiterhin.
Das Kalender Icon gehört zur Time-App seit Version "keine ahnung" xD
Du kannst sie per settings API nach belieben anpassen
