### ISSUE TITLE
Unable to control brightness via MQTT

### ISSUE THREAD

**Issue by DaveBKC** [Blueforcer/awtrix-light#430]
Hi, not a bug, I assume. I trying to understand what I'm doing wrong.
I'm able to successfully send some commands via MQTT and get the expected results. A couple of examples of what works for me:
```
awtrix_b91f90/moodlight
{"brightness":70, "color":[155,38,182]}
```
```
awtrix_b91f90/indicator1
{"color":[0,255,123]}
```

My issue is that sending a brightness command, regardless of the payload, it sets the brightness to "0." The only way I know to turn it back on is via the app. Here's an example what I'm sending:

```
awtrix_b91f90/settings
{"BRI":[10]}   
```

Are /settings not fully supported? 
My use case if it helps: My clock is mounted near a wall where auto-brightness doesn't work. I was planning to create an HA automation to control the brightness through sunrise/sunset. 

Sorry if this is in the wrong place. Thanks for reading.

**Comment by Blueforcer** [comment]
Don't use the brackets [10] around the 10. Also make sure automatic brightness control ist deactivated.

**Comment by DaveBKC** [comment]
I can't I didn't already try that. Thanks!

**Comment by Gerrit-KMeier** [comment]
I just tried it with V0.93 using this command
` mosquitto_pub -t awt/settings -m '{"BRI":200,"ABRI":false}'`

works like expected!
Note: My mqtt prefix ist just `awt`

Maybe it's also worth to mention, that a dark font-color stays quite dark - even with full brightness. So consider changing the foreground color, accordingly
` mosquitto_pub -t awt/settings -m '{"TCOL":"#FFFFFF","TIME_COL":0}'`

**Comment by DaveBKC** [comment]
Yeah, it was the brackets. I got it sorted a while back. Thanks though.
