### ISSUE TITLE
[FEATURE REQUEST] Animation icon Database

### ISSUE THREAD

**Issue by MasterVigori** [Blueforcer/awtrix-light#431]
Hello,
is it possible to use the old animation icon database from Awtrix 2.0? 
![Screenshot_20231214_120250](https://github.com/Blueforcer/awtrix-light/assets/102611675/51e5745d-7ba0-4907-90e2-df5152751669)

**Comment by Blueforcer** [comment]
It's not possible, both are different formats.

next version of the official awtrix light app will contain a 32x8 Database

**Comment by Blueforcer** [comment]
The only way is you can download the GIFs from the awtrix 2 Webinterface and resize it to 32x8 and upload it to awtrix light.

**Comment by MasterVigori** [comment]
Ok, thanks I will try that and upload it to Awtrix light

Thank you

**Comment by MasterVigori** [comment]
> The only way is you can download the GIFs from the awtrix 2 Webinterface and resize it to 32x8 and upload it to awtrix light.

Do you have any idea which program I can use to convert the tetris.bin file to tetris.gif?

[Animation DB](https://awtrix.blueforcer.de/animations/ )
