### ISSUE TITLE
Light Sensor Value unit

### ISSUE THREAD

**Issue by Rushmed** [Blueforcer/awtrix-light#433]
Hi.

What unit does the light Sensor value?
I made this issue on the ioBroker adapters GH page:
https://github.com/klein0r/ioBroker.awtrix-light/issues/104#event-11267761567
Can @Blueforcer pls have a look.
Unfortunately the issue was closed immediately referring to your software.

For unit lux as in @klein0r s  adapter the value is way too low.

**Comment by Blueforcer** [comment]
The LDR value doesn't have a Unit. It's the raw 10bit value from the ADC.

**Comment by Blueforcer** [comment]
The lux value is incorrect because the build in LDR is still unknown. Awtrix uses the raw value for brightness controll
