### ISSUE TITLE
[QUESTION] esp32 with matrix panel

### ISSUE THREAD

**Issue by PaulBiod** [Blueforcer/awtrix-light#435]
Hi,
I'm not using the ulanzi device, I use an esp32 connected to a 32x8 panel.
I followed de process; flashed (with [Ulanzi TC001 and custom builds flasher]) , opened webui, set up wifi, mqtt user. Alse, Home assistant is seing the panel.
But instead of the hour, I have meaningless characters.
I create a dev.json file
![image](https://github.com/Blueforcer/awtrix-light/assets/28720176/4331396a-f936-4790-9c62-5da1ed1e1734)
(tried with 0, 1 and 2, almost same result.
The esp32 has pin 32 connected to the data in line of the matrix panel.
Am I doing something wrong ?
Thanks
![20231219_171156](https://github.com/Blueforcer/awtrix-light/assets/28720176/ed53d563-add2-41cd-b7e2-9373ecec13f7)

![image](https://github.com/Blueforcer/awtrix-light/assets/28720176/4d933c7f-ad5c-4a6e-ba2c-0e21e9967552)

**Comment by Blueforcer** [comment]
That's look like a faulty connection, not a software problem. Check your cables. It's also better to solder it.

**Comment by PaulBiod** [comment]
So, pin 32 is correct ? connection about voltage are ok, and the dupont cable from pin 32 is soldered

**Comment by PaulBiod** [comment]
Ok, panel is faulty... even with wled and a solid color, it messes completly

**Comment by Demel75** [comment]
I got similar problem. I had migradte from esp8266 (awtrix2) and rgb-matrix work flawless. Any idea?
