### ISSUE TITLE
DoNotTouch.json Sample

### ISSUE THREAD

**Issue by derjonny88** [Blueforcer/awtrix-light#436]
# Bug report

## Describe the bug

Hello, unfortunately I accidentally overwrote the DoNotTouch.json. Is there somehow a sample that I can use? I should still remember my own values. 

## Additional information

- Devices involved:
  - Model: Ulanzi Awtrix Smart Pixel Clock 2882 (TC001)
  - AWTRIX-LIGHT version: 0.91

**Comment by Blueforcer** [comment]
Just delete it and reboot awtrix.
It will generate a new one
