### ISSUE TITLE
[BUG] Unable to update

### ISSUE THREAD

**Issue by PaulBiod** [Blueforcer/awtrix-light#437]
Hi,
i am using 0.90 
![image](https://github.com/Blueforcer/awtrix-light/assets/28720176/62b5858c-6464-4090-85a1-362ad1008bcb)
When I go to "update" tab, I select the bin file 0.91, then click update, after a few moment, the page shows as follow : 
![image](https://github.com/Blueforcer/awtrix-light/assets/28720176/89b13b9d-4e52-475f-9dc9-f16c12fc56f8)
And when I refresh the gui, it's still in 0.90

**Comment by Blueforcer** [comment]
Try the update function in the buttons Menü, or flash it via USB

**Comment by apachelance** [comment]
Not sure if this is related. However I had issues with timeouts as well, not only using the update function but also regarding general connectivity. Could be a network issues. However I went back to 0.89.

**Comment by Blueforcer** [comment]
Just tested it with 0.92. works as it should. Also tried updating via app or onscreen menu.

**Comment by Blueforcer** [comment]
@PaulBiod Can this issue be closed?

**Comment by PaulBiod** [comment]
Hi @Blueforcer 
sure, it works perfectly. Thanks
