### ISSUE TITLE
[BUG] Draw a pixel at position (x, y) doesn't allow pixel image drawing bigger than 8x8

### ISSUE THREAD

**Issue by rap165** [Blueforcer/awtrix-light#439]
# Bug report

## Describe the bug

When using the Draw pixel 

> **dp | [x, y, cl] | Draw a pixel at position (x, y) with color cl**

we can't use more than 8x8, 
We want to generate a random (DALL-E?) image 8x32 but the maximum is 8x8 (like icon?) nothing more. 

The dc and dr is working for x>8

    { "dc": [28, 4, 3, "#FF0000"] },
    { "dr": [20, 4, 4, 4, "#0000FF"] },

## Additional information

- Devices involved:
  - Model: Ulanzi Awtrix Smart Pixel Clock 2882 (TC001)
  - AWTRIX-LIGHT version: [ v0.91 ]
  - Node-Red [ v3.1.3 ]

## Expected behavior

we should be able to make a bigger image then the 8x8
[8x32image.json](https://github.com/Blueforcer/awtrix-light/files/13753380/8x32image.json)

## Screenshots

8x8 works

![Screenshot 2023-12-22 at 15 37 22](https://github.com/Blueforcer/awtrix-light/assets/46670599/69f4ae43-efa3-4f67-a2cf-f234b43c5b57)

## Logs

```text
(optional) Add relevant logs which could help tackle the problem.
```

**Comment by Blueforcer** [comment]
Thew problem are not coordinates, but the json size. Its too huge to fit into the parser.
For such a huge pictrue its better to use bitmap drawing "db" instead of drawing every pixel seperatly
