### ISSUE TITLE
[FEATURE REQUEST] Choose indicator Color

### ISSUE THREAD

**Issue by dabenzel** [Blueforcer/awtrix-light#440]
# Feature Request

### Is your feature request related to a problem?
Nope

### Describe the solution / feature you'd like

I'd like to change/set the Color for the three indicators in the WebUI

### Describe alternatives you've considered

--

### Additional context

I's about these indicators:
![image](https://github.com/Blueforcer/awtrix-light/assets/2480235/e6daac6d-b1fe-4b0a-8425-6f3d6f2467d5)

**Comment by Blueforcer** [comment]
For API functions there will be no settings in the web UI.
You can already change the color also via API
