### ISSUE TITLE
Turn off christmas Let it snow

### ISSUE THREAD

**Issue by hytrek** [Blueforcer/awtrix-light#441]
Hi there,
I just installed the latest Firmware and yes, it was mentioned I can disable the Snowfall, but how? I am using you iphone app. cannot find a setting for the dev.... Please let me know how to...
Many Thanks and merry christmas

**Comment by Blueforcer** [comment]
https://blueforcer.github.io/awtrix-light/#/dev

**Comment by hytrek** [comment]
I understand... But all I have is either the app or the ioBroker plugin... I have no developer setup or so.... So honestly I have no clue what to do... I like the effect for the moment but christmas and winter will be over one day :-)

**Comment by theunknownstarman** [comment]
how is the correct syntax for disabling?

**Comment by Blueforcer** [comment]
1. Go into your AWTRIX filmanager (**http://[AWTRIX-IP]/edit**)
2. Create a **dev.json**
3. Paste **{"let_it_snow":false}**
4. Save the file
5. Reboot awtrix

**Comment by cobra98** [comment]
In other words create a file with a notepad on windows or vi/nano on linux with file name "dev.json and upload it to http://AWTRIXIP/edit and reboot
Maybe a way to turn off it in the awtrix light app on android would be a better way.

![File_manager_-_Google_Chrome_2023-12-23_23-15-57](https://github.com/Blueforcer/awtrix-light/assets/5233784/0c88b2d1-9717-4796-a59e-58e36e9a63cf)

should look like this

**Comment by Blueforcer** [comment]
You can create and edit files directly in the Filemanager.

Read the documentation for further dev settings.

https://blueforcer.github.io/awtrix-light/#/dev

**Comment by marcgauch** [comment]
Pain. I use the light in my bedroom. The snow is too bright and I hate animations. Disabling it was way too much work. Like OP I only use the app. Not amused. Just wanted to sleep.

**Comment by GreenTentacle** [comment]
I added a `dev.json` and I still have the snow falling over every app.  

Honestly, this is something that I'd like to have easily configurable -- it changes what the end user is expecting to see, without asking their permission or giving them an easy way out.

**Comment by GreenTentacle** [comment]
> I added a `dev.json` and I still have the snow falling over every app.
> 
> Honestly, this is something that I'd like to have easily configurable -- it changes what the end user is expecting to see, without asking their permission or giving them an easy way out.

Whoops, this was a stray character in my json... disabled now

**Comment by distanzcheck** [comment]
[dev.json](https://github.com/Blueforcer/awtrix-light/files/13760908/dev.json)


Nimm mal diese dev.json und starte danach die neu.

Take this dev.json and then restart it.

**Comment by sansonifabio** [comment]
@Blueforcer ich finde es mit dem Schneefall sehr schön, musste aber auch erst vertehen was eine dev.json ist. 
Ich arbeite fast nur mit deiner App und natürlich mit ioBroker und dem Awtrix Adapter. 
Vieleicht hats du ja mal Zeit den Schnnefall in die App zu konfigurieren dann kann man sich das zu Weihnachten selbst aus und anschalten. ;-)

**Frohe Weihnachten und vielen vielen Dank das du Awtrix-light machst.**
Grüße
Fabio

**Comment by Blueforcer** [comment]
> @Blueforcer 
> ich finde es mit dem Schneefall sehr schön, musste aber auch erst verstehen was eine dev.json ist. 
> Ich arbeite fast nur mit deiner App und natürlich mit ioBroker und dem Awtrix Adapter. 
> Vieleicht hast du ja mal Zeit den Schnnefall in die App zu konfigurieren, dann kann man sich das zu Weihnachten selbst aus und anschalten. ;-)
> 
> **Frohe Weihnachten und vielen vielen Dank das du Awtrix-light machst.**
> Grüße
> Fabio

Die App kann nicht in die Dev schreiben.
Sieht eher so aus als müsste ich heute nochmal ein Update nachschieben in dem es wieder ausgeschaltet wird.
 
Es ist erstaunlich wieviele Leute keine Ahnung haben was 
1. Awtrix alles kann
2. Eine JSON ist
3. Die Dokumentation ist.

Und dennoch irgendwie awtrix nutzen 😄

**Comment by sansonifabio** [comment]
Es ist wie es ist 😁😉

**Comment by Blueforcer** [comment]
https://github.com/Blueforcer/awtrix-light/releases/tag/0.93

**Comment by sansonifabio** [comment]
> https://github.com/Blueforcer/awtrix-light/releases/tag/0.93

... ich danke dir ganz herzlich und es tut mir wirklich echt leid das User stellenweise so harsch reagiert haben.

**Comment by smarthomejunkie** [comment]
Thank you Stephan for all your hard work. I appreciate all the efforts that you are making. Don't be sad about the harsh comments of some people. They probably have no idea how much work you put into this awesome free piece of firmware. I wish you a very merry Christmas and a happy 2024!

**Comment by Blueforcer** [comment]
> > https://github.com/Blueforcer/awtrix-light/releases/tag/0.93
> 
> ... I thank you very much and I'm really sorry that users reacted so harshly in some places.
> 
> ... ich danke dir ganz herzlich und es tut mir wirklich echt leid das User stellenweise so harsch reagiert haben.

It's not your fault.

I assume a certain basic understanding of this project. It's a shame to get upset about how I program my project.
I have already deleted comments here that were really offensive.

**Comment by Blueforcer** [comment]
> ... I thank you very much and I'm really sorry that users reacted so harshly in some places.
> 

It's not your fault.

I assume a certain basic understanding of this project. I think it's a shame to get upset about how I program my project.
I have already deleted comments here that were really offensive.

**Comment by theunknownstarman** [comment]
@Blueforcer 

Ich sehe es genauso wie meine Vorposter. Bitte nicht ärgern, es gibt immer irgendwelche Nörgler die nicht im Ansatz einschätzen können wieviel Herzblut Du in die Sache steckst.

In meinem Fall war mir nur nicht klar, dass es "hidden functions" gibt und nachdem ich ein paar aktiviert habe, hat das Ganze noch mehr Spass gemacht, als es vorher schon der Fall war.
Weiterhin konnte ich nicht einschätzen ob es "zu schneien aufhört", wenn Weihnachten vorbei ist? (Ob Du diese Funktion Datum gesteuert realisiert hast, war mir leider nicht klar).

vG, ein GROSSES Danke & ein schönes Weihnachtsfestchen

**Comment by ProggroP** [comment]
Thank you for your great an have a great X-mas.

**Comment by Dtrieb** [comment]
Stephan vielen Dank für die alternative Firmware!
Man kann echt froh sein, das du diese auf die Beine gestellt hast, denn mit ihr hat man echt einen Mehrwert!

Und zu Silvester/Neujahr gibt's dann ein Feuerwerk?(Farbige Pixel 🫣😜) 

{"firework":true} or {"firework":false}

**Comment by SomeFixItDude** [comment]
@Blueforcer love the snow!  Appreciate you're work on this project.  This is the clock for my living room and notification display for my home.  Keep up the great work!  Merry Christmas

**Comment by hytrek** [comment]
Hi Stephan,
das wollte ich nicht anstossen, dass sich hier in unangebrachter Weise Leute beschweren. Ich schätze es sehr, dass Du Deppen wir mir möglich machst (mit Kleinohr), so nettes Spielzeugs zum Laufen zu bringen, aber eben ohne, dass ich Programmierkenntnisse brauche. Ich habe mir die dev.json von @distanzcheck geladen und damit kann ich jetzt das machen, was ich wollte. An Euch beide herzlichen Dank! Und weiter so ... Again what learned ;-)

**Comment by hytrek** [comment]
> [dev.json](https://github.com/Blueforcer/awtrix-light/files/13760908/dev.json)
> 
> Nimm mal diese dev.json und starte danach die neu.
> 
> Take this dev.json and then restart it.

Danke Dir... Nun läufts auch mit dem ein- und ausschalten bei mir!

**Comment by theunknownstarman** [comment]
Weis jemand zufällig ob es möglich ist die Batterieanzeige irgendwie abzuschalten?
Ich habe die AWTRIXies am Netzteil laufen und benötige diese nicht.

**Comment by Dtrieb** [comment]
> Weis jemand zufällig ob es möglich ist die Batterieanzeige irgendwie abzuschalten? Ich habe die AWTRIXies am Netzteil laufen und benötige diese nicht.

Zum Beispiel, die App runterladen und da ein bzw. ausschalten...

**Comment by Blueforcer** [comment]
Oder im onscreen Menü oder per settings API

**Comment by theunknownstarman** [comment]
Danke. App gekauft 🤟🏻
