### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by cobra98** [Blueforcer/awtrix-light#443]
# Bug report

## Describe the bug

After updating with awtrix light under android, snow is showing all the time,
no way found yet to turn it off again too
Update to 0.92

## Additional information

- Devices involved:
  - Model: Ulanzi Awtrix Smart Pixel Clock 2882 (TC001)
  - AWTRIX-LIGHT version: 0.0.22

## To Reproduce

it was mentioned in the update feature to add snow
but not how to turn it off again too
![awtrix](https://github.com/Blueforcer/awtrix-light/assets/5233784/e37932a8-6fff-47f1-80e2-0e9431e38467)

## Screenshots

attached

## Logs

don´t think it is needed

## Additional context

Please supply a way to turn the snow off
On the website of ulanzi awtrix / time / it shows esp so i guess i have a new model with esp

**Comment by Blueforcer** [comment]
Please read the changelog before opening a "bug" report
https://github.com/Blueforcer/awtrix-light/releases/tag/0.92

also check the other issues before
https://github.com/Blueforcer/awtrix-light/issues/441
