### ISSUE TITLE
[QUESTION] About ldr_factor, ldr_gamma

### ISSUE THREAD

**Issue by PaulBiod** [Blueforcer/awtrix-light#445]
Hi, in my dev.json file, I tried changing the values, but it doesn't seem to change anything.
I tried from 0 to 1000 and from 1.0 to 3.0

My brightness is still too dark

![image](https://github.com/Blueforcer/awtrix-light/assets/28720176/b6d2ad6a-3b5a-4e1b-8991-ece8f1feb8f4)

**Comment by Blueforcer** [comment]
The filemanger point you to the error with the red dot. you have a space before your json. remove it.

**Comment by PaulBiod** [comment]
@Blueforcer Sometimes, I feel so stupid !
Thanks a lot !
