### ISSUE TITLE
activate let_it_snow

### ISSUE THREAD

**Issue by tobasium** [Blueforcer/awtrix-light#446]
Hi I want to activate let it snow. Bit it did not work.

I created a dev.json in File Manager root.

I added:

`{
"let_it_snow": "true",
}`

also test:

`{
"let_it_snow": true,
}`
Could someone tell me where i make the mistake.

**Comment by Rushmed** [comment]
Try without the “,“.

**Comment by tobasium** [comment]
Thanks this works for me.

**Comment by tobasium** [comment]
Thanks for the fast Feedback

**Comment by Rushmed** [comment]
Ur welcome, merry christmas.
