### ISSUE TITLE
[BUG] Fix uptime sensor in Home Assistant

### ISSUE THREAD

**Issue by TheGroundZero** [Blueforcer/awtrix-light#45]
# Bug report

## Describe the bug

From the Home Assistant Logs:
> Sensor sensor.awtrix_xxxxxx_uptime has device class `duration`, state class `None` and unit `None` thus indicating it has a numeric value; however, it has the non-numeric value: P0DT7H56M8S (<class 'str'>);
> Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+mqtt%22

## Additional information

- Devices involved:
  - Model: Ulanzi Awtrix Smart Pixel Clock 2882 (TC001)
  - AWTRIX-LIGHT version: v0.45

## Expected behavior

Have a properly setup uptime sensor.

Send the boot time as a datetime object / iso datetime string and have HA calculate the uptime for you?

## Screenshots

![image](https://user-images.githubusercontent.com/2406013/230623856-921b59f0-9e31-4c91-a1e5-1f59d30e1225.png)

## Logs

```text
Sensor sensor.awtrix_dd2824_uptime has device class duration, state class None and unit None thus indicating it has a numeric value; however, it has the non-numeric value: P0DT7H56M8S (<class 'str'>); Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+mqtt%22
```

**Comment by Blueforcer** [comment]
The time format  is an ISO 8601 duration format.
Tell me how else to send it

**Comment by TheGroundZero** [comment]
Perhaps unit_of_measurement or state_class need to be configured correctly HA to recognise this format vs HH:MM:SS ?
