### ISSUE TITLE
Hard coded sound file extension

### ISSUE THREAD

**Issue by Brunas** [Blueforcer/awtrix-light#452]
Hi,

I think it's not really correct to have such statement in Sounds section in documentation:
![image](https://github.com/Blueforcer/awtrix-light/assets/5709368/f1b21fa4-b827-4f9a-be95-be073122d7ee)

and have `.txt` hard coded in the [code](https://github.com/Blueforcer/awtrix-light/blob/326184127509ff86074ef78ea7014debf541cb91/src/PeripheryManager.cpp#L318)

I've spent too much time on trying to find why api or mqtt sound request is not working when rtttl works.

**Comment by Blueforcer** [comment]
Just ask if you have problems.
There is no extension required to keep the JSON small as possible.

**Comment by Blueforcer** [comment]
> Just ask if you have problems.
> There is no extension required to keep the JSON small as possible.

Same also applies to icons.
