### ISSUE TITLE
[FEATURE REQUEST] 3 More Indicators Please

### ISSUE THREAD

**Issue by DaveTiff** [Blueforcer/awtrix-light#463]
Love this display and its good using it with Home Assistant, but I could do with more indicators.

I use the indicators to show when the upstairs heating is On, Hot Water Heating is On & downstairs heating is On, that's all 3 used but I would also like to display when my cheap rate electricity kicks in and when my car is on charge.

I believe there is room on the display, just means changing the shape of the existing indicators and shifting everything to the right by 1 pixel.

I have drawn up what I believe is a solution. I know Its a big ask.

![Awtrix 3 more indicators](https://github.com/Blueforcer/awtrix-light/assets/25724769/38d16542-7452-4a4f-94d0-7fb639215663)

**Comment by DaveTiff** [comment]
Just a thought and maybe easier alternative is if you have the week days disabled, then allow each of the week days to be individually addressable, that way you would get 7 more indicators.

**Comment by Blueforcer** [comment]
But only in the time app. 
To move all content 3 pixels to the right will also shorten the available content space which is already pretty short. And this will also affect other functions like the progressbar.

**Comment by DaveTiff** [comment]
Happy with only in the time app, that is all that I have constantly displayed, except for when a message is sent.

**Comment by Blueforcer** [comment]
But very few people do, so the effort involved is quite high and out of all proportion. It would therefore be better if you simply created a custom app according to your preferences

**Comment by DaveTiff** [comment]
Totally understand, would love to create a custom app, but not sure where to start. But many thanks for the great work you have done.
