### ISSUE TITLE
[BUG] let_it_snow not working

### ISSUE THREAD

**Issue by dl1ekm** [Blueforcer/awtrix-light#465]
# Bug report

## Describe the bug

This option in the dev.json has no effect.

## Additional information

- Devices involved:
  - Model: ESP Wroom 32
  - AWTRIX-LIGHT version: [ v0.91]

## To Reproduce

Put the line

 "let_it_snow": true
In the dev.json file.Restart.

## Expected behavior

Snow as background effect / global overlay.

## Logs

```text
(optional) Add relevant logs which could help tackle the problem.
```

**Comment by RDG88** [comment]
Please show the content of your dev.json

**Comment by dl1ekm** [comment]
After update to v0.94 it's working.I
Thanks for support!
