### ISSUE TITLE
[BUG] Suport for ESP32-S3

### ISSUE THREAD

**Issue by Himura56** [Blueforcer/awtrix-light#469]
# Bug report

## Describe the bug
Sorry for bad English i not speak english...

I updated my old Awtrix2 and see the matrix is not compatible with awtrix light, so make of zero witch a new [led matrix](https://articulo.mercadolibre.cl/MLC-492790529-pantalla-256-leds-smd5050-8x32-ws2812b-_JM), and I see they added oficial support for [ESP32-S3](https://www.aliexpress.com/item/1005005767192637.html?spm=a2g0o.order_list.order_list_main.50.3336194dFA02kY) Board, however not is possible compiler the software because the matrix pin (32) not exist in the board, i fix the problem using another pin (13) in displaymanager adding in the lines 37 and 38 the code

```text
#elif ESP32_S3
#define MATRIX_PIN 13
```
in PeripheryManager pin of select button and i2c_scl is same pin? (10) is correct this? i changed for

```text
#elif ESP32_S3
#define BATTERY_PIN 4
#define BUZZER_PIN 5
#define LDR_PIN 6
#define BUTTON_UP_PIN 11
#define BUTTON_DOWN_PIN 7
#define BUTTON_SELECT_PIN 10
#define I2C_SCL_PIN 9
#define I2C_SDA_PIN 8
```
in ESP32-S3 not added support for BME280 only for SHT31, i can fix using the code of awtrix2_upgrade sections.

I have problems with send stats to home assistant in mqtt discovery, i not idea of the problem, I think it could be for used ESP32_S3 option at compiled, using awtrix2_upgrade at 0.91v this not ocurred.

I don't know if it's a code problem... I don't see awtrix2 or lamatric icons...

using [TTP223](https://www.aliexpress.com/item/1005006216522994.html?spm=a2g0o.order_list.order_list_main.17.3336194dFA02kY) touch button for the select button we have soldier the "A" pins?

## Additional information

- Devices involved:
  - Model: ESP32-S3 with Matrix type 2
  - AWTRIX-LIGHT version: [v0.94 ]

## To Reproduce

- make hardware using esp32-s3
- edit code
- compiler and upload to the board

## Expected behavior

100% functionality

## Screenshots

![image](https://github.com/Blueforcer/awtrix-light/assets/40153974/8db65080-2cf3-4aad-b0bc-b01315e21400)
![image](https://github.com/Blueforcer/awtrix-light/assets/40153974/2a6c10db-0ec4-4205-a225-cd31763a5f69)
![image](https://github.com/Blueforcer/awtrix-light/assets/40153974/550a926a-d0e3-4518-b6ca-b119c13610d7)

In 0.94 ESP32_S3. not send statics
![image](https://github.com/Blueforcer/awtrix-light/assets/40153974/c85067ef-998f-43fc-af11-2bf570c8eea5)
mqtt explorer not topic
![image](https://github.com/Blueforcer/awtrix-light/assets/40153974/3e60e686-0a01-4c90-8b8d-403758ad30f8)

in 0.91 awtrix2_upgrade
![image](https://github.com/Blueforcer/awtrix-light/assets/40153974/58ac2361-963d-402a-9fe8-1fdadf3f9bcb)

## Logs

```text
(optional) Add relevant logs which could help tackle the problem.
```

**Comment by Blueforcer** [comment]
ESP-S3 is currently not officially supported. Please only use the environments which are also placed in the releases.
