### ISSUE TITLE
Motion detector [FEATURE REQUEST]

### ISSUE THREAD

**Issue by MarkKalk** [Blueforcer/awtrix-light#472]
Hi,
it would be nice to have the option to add a motion detector like the HC-SR501 to the Ulanzi Clock.

- Motion wakes the clock up, no motion for some time sends the clock to deep sleep or display off.
- Motion is puplished via mqtt.

Thank you

**Comment by 10der** [comment]
Ulanzi Clock - Wunderwaffe
why you wouldn't use separated motion sensor (or any HA automation) and call Ulanzi Clock API for deep sleep or display off etc so on...
IMHO

**Comment by Blueforcer** [comment]
Agree. 
Very few users will open the ulanzi to somehow solder on a motion sensor.
