### ISSUE TITLE
[BUG] Power Control REST API Bool Payload

### ISSUE THREAD

**Issue by berndb84** [Blueforcer/awtrix-light#473]
# Bug report

## Describe the bug

I was trying to use the REST APIs. I made a mistake in the payload of the Power Control API with Boolean data and found this issue.

## Additional information

- Devices involved:
  - Model: Ulanzi Awtrix Smart Pixel Clock 2882 (TC001)
  - AWTRIX-LIGHT version: 0.94

## To Reproduce

Using the API:
`http://[IP]/api/power` 	
With payload `{"power": "true"}` clock will switch on, but with `{"power": "false"}`it will **not** switch off.
The response from the clock is always 200. 

## Expected behavior
The payload for JSON Booleans should always be without double quotes ("). The clock should not change the power mode on a wrong request. In addition it should response with eg. Bad Request (400).

**Comment by Blueforcer** [comment]
currently there is no single check on any API point.
