### ISSUE TITLE
How do I get the IP-address of my Ulanzi device?

### ISSUE THREAD

**Issue by salabim** [Blueforcer/awtrix-light#476]
I have a Python program controlling my Awtrix device, which was connected to 192.168.1.53
After weeks of operation, the program didn't work anymore and I found out that the IP address had been changed to 192.168.1.54.
Of course, I can change this, but then at a certain point in time, the address will change again as it is dynamic.
What would be the best way to proceed:
- assign a static address. Is that possible at all and if yes, how
- scan for the Awtrix device. I know that this should be possible as the Awtrix app does that. But how to do this in Python?
Maybe these questions are not Awtrix-related, but I'm stuck.

**Comment by petterhanssen** [comment]
Static IP or DHCP reservation would be the safest solution. 
Could also use MQTT which is not dependant on the MQTT clients IP-address

Third option is using ARP scanning and filtering by MAC-address prefix. I suggest using static IP
