### ISSUE TITLE
[BUG]clockless_rmt_esp32.h:358:46: error: static assertion failed: Invalid pin specified      static_assert(FastPin<DATA_PIN>::validpin(), "Invalid pin specified");

### ISSUE THREAD

**Issue by 97691974** [Blueforcer/awtrix-light#477]
When compiling this project in Vscode, I encountered this error message, indicating that the specified pin is invalid, I have checked the code does not call this class, I am not clear why there is this error
![image](https://github.com/Blueforcer/awtrix-light/assets/50973914/c02b7da2-8968-4a7a-ab71-13b765ac4035)
![image](https://github.com/Blueforcer/awtrix-light/assets/50973914/2867e437-2583-43af-ad68-55194356f70b)

**Comment by Blueforcer** [comment]
Since the current main branch works fine, the question is, what have you changed?
Seems like you´ve changed the Matrix data pin...
Furthermore you try to compile a ESP32 S3 enviroment wich is currently unsupported.
