### ISSUE TITLE
[FEATURE REQUEST] More statically-typed languages friendly API for Draw

### ISSUE THREAD

**Issue by leinardi** [Blueforcer/awtrix-light#478]
# Feature Request

### Is your feature request related to a problem?

I'm communicating with the Awtrix Light client via a MQTT server written in Kotlin and I was able so far to map every single API besides the [Draw](https://blueforcer.github.io/awtrix-light/#/api?id=drawing-instructions) one.

The issue is that, with the current API, it is not possible to generate the the draw payload serializing something like a Kotlin `data class`.

### Describe the solution / feature you'd like
The current API is expecting a list of dictionaries of lists containing mixed types:

```json
{"draw":[  
 {"dc": [28, 4, 3, "#FF0000"]},  
 {"dr": [20, 4, 4, 4, "#0000FF"]},  
 {"dt": [0, 0, "Hello", "#00FF00"]}  
]}  
```
This is usually tricky to handle in statically-typed languages like Kotlin/Java.

A statically-typed friendly approach would be something like this:
```json
   "draw":[
      {
         "type":"dc",
         "x":28,
         "y":4,
         "r":3,
         "cl":"#FF0000"
      },
      {
         "type":"dr",
         "x":20,
         "y":4,
         "2":4,
         "h":4,
         "cl":"#0000FF"
      },
      {
         "type":"dt",
         "x":0,
         "y":0,
         "t":"Hello",
         "cl":"#00FF00"
      }
   ],
```
that could be easily mapped to  a `sealed class` of `data class`es:

```kotlin
@Serializable
sealed class Draw {
    @Serializable
    @SerialName("dr")
    data class Rectangle(
        val x: Int,
        val y: Int,
        @SerialName("w")
        val width: Int,
        @SerialName("h")
        val height: Int,
        @SerialName("cl")
        val color: String,
    ) : Draw()

    @Serializable
    @SerialName("dc")
    data class Circle(
        val x: Int,
        val y: Int,
        @SerialName("r")
        val radius: Int,
        @SerialName("cl")
        val color: String,
    ) : Draw()

    @Serializable
    @SerialName("dt")
    data class Text(
        val x: Int,
        val y: Int,
        @SerialName("t")
        val text: String,
        @SerialName("cl")
        val color: String,
    ) : Draw()
[...]
}
```

### Describe alternatives you've considered

Currently I still haven't found a way to generate this Json using [kotlinx.serialization](https://github.com/Kotlin/kotlinx.serialization) besides building the String manually.

**Comment by Blueforcer** [comment]
This design is used to keep the json as small as possible (due limited rescources on the ESP) and it works like this since the beginning. Please understand that i cannot change the API beacuse of a single request and force hundreds of users to change their automations.
