### ISSUE TITLE
[FEATURE REQUEST] Live view card for home assistant

### ISSUE THREAD

**Issue by sushant-here** [Blueforcer/awtrix-light#492]
# Feature Request

It would be nice to be able to use the live view in a home assistant dashbaord. I know this is possible by using a webview card. However it wont work when remotely accessing over https.

### Describe the solution / feature you'd like

A Homeassistant card that can be pointed at a Awtrix instance for a live screen view.

### Describe alternatives you've considered

Ive considered setting up a reverse proxy.

### Additional context

n/a

**Comment by Blueforcer** [comment]
this has nothing to do directly with the firmware.
However it already exists :)

https://github.com/RDG88/lovelace-awtrix-light-display-card

You will find more great projects on my discord server.
