### ISSUE TITLE
[BUG] Webinterface loads javascript and images from the internet

### ISSUE THREAD

**Issue by eku** [Blueforcer/awtrix-light#495]
# Bug report

## Describe the bug

When using the web interface, resources are loaded from Google, GitHub, Cloudflare and more. These could easily be stored on the ESP32.

## Additional information

- Devices involved:
  - Model: Ulanzi Awtrix Smart Pixel Clock 2882 (TC001)
  - AWTRIX-LIGHT version: v0.94

## To Reproduce

Open the browsers web developer tools and watch network traffic.

## Expected behavior

All resources of the web interface including the file editor are located on the ESP32.

## Screenshots
![Bildschirmfoto vom 2024-02-20 17-09-25](https://github.com/Blueforcer/awtrix-light/assets/418685/47576eea-60f6-4307-8d71-75a95ea2fce9)
![Bildschirmfoto vom 2024-02-20 17-07-29](https://github.com/Blueforcer/awtrix-light/assets/418685/31ebad59-2a63-462b-bbf5-6916e01efc1c)

## Additional context

Strictly speaking, this is a violation of privacy.

**Comment by Blueforcer** [comment]
Bug? Violation of privacy in a opensource project? 
You can always check the code and see what happens.
These are pictures wich are located in this repo, and javascipts for the filemanger on a standard cdnjs. All of this is opensource.
Anyways, these files are way too huge for the limited resources on the ESP.
If you not agree to this, please dont use this project, thanks.
