### ISSUE TITLE
[BUG] temp_offset leads to wrong temperature value

### ISSUE THREAD

**Issue by individualist99** [Blueforcer/awtrix-light#498]
# Bug report

## Describe the bug

My ulanzi clock shows a temperatre that's 1°C lower than it should bei. So I added an temp_offset of 1 to dev.json and rebooted the clock. It now Shows 30°C instead of previously 20 °C / expected 21°C , so obviously 10°C have been added instead of 1°C. Maybe I fif Something wrong, but Inplayed around a but with different values and Formats (1, +1, 1.0, 1,0, ...) but was not able to actually get a correct result.
  
Looks Like temp_offset does Not Work as expected. 
  
content of dev.json:

```
{

  "temp_offset": 1,

  "hum_offset": 0
}

```## Additional information

- Devices involved:
  - Model: Ulanzi Awtrix Smart Pixel Clock 2882 (TC001)
  - AWTRIX-LIGHT version: 0.93

## To Reproduce

Set temp_offset to 1 
## Expected behavior

Temperature should be 1°C higer than before
## Screenshots

If applicable, add screenshots to help explain your problem.

## Logs



## Additional context

Add any other context about the problem here.

**Comment by Blueforcer** [comment]
Standard value is 9, because in reality the raw sensor value is completely wrong. 

So you need to enter 8

**Comment by Blueforcer** [comment]
Make sure there is no leading space in your JSON. The editor will show you the error with a red dot.

**Comment by proffalken** [comment]
Nope, no red dots:
![image](https://github.com/Blueforcer/awtrix3/assets/262545/a05ba437-e8b6-4a8d-843a-54b8ecb3442e)

**Comment by Blueforcer** [comment]
Did you restarted awtrix after change?
For me it's working.

**Comment by proffalken** [comment]
I'll restart it again, but I thought I had.

Does it need to be a full power-off/back on, or will "restart ESP" from the MQTT page do the trick?

**Comment by proffalken** [comment]
@Blueforcer - I've edited the file, saved it, but when I go back in, the save hasn't taken effect.

This remains the same regardless of whether I reboot or not, the "temp_offset" value remains at `-9`
