### ISSUE TITLE
[BUG] Broken auto brightness

### ISSUE THREAD

**Issue by infestonn** [Blueforcer/awtrix-light#499]
# Bug report
Not sure what exactly it is. 
## Describe the bug

My Illuminance sensor always reports `0`lx, therefore (I presume) auto-brightness does not work.
It is a new device so I only tested it with the latest version.
Auto-brightness on stock Ulanzi firmware did work.

## Additional information

- Devices involved:
  - Model: Ulanzi Awtrix Smart Pixel Clock 2882 (TC001)
  - AWTRIX-LIGHT version: [ eg. v0.94 ]

## To Reproduce

By a new clock. Falshit with https://blueforcer.github.io/awtrix-light/#/flasher v0.94

## Expected behavior

Do you know what may have caused the problem, or did my sensor just die?

**Comment by Blueforcer** [comment]
No issues so far from other users. I assume it's a faulty hardware

**Comment by infestonn** [comment]
> Did you test it with a flashlight? The lux value isn't accurate, but you can read the raw value from the stats API.
> 
> No issues so far from other users. So if the raw value still doesn't change I assume it's a faulty hardware.

Checked stats via the API. A direct flashlight beam doesn't change `lux` at all. 
Only `ldr_raw` value is moving. I have not found information on this parameter and Im also a newb. Is that something related to light?

**Comment by Blueforcer** [comment]
LDR_raw is the raw analog value measured by the ESP.

Lux isn't accurate because nobody knows which sensor is used in the Ulanzi and there are different batches out there.

So if you want to use the light sensor for any reason use the raw value.
Also Awtrix light uses the raw value for Auto brightness, not lux.
