### ISSUE TITLE
[BUG] Online Flasher

### ISSUE THREAD

**Issue by pesce** [Blueforcer/awtrix-light#503]
# Bug report

website: https://blueforcer.github.io/awtrix-light/#/flasher
1. Using multiple windows 10 computers, Chrome and Edge browsers, I cannot get the flasher to appear.  
2. On the same page, when I click on the ESP Web Tools link (which opens in the same page) and attempt their live demo, I get this error: Error: Failed to execute 'requestPort' on 'Serial': Access to the feature "serial" is disallowed by permissions policy.

When I go directly to https://esphome.github.io/esp-web-tools/ and attempt the same live demo, it works as expected.

## Additional information

- Devices involved:
  - Model: Ulanzi Awtrix Smart Pixel Clock 2882 (TC001)
  - AWTRIX-LIGHT version: [ eg. v0.45 ]

## To Reproduce

Browse to: https://blueforcer.github.io/awtrix-light/#/flasher

## Expected behavior

I expect a "connect" button, or similar.

## Screenshots

![image](https://github.com/Blueforcer/awtrix-light/assets/4434099/d199e666-32a8-4448-9432-51968de7d6b3)

![image](https://github.com/Blueforcer/awtrix-light/assets/4434099/d89babe2-fe36-4d7b-a15e-d7ea1031db1e)

![image](https://github.com/Blueforcer/awtrix-light/assets/4434099/a8c80d0a-4412-4903-bca1-c2d3a585d6b9)

## Additional context

Thank you

**Comment by Anonym-tsk** [comment]
Go to chrome://settings/content/siteDetails?site=https%3A%2F%2Fblueforcer.github.io
![image](https://github.com/Blueforcer/awtrix-light/assets/1973755/e326dbd5-e733-4622-809f-d92fafa5ae22)
Look at "Serial ports" permission. Set it to default value.

**Comment by Blueforcer** [comment]
mhh. still works as expected:
![image](https://github.com/Blueforcer/awtrix-light/assets/31169771/e8c55bb8-4ab2-4cfd-b1d3-710b5b2416bf)
