### ISSUE TITLE
Question: does AWTrix need internet access to download new icons?

### ISSUE THREAD

**Issue by Jackie78De** [Blueforcer/awtrix-light#504]
Hello,

I own a Ulanzi Pixel clock powered by Awtrix Light, and a thing I wonder about is that I am able to download new icons using the Webinterface of AWTRIX Light although I have intentionally blocked internet access for the Ulanzi device in my Router (Fritz Box).

So I wonder: does the blocking for some reason not work, or does loading new icons download them on the client who uploads it to the Ulanzi device, and therefor is possible without the Ulanzi device itself being able to connect to the internet? So how can I check if the Ulanzi device is really not able to access the internet at all, being only accessed in my local network?

Thank you!

**Comment by Blueforcer** [comment]
Your browser downloads the icon and push it locally to Awtrix.

Awtrix only uses Internet Access for NTP time and self updating.
