### ISSUE TITLE
[FEATURE REQUEST] Disable app switch via hardware buttons

### ISSUE THREAD

**Issue by Green-Kite** [Blueforcer/awtrix-light#505]
# Feature Request

### Is your feature request related to a problem?

No.

### Describe the solution / feature you'd like

I would like to disable the app switch via the buttons on top of the Ulanzi Clock. In that way I could use the Buttons as custom triggers for Home Assistant Automations, like an alarm Clock or other things based on button presses without leaving the app I set via MQTT.

### Describe alternatives you've considered

This could be added as an option to the dev.json.

**Comment by Blueforcer** [comment]
Already possible.
See BLOCKN key in the settings API

**Comment by Green-Kite** [comment]
I'm sorry, I read the documentation but apparently overlooked this line.
