### ISSUE TITLE
Does it speak time by pressing a button?

### ISSUE THREAD

**Issue by midenok** [Blueforcer/awtrix-light#507]
I'm looking for **obvious** feature of speaking time. Strange it was not implemented out of the box.

**Comment by Blueforcer** [comment]
Im not sure what you mean.
Like speaking the current time with a speaker?
Thats not possible, the Ulanzi clock doesn't have a speaker, only a passive piezo buzzer

**Comment by midenok** [comment]
Yes, speaking current time by pressing button... Too pity... If anyone knows nice hardware for this or existing implementation, please tell here. Another important requirement is time synchronization, that's why I'm looking for IP-capable clocks.

**Comment by Blueforcer** [comment]
You can use a Dfplayer with AWTRIX and built your own speaker
