### ISSUE TITLE
[BUG] Disabling Humidity and Battery Level but always displayed

### ISSUE THREAD

**Issue by hallard** [Blueforcer/awtrix-light#55]
# Bug report

## Describe the bug
Disabling humidity and battery screen has no effect 

## Additional information

- Devices involved:
  - Model: Ulanzi Awtrix Smart Pixel Clock
  - AWTRIX-LIGHT version: v.0.49 (but same since beguining) 

## To Reproduce
Flash latest version 

## Expected behavior
Screen slide not showing humidity nor battery level

## Screenshots
![image](https://user-images.githubusercontent.com/2471931/231296267-f266a9a4-e4bb-4872-9eca-a3f12e3bfa43.png)

![image](https://user-images.githubusercontent.com/2471931/231296435-1f441914-8e4e-4aac-be9a-df37b2f128a2.png)

**Comment by Blueforcer** [comment]
You're using a very old config.json from one of the first versions. According to an older changelog you had to delete the JSON.
