### ISSUE TITLE
Allow to show text exactly once (no matter the length) 

### ISSUE THREAD

**Issue by TheZoker** [Blueforcer/awtrix-light#6]
When I use my spotify artist and title on a custom page it's hard to display the whole text. Sometimes the text is so long, that the transition cuts in the middle of the text. Sometimes the title is so short, that it displays 3 times. Would be nice if there was a MQTT option to display the text exactly once. After the text is finished switch back to the other page.

**Comment by Blueforcer** [comment]
Its already possible with the "repeat" key. 
https://blueforcer.github.io/awtrix-light/#/custom

**Comment by TheZoker** [comment]
Ah nice, works perfectly. Thanks! 🎉
