### ISSUE TITLE
[FEATURE REQUEST] Icon download via MQTT/HTTP API

### ISSUE THREAD

**Issue by blaxer** [Blueforcer/awtrix-light#61]
# Feature Request

Would it be possible to expose the icon download functionality via MQTT / HTTP API? That way if you have multiple clocks you would be able to download icons programmatically across all of them. TIA!

### Is your feature request related to a problem?

No

### Describe the solution / feature you'd like

I would like to be able to use MQTT or the HTTP API to be able to download icons programmatically.

### Describe alternatives you've considered

I do not believe this functionality is present, unless I missed it.

### Additional context

NA

**Comment by Blueforcer** [comment]
The download **and**  conversation is done by your browser, not the ESP32.
But once downloaded you can send the files also via http to /edit/ICONS
