### ISSUE TITLE
[QUESTION] Cannot change settings like WD or TFORMAT

### ISSUE THREAD

**Issue by MarcoGos** [Blueforcer/awtrix-light#62]
# Question

When I try to publish a MQTT payload to <prefix>/settings to change a setting like "WD" or "TFORMAT", The display flashes but the changes are not set. Also when I try to set is via Postman to http://<ip>/api/settings the same happens. Maybe I am doing something wrong, but can you help me?

Used payload:

{
    "WD": false
}

## Additional information

- Devices involved:
  - Model: Ulanzi Awtrix Smart Pixel Clock 2882 (TC001)
  - AWTRIX-LIGHT version: 0.51

## Logs

```text
(optional) Add relevant logs which could help tackle the problem.
```

**Comment by Blueforcer** [comment]
there was an bug with boolean values like WD.
timeformat works still great with
```{"TFORMAT":"%l:%M %p"}```
