### ISSUE TITLE
[FEATURE REQUEST] Binary sensor for charging state / power source

### ISSUE THREAD

**Issue by schneekluth** [Blueforcer/awtrix-light#63]
# Feature Request

### Is your feature request related to a problem?
No

### Describe the solution / feature you'd like
Is it possible to implement a binary sensor to indicate wether the pixel clock is currently connected to a power source and is charging? If so could you please implement a binary sensor to show charging state?

### Additional context
**The idea behind:** If the pixel clock runs on a power source I usually disable the battery app. But sometimes the clock is running on battery and in this case the battery app is helpful. If one could determine the current state wether the pixel clock is on power source or runs on battery I could write an automation to automatically enable or disable the battery app.

**Comment by Blueforcer** [comment]
Unfortunally its not possible to detect, the ESP isnt connected to the charging hardware.
