### ISSUE TITLE
[FEATURE REQUEST] WebUI Password Protection

### ISSUE THREAD

**Issue by DanijelVOCKIC** [Blueforcer/awtrix-light#66]
Idea: WebUI Password Protection

**Something like this:** 

<script language="JavaScript">
var pass_entered;
var password="test1234";
while (pass_entered!=password) {
    pass_entered=prompt('Please enter the password:','');
}
self.close();
</script>

**Comment by Blueforcer** [comment]
Unfortunately the used webserver library doesn't support it. And im also not a web developer.

Why we need a password protection for a local operating device?

I will close this issue for now, and will implement it as soon as the lib can do it.
Or if you have knowledge, feel free to open a PR
