### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by pdeheij** [Blueforcer/awtrix-light#67]
# Bug report

Clock is bricked 
## Additional information
Clock stays on 02:36:34 and wil not reset with button, also the com port does work anymore, flashing not posible
- Devices involved:
  - Model: Ulanzi Awtrix Smart Pixel Clock 2882 (TC001)
  - AWTRIX-LIGHT version:  v0.54 ]

## To Reproduce
Can not reproduce, clock is bricked

## Logs

```text
(optional) Add relevant logs which could help tackle the problem.
```

**Comment by Blueforcer** [comment]
Clock isn't brickable.
Can you turn it off while holding left and right button simultaneously?

**Comment by Nash2112** [comment]
Disable MQTT. V0.53 OK  V.055 Start, Crash, Start, etc

**Comment by Nash2112** [comment]
Die Uhr startet nach dem Update, zeigt IP Adresse an, dann kommt ein noch oben fliegendes Z und die Uhr startet neu. 
Uhr Ulanzi, Version 0.55, Iobroker MQTT Server

The clock starts after the update, shows IP address, then comes a still flying Z above and the clock restarts.
Clock Ulanzi, version 0.55, Iobroker MQTT Server

**Comment by Blueforcer** [comment]
> Die Uhr startet nach dem Update, zeigt IP Adresse an, dann kommt ein noch oben fliegendes Z und die Uhr startet neu. 
> Uhr Ulanzi, Version 0.55, Iobroker MQTT Server
> 
> The clock starts after the update, shows IP address, then comes a still flying Z above and the clock restarts.
> Clock Ulanzi, version 0.55, Iobroker MQTT Server

Dann mach doch dafür ein eigenes issue auf? Oder komm auf den discord.

**Comment by pdeheij** [comment]
> Clock isn't brickable by software. Can you turn it off while holding left and right button simultaneously?

Yes it turns off, but does not turn on anymore, still no comport

**Comment by Blueforcer** [comment]
Is the battery charged? It will not turn on with empty battery even plugged in.

There are some reports of dead clocks. But this is a hardware failure and has nothing to do with this software. Contact ulanzi for a replacement.

**Comment by martin131** [comment]
@pdeheij Any solution, please? Battery seems to be charged but i cannot turn on clock

**Comment by Blueforcer** [comment]
If the com port doesn't work it's a hardware failure and has nothing to do with the firmware. Contact Ulanzi to get a replacement

**Comment by pdeheij** [comment]
@martin131 No, contacted Ulanzi, waiting for answer, hoping in replacement.

**Comment by Blueforcer** [comment]
> @Blueforcer  It is very strange. Yesterday my clocks were delivered. I flashed Awtrix Light on both. And today both of them stopped working. Both was on different USB adapter. 

There are many users the last time, who have broken clocks. But this seems to depend on the latest batches. There are lots of older users without problems.

The ESP has no physical connection to the power management. It only gets the 3,3V if you turn it on. That's it. If you doesn't hear a short beep while turning on, the ESP gets no power.

**Comment by Blueforcer** [comment]
heres a photo from a user with the same problem
Its clearly a hardware failure
![image](https://user-images.githubusercontent.com/31169771/233675371-ff1a633b-ea6f-42a5-8ae9-b4f013e6e9d6.png)

**Comment by martin131** [comment]
OK, I send an email to Ulanzi support. I bought three clocks total so I will try to turn on the third one.

**Comment by Blueforcer** [comment]
You can also try to let it run with the original firmware for some days

**Comment by martin131** [comment]
Yes, I will. I turned on "matrix" animation and full brightness 🙂

**Comment by martin131** [comment]
I think this is weird. Temperature sensor was very hot while charging. Same behavior on both clocks. 
![Screenshot_2023-04-21-21-52-47-94_c3a231c25ed346e59462e84656a70e50](https://user-images.githubusercontent.com/4062374/233723399-39e52ecf-d78d-457d-b7cf-18d27c9ee24c.jpg)

**Comment by Blueforcer** [comment]
My device is currently connected to my PC and receiving a low amount of current, but enough to prevent discharge. Therefore, I haven't experienced any issues for over two months. However, it appears that the charging regulator may be undersized, which would explain the blown ICs and high temperature.

**Comment by MrRodz** [comment]
[pdeheij](https://github.com/pdeheij)

> > Clock isn't brickable by software. Can you turn it off while holding left and right button simultaneously?
> 
> Yes it turns off, but does not turn on anymore, still no comport

Hi I have the same issue, when you plug the charger in does the light on the back light up for you?

**Comment by supremelucifer** [comment]
> [pdeheij](https://github.com/pdeheij)
> 
> > > Clock isn't brickable by software. Can you turn it off while holding left and right button simultaneously?
> > 
> > 
> > Yes it turns off, but does not turn on anymore, still no comport
> 
> Hi I have the same issue, when you plug the charger in does the light on the back light up for you?

Got the same thing and mine does light on the back

**Comment by Dawnes** [comment]
Flashed 0.57 over 0.56 that had been running a week or so, and 1 hour later I had exactly this issue. Completely dead. No serial. Charging light is still working.  Not saying it is firmware but it happened right after updating.

**Comment by supremelucifer** [comment]
Just send them a mail. They will send you a new one without wanting the old one back. 
![image](https://user-images.githubusercontent.com/70238544/233832198-104b8752-5fb1-44d7-a7ac-ab17e420e176.png)

**Comment by djungelola** [comment]
> I have the same thing. During the night the clock disconnected from the network (went unavailable in HA) and I couldn't switch on the clock. The power led is on, and after a couple of hours it is turning green. Can't get is powered up again though, no beep no display.
> 
> I am wondering how to open the case. I saw the photo but I didn't succeed yet opening the case without destroying it.

I know how to do it :-) Did it yesterday myself.
The screen is glued to the case. I used a hairdryer to warm it up for about 10 min. The gently stick in something between the screen and the case. Warm more if needed. Then remove the screws and you have access to the circuitboard.

i didnt find any components that looked burned at all, but still only the charging led is lit up. seems to charge the battery though.
very strange that so many people have this problem to be honest.

Br Ola
![ulanzi](https://user-images.githubusercontent.com/6004620/234045188-1881869a-43b1-421a-bcc1-1ca7f770df45.jpg)

**Comment by floschibo** [comment]
Same here. No way to get the clock running again. Clock was charging for three days with matrix off. Contacted support now.

**Comment by Dawnes** [comment]
@supremelucifer I got a refund too, so all is good. It must be a faulty batch.

**Comment by pdeheij** [comment]
I also get a new one, but had a good advise form Ulanzi. The charcher i use was a Samsung with the capabilty for fastcharge. This means it is posible that 9V is provided to the clock. Use a old 5V charger !! was the advice. Must say that Ulanzi has a very good service!. Next week i have a few days off and try to open the defective clock. Maybe somthing interesting comes out.

**Comment by martin131** [comment]
I can confirm that one of my clocks died at Quick Charge 3.0 charger. About the second one, I am not sure.

**Comment by Mauricevb** [comment]
I was using an old 5V 1A iPhone charger. So I don't think it has anything to do with the charger 🤔

**Comment by MrRodz** [comment]
They are sending me a new one. They say it should be a 5v1a charger. I was using a 1.2a charger.

**Comment by MrRodz** [comment]
![IMG_2925](https://user-images.githubusercontent.com/38086707/234362673-3fc85db8-658b-4d9a-82bd-7202ef1cd654.jpeg)

so I’ve pulled my clock apart and traced my fault to this regulator. I have 3.7v going in and nothing coming out. It has GU2Z written on it. I can’t find that one online but have seen some others but not sure if they would be compatible.

**Comment by Blueforcer** [comment]
It's everytime the same IC. I posted a photo some posts before where it blows up. I think this is kind of switch, transistor whatever wich gives the power to the esp when you turn it on.

**Comment by Dawnes** [comment]
Question now is, will a replacement unit be any better? Was it bad luck for this batch, or did they change the circuit/components recently and all will fail?

@Blueforcer Your clock is probably older and does not have this issue. Any idea if the circuitboard is different?
@MrRodz Do you think a bypass of this chip would be an option? I really can't tell what it is supposed to do, but if it is a regulator and 3.7 is coming in, we should be ok right?

**Comment by MrRodz** [comment]
No a bypass will potentially blow the esp, from what data sheets i found it gives a constant 3,3v out to the esp from a 2.4-5.5v input. The supply comes through a mosfet too witch i think turns off the supply if the voltage goes too low from the battery. 

Hopefully i can just replace the regulator if i can find one. 

There is no guarantee that the new ones will be any better, guess we will just have to find out. 

I did find 

https://twitter.com/rm83/status/1621194459965788160

With some pics of a working one from two months ago, but the board looks the same

**Comment by Blueforcer** [comment]
In my discord server (https://discord.gg/cyBCpdx), all users with the board date 2023-3-2 have this problem.
![image](https://user-images.githubusercontent.com/31169771/234414986-25b4961f-a8e7-4188-aa85-c8df9c974481.png)

I received my two clocks before this date. I will check my pcb stamp tommorow

**Comment by MrRodz** [comment]
Unfortunately thats the board i have. Did any of your other users find a fix or work around?

**Comment by Blueforcer** [comment]
> Unfortunately thats the board i have. Did any of your other users find a fix or work around?

https://discord.com/channels/546407049148366859/1096822468737511574/1101222937501126778

**Comment by barbiudo** [comment]
same issue here, clock dead, board date 2023-3-2  :-(

**Comment by StormyKnight17** [comment]
So my first clock died within 6hrs of use. Second is going well so far, running for 24hrs so far ....

**Comment by darkpoet78** [comment]
My first still runs.  My second suddenly froze up while displaying the time.  I could turn it off but not on again... I'll contact them direct on Aliexpress (a good reason to always buy from the official store even if it's a few bucks more) but in the meantime... I took some good pics while pulling it apart if anyone else feels the need to pull theirs apart without destroying it.

[Imgur Link](https://imgur.com/a/2p2miqF)

**Comment by scarolan** [comment]
Same failure here, clock froze, after reset screen won't come on at all.  I will contact Ulanzi about the HW failure.

**Comment by scarolan** [comment]
> Just send them a mail. They will send you a new one without wanting the old one back. ![image](https://user-images.githubusercontent.com/70238544/233832198-104b8752-5fb1-44d7-a7ac-ab17e420e176.png)

Shame to waste a good device. Has anyone had luck de-soldering and replacing the failed voltage regulator?

**Comment by ptrkp** [comment]
Today I received a new clock after the first one died after a month or so.
Did take the broken one apart, would be nice if it is fixable.

**Comment by ptrkp** [comment]
Removed the faulty charge controller and the battery and solder a 5v to 3.3v stepdown converter on to the pcb.
Clock working again.

![IMG_9097](https://github.com/Blueforcer/awtrix-light/assets/115818953/0a5e932f-ed93-479d-9e4a-147fe1e05b17)

**Comment by Mauricevb** [comment]
> Removed the faulty charge controller and the battery and solder a 5v to 3.3v stepdown converter on to the pcb. Clock is working again.

Nice! Would you mind sharing the exact part(s) that you used?

**Comment by darkpoet78** [comment]
Yes, please do... over on Discord someone recommended a STI3408B.  I've got a few on the way from Aliexpress.  I'll also report back if it was a success or not.

**Comment by ptrkp** [comment]
I'm not responsible if somethings goes wrong, you need to have knowledge of how to solder and how to work with a multimeter.
Remove the charge controller and clean the surface. Check with the multimeter if there are no shortages anymore.
Check if there is 5v.

Solder the 3.3v step down converter with some wires to the pcb

Step down 3.3 converter
https://www.amazon.com/Alinan-Efficiency-Converter-Regulator-Stabilized/dp/B09W8P1QNM or something similar.

![signal-2023-06-17-003310_002](https://github.com/Blueforcer/awtrix-light/assets/115818953/92042ce5-5737-4d93-a1b1-5497a5671569)

![signal-2023-06-17-003310_003](https://github.com/Blueforcer/awtrix-light/assets/115818953/4226fdfd-6296-4041-9bc1-67ece21e89c0)

**Comment by stefangries** [comment]
I can confirm, that replacing the part at position A_U1 (GU2B) with a new STI3408B fixes this problem. I got mine on [AliExpress](https://www.aliexpress.com/item/1005004307132691.html).

**Comment by darkpoet78** [comment]
Still waiting on my replacement STI3408Bs but in the meantime, I contacted Ulanzi through their official store and they're charging less than a dollar for a replacement.  It's great to see a company like this stand behind their product even if they screwed something up.  Here's hoping they rectified the issue... has anyone opened up one from the new batch to confirm it doesn't use the GU2B any more?

**Comment by trip5** [comment]
@stefangries Yup.  SMD soldering isn't my thing.  After removing the old regulator, I made 3 attempts but just ended up ripping the trace on the board.  I had an adjustable voltage regulator laying around so I set it to 3.3V and followed the pics @ptrkp posted.  Thanks a lot!  It might be lacking the battery but it works... although lol a bit weird that you have to press the left and right buttons to turn it on after plugging it in... but it works.

**Comment by Calimerorulez** [comment]
Mine just died too, bought late April on AliExpress. It froze on displaying the time. I've sent them a message.

**Comment by ptrkp** [comment]
> @stefangries Yup. SMD soldering isn't my thing. After removing the old regulator, I made 3 attempts but just ended up ripping the trace on the board. I had an adjustable voltage regulator laying around so I set it to 3.3V and followed the pics @ptrkp posted. Thanks a lot! It might be lacking the battery but it works... although lol a bit weird that you have to press the left and right buttons to turn it on after plugging it in... but it works.

Are your temperature and humidity readings still working? Mine are dead not sure what happened there.

**Comment by trip5** [comment]
My temp and humidity sensor still function, yes but... not more accurate than before.  So, still basically useless.  If you accidentally hit them with 5V, you could have killed them.  ESPs can survive that voltage but sensors can be fried.  Maybe static, too...  I've also killed BME sensors with heat (ie too much soldering) so there's a million ways you could have killed them.  

Honestly I'd consider it a win to have the board still working... I was willing to throw the whole board out and try to wire up a new ESP32 to the buttons and screen.

**Comment by stefangries** [comment]
> Are your temperature and humidity readings still working? Mine are dead not sure what happened there.

Mine are still working. However, their values are completely unusable, as they are much too high. However, they were also not correct before. I think it is simply warmer in the housing where the sensor is located.

**Comment by ptrkp** [comment]
Try to hook an external one SHT31 but that also did not work, so I think more things got fried when the clock went dead.
But the values where useless so I can live without it.

**Comment by Mauricevb** [comment]
> I'm not responsible if somethings goes wrong, you need to have knowledge of how to solder and how to work with a multimeter. Remove battery, you don't need that anymore, clock will only work via usb-c. Remove the charge controller and clean the surface. Check with the multimeter if there are no shortages anymore. Check if there is 5v.
> 
> Solder the 3.3v step down converter with some wires to the pcb
> 
> Step down 3.3 converter https://www.amazon.com/Alinan-Efficiency-Converter-Regulator-Stabilized/dp/B09W8P1QNM or something similar.
> ....
> Be care full, I broke the reset button upper left near usb-c connector.

Thank you @ptrkp! I was able to fix mine with this. It was hard to remove the charge controller, but I managed do it apparently.

**Comment by Calimerorulez** [comment]
I soldered a step down converter like @ptrkp did, and the clock is working again. Thank you for the pictures 😃

**Comment by scarolan** [comment]
@ptrkp you are the real MVP...thanks for the photo and tutorial

**Comment by JoFranke** [comment]
Excellent, thanks for all that information. I actually have three bricked devices now, and I hope Ulanzi will replace them as they are just a few weeks old.

The question is, did they fix the issue, or will the replacement ones fail again - does anyone has any experiance with the replacement? If it is not fixed, I will try to get a refund instead....thanks.

**Comment by Blueforcer** [comment]
> The question is, did they fix the issue, or will the replacement ones fail again - does anyone have any experiance with the replacement? If it is not fixed, I will try to get a refund instead....thanks.

according to the productmanager, its fixed.

**Comment by JoFranke** [comment]
> according to the productmanager, its fixed.

Thats good news, thanks for the info - I'm from Germany and could send you two bad ones if they dont want them back. PM for details :)

**Comment by Blueforcer** [comment]
How to PM in github? 😮

**Comment by JoFranke** [comment]
> How to PM in github? 😮

Sent you a mail to your website admin address

**Comment by StormyKnight17** [comment]
I ordered another after getting a credit for the first & it has been working fine for 3 months. My first failed in 24hrs. CheersRichardSent from my iPhoneOn 1 Aug 2023, at 18:06, Stephan ***@***.***> wrote:﻿

The question is, did they fix the issue, or will the replacement ones fail again - does anyone have any experiance with the replacement? If it is not fixed, I will try to get a refund instead....thanks.

according to the productmanager, its fixed.

**Comment by trip5** [comment]
I've been struggling trying to find a solution to the solution... removing the battery and using the solution **ptrkp** posts above has an oddity.  De-powering and re-powering the device requires holding the left and right buttons to turn on the display.  The device itself is still on... it just doesn't activate the display.  I even tried emulating output to the buttons but that doesn't work.

Is there some way to avoid this and just have the display come on immediately with power?

Sidenote, my first Ulanzi and the replacement for the second are still functioning great.  It really must have been a bad batch.

**Comment by xkvmoto** [comment]
Thank you!!!! I suffered a dead clock 
I was able to replace the faulty STI3408B with a new one (it's quite a hassle to unsolder and re-solder...)
Now it works like new.

**Comment by corneyl** [comment]
> Is there some way to avoid this and just have the display come on immediately with power?

@trip5, a bit late to the party, but for me following this guide on reddit worked well: https://www.reddit.com/r/homeassistant/comments/1grzksj/ulanzi_tc001_always_on_mod_battery_removal/

The main difference to the instructions from @ptrkp is to add an extra wire between the top/bottom pins of IC2. This makes the clock think the battery is always full, so it powers on as soon as you connect the power supply.
