### ISSUE TITLE
[FEATURE REQUEST] E1.31 integration

### ISSUE THREAD

**Issue by 120318** [Blueforcer/awtrix-light#71]
# Feature Request

### Is your feature request related to a problem?
No
### Describe the solution / feature you'd like
I hope awtrix-light can support the E1.31 protocol, so that I can directly control the pixel display through other software, such as openrgb. it's so cool.

### Describe alternatives you've considered
WLED, Awtrix
### Additional context
I found that awtrix has already supported it, will there be a plan to support awtrix-light

**Comment by Blueforcer** [comment]
https://github.com/Blueforcer/awtrix-light/releases/tag/0.60
