### ISSUE TITLE
Temperature has no decimals in Home Assistant entity

### ISSUE THREAD

**Issue by wilfredktlr** [Blueforcer/awtrix-light#72]
# Feature Request

### Is your feature request related to a problem?

No.

### Describe the solution / feature you'd like

Currently you can set the `temp_dec_places` in the file `dev.json` so the display shows the specified number of decimals. However the value of the Home Assistant entity doesn't contain any decimals.

### Describe alternatives you've considered

I have tried setting the precision of the entity in Home Assistant but that didn't work.

### Additional context

n/a

**Comment by smarthomejunkie** [comment]
I wouldn't use the temperature entity of the clock. The value is way off. I think it's better to use a temperature sensor in the room and show that value on the clock.

**Comment by wilfredktlr** [comment]
Agreed. The clock gets a bit warm and that distorts the value.
