### ISSUE TITLE
WIFI auto connect and send MQTT after recharge start 

### ISSUE THREAD

**Issue by matze20211** [Blueforcer/awtrix-light#76]
WIFI auto connect and send MQTT after recharge start , after shutdown because of a empty Accu and starts to recharge, the clock should automatically  connect to wifi and MQTT Server, and send a startup MQTT Message, if possible

**Comment by Blueforcer** [comment]
I think I don't understand.
There is always a wifi and Mqtt connect at start.

**Comment by matze20211** [comment]
Oh, my failure, i used "mqtt-toggle" to switch on/off with select Button, but thats not working.
