### ISSUE TITLE
[FEATURE REQUEST] Play sound when the indicators are activated

### ISSUE THREAD

**Issue by smarthomejunkie** [Blueforcer/awtrix-light#77]
# Feature Request

It would be nice to be able to play a sound when indicator 1 or indicator 2 is activated. So, for each indicator, a sound option would be great!

**Comment by Blueforcer** [comment]
closed with https://github.com/Blueforcer/awtrix-light/commit/d25b43279a3449ba0844166a6bc231495b869b5e
