### ISSUE TITLE
[FEATURE REQUEST / "BUG"] Scroll icon immediately with the text.

### ISSUE THREAD

**Issue by smarthomejunkie** [Blueforcer/awtrix-light#79]
# Feature Request
When a text in a custom app or notification is long, it scrolls automatically. If an (animated) icon is used in front of it, and the text starts scrolling, the text scrolls first one step to the left so that it "*touches*" the icon. After that, the icon starts scrolling. It would look nicer if the icon starts scrolling to the left immediately when the text starts scrolling so that it looks like a seamless scroll.

Not sure how to explain it more clearly.

**Comment by Blueforcer** [comment]
i think this is a matter of taste. in order to push something, you need to touch it first :)

**Comment by smarthomejunkie** [comment]
Fair enough!

**Comment by smarthomejunkie** [comment]
Thanks!
