### ISSUE TITLE
after Bat low, not connecting to WIFI and so not to MQTT

### ISSUE THREAD

**Issue by matze20211** [Blueforcer/awtrix-light#80]
# Bug report

## Describe the bug

If the Clock goes off because of low Bat, and power is again connected, clock not automatically  connecting again to WIFI and so not to MQTT Server
## Additional information

- Devices involved:
  - Model: Ulanzi Awtrix Smart Pixel Clock 2882 (TC001), two different devices
  - AWTRIX-LIGHT version: 0.57
  - 
## To Reproduce

Disconnect Power, wait until Bat is low and Device goes off, reconnect power, nothing happens, no connect to WIFI and MQTT.

After Restart, using both Buttons (</>), all is working well - Device connecting to WIFI and so to MQTT

## Expected behavior

After reconnect Power and load Bat, clock connected to WIFI and MQTT Server

**Comment by Blueforcer** [comment]
Of course you need to turn it on. Awtrix cannot turn itself on or off. The ESP32 has no connection to the powermanagement
