### ISSUE TITLE
Creating custom page not working

### ISSUE THREAD

**Issue by b-a-9-0** [Blueforcer/awtrix-light#9]
- MQTT prefix changed to "awtrix" in web ui.
- Sending MQTT message to "awtrix/custom/test"

- Message:
{
    "text": "512 W",
    "icon": "52090",
    "repeat": 1,
    "rainbow": false,
    "duration": 10,
    "color": "#FFFFFF",
    "hold": false
}

- Icon is uploaded to folder ICONS.

-> Custom page is not generated nor shown on display.

-> the same message to topic "awtrix/notify" works!

**Comment by Blueforcer** [comment]
Unfortunately, I can not reproduce. Works here with the same data flawlessly.
Any other informations i should know?

**Comment by b-a-9-0** [comment]
MQTT message is generated with node red:
![grafik](https://user-images.githubusercontent.com/10331861/227326167-36b126d1-01a4-4f8a-8153-f56f0a853108.png)

MQTT explorer:
![grafik](https://user-images.githubusercontent.com/10331861/227326426-6071f07a-0d01-41b0-b70a-22552e08edb2.png)

**Comment by b-a-9-0** [comment]
I currently only have the standard pages: time, date, temp, humidity, battery. Running version 0.33

**Comment by Blueforcer** [comment]
please update to latest 0.36 first. I cannot find bugs in older firmwares anymore :)

**Comment by b-a-9-0** [comment]
Works in 0.36!

**Comment by aptonline** [comment]
I'm seeing the same issue when testing the latest firmware (0.45). Not displaying custom pages with the following command:

Topic:
`awtrix_d670d0/custom/demo
`
Payload:
```
{
  "text": "Hello, AWTRIX Light!",
  "icon": "1",
  "rainbow": true,
  "duration": 10
}
```

Testing the same payload with `awtrix_d670d0/notify` **intermittently** works.  Testing by sending from Home Assistant and MQTTX where I can see the payload correctly delivered to MQTT,
