### ISSUE TITLE
[FEATURE REQUEST] Other language support

### ISSUE THREAD

**Issue by dalv666** [Blueforcer/awtrix-light#94]
# Feature Request

### Is your feature request related to a problem?

No

### Describe the solution / feature you'd like

I would like to request adding support for Russian in your application. So that you can display Russian characters on the clock. This would require drawing all the symbols for the language and integrating them into the current code. I am willing to assist with the drawing all the symbols. Is it possible to support another language?

### Describe alternatives you've considered

-

### Additional context
-

**Comment by Blueforcer** [comment]
Where you need another language?
For the Webinterface?

**Comment by dalv666** [comment]
Ability to send characters to display on the watch.

**Comment by Blueforcer** [comment]
the awtrix font only supports latin characters. There are no plans to extend this from my side,  because changing fonts is a very huge work.
 If you're able to do it, please feel free to open a PR.

https://github.com/Blueforcer/awtrix-light/blob/main/lib/MatrixUI/Fonts/AwtrixFont.h
