### ISSUE TITLE
[FEATURE REQUEST] Allow alternative syntax for custom App creation API via MQTT

### ISSUE THREAD

**Issue by m-zim** [Blueforcer/awtrix-light#98]
# Feature Request

### Is your feature request related to a problem?

I am using the MQTT broker from adafruit.io to make requests to the Ulanzi pixel clock with the Awtrix light firmware on it.
Unfortunately, the adafruit.io broker is limited in its functionality. In particular, it does not allow to use any hierarchy in the topic. So I cannot use the [PREFIX]/custom/[APP] topic to create a custom app.

### Describe the solution / feature you'd like

An added alternative syntax for the respective API that can be used without an additional hierarchy level in the topic would solve the problem. One possibility would be to change the Awtrix light firmware code such that [PREFIX]/custom.[APP] is supported as an additional alternative syntax for the respective API.

### Additional context

The adafruit.io broker comes with a connector to IFTT, which would allow a quite flexible setup without any additional hardware. Thus, it would be great if this proposed workaround to circumvent the limitation of the adafruit-Broker could be added.

**Comment by Blueforcer** [comment]
Its not possible for a mqqt client to subscibe to [PREFIX]/custom.[APP], beacuse custom.[APP] is unknown at this time.
Its only possible to subscribe to wildcards [PREFIX]/custom/[APP].

You can try to use http api
