### ISSUE TITLE
[FEATURE REQUEST] Allow to disable scroll in effect during app change

### ISSUE THREAD

**Issue by dg1yds** [Blueforcer/awtrix-light#99]
# Feature Request

### Is your feature request related to a problem?

No, no functional issue.
Changing apps can lead to an optically "ugly" behavior in case the previous app includes a longer text (scrolling necessary). 

### Describe the solution / feature you'd like

Direct change to new app view - without effects (like Awtrix2 behaviour).

### Describe alternatives you've considered

N/A

### Additional context

Thank you for considering my proposal and the work you put into the project.

**Comment by Blueforcer** [comment]
I think disabling the transition will not solve the initial problem.
